### PR TITLE
Upgrade GitLab to 12.6.0

### PR DESCRIPTION
**Pull request by solidnerd**

### CODE REVIEW

**Comment by sachilles** [comment]
Hi,

I tried to build and work with your `upgrade-to-12.6.0` branch. It builds without problems, but unfortunately the upgraded `gitlab-shell` does not work. 

Trying to clone an arbitrary repository results in an error message like
> bash: /home/git/gitlab-shell/bin/gitlab-shell: No such file or directory

I guess the problem is related to the fact that some changes inside the gitlab-shell archive happened. In particular in the compile script inside the bin directory is gone and thus, the gitlab-shell won't be compiled.

I hope this helps to fix the problem.

Best regards

**Comment by sachilles** [comment]
Hi,

I fixed the issue by running the command `make setup`. However, on order to run this command succesfully, one has to prepend the temporary directory of the go compiler to the `Makefile` of the gitlab-shell sources. Otherwise the go compiler won't be found since it is defined in a parent shell only and not in the subshells (opened by every make target).

To make it short. If you apply to following patch to your install script (`assets/build/install.sh`) also the gitlab-shell will work as expected.

```diff
diff --git a/assets/build/install.sh b/assets/build/install.sh
index b69018d..e0bd5ac 100755
--- a/assets/build/install.sh
+++ b/assets/build/install.sh
@@ -88,12 +88,10 @@ chown -R ${GITLAB_USER}: ${GITLAB_SHELL_INSTALL_DIR}

 cd ${GITLAB_SHELL_INSTALL_DIR}
 exec_as_git cp -a config.yml.example config.yml
-if [[ -x ./bin/compile ]]; then
-  echo "Compiling gitlab-shell golang executables..."
-  ./bin/compile
-  rm -rf go_build
-fi
-./bin/install
+sed -i '1s|^|export PATH := '"${GOROOT}"'\/bin:$(PATH)\n\n|' Makefile
+echo "Compiling gitlab-shell golang executables..."
+rm -rf go_build
+exec_as_git make setup

 # remove unused repositories directory created by gitlab-shell install
 rm -rf ${GITLAB_HOME}/repositories
```

Have fun.

Cheers

**Comment by Ilya-Kuchaev** [comment]
Any news here?

**Comment by sachilles** [comment]
Hi,

just follow the ongoing discussion <https://github.com/solidnerd/docker-gitlab/pull/1>.

Best regards

**Comment by cwildfoerster** [comment]
Time for 12.7.0

**Pull request merged**
