### PR TITLE
Upgrade to 8.9.0

### PR DESCRIPTION
**Pull request by SolidNerd**
#Hey, 
here is the upgrade for `8.9.0`. 
FYI: I run it on my production system and i tested a fresh installation both system works as excepted.
/cc @sameersbn

### CODE REVIEW

**Comment by sameersbn** [comment]
@SolidNerd please hold on to the merge. Will review and merge it my self.

**Comment by jvdgeest** [comment]
Well done @SolidNerd! Looks like an easy upgrade with one new cronjob.

**Comment by SolidNerd** [comment]
@sameersbn This should only the preparation of the next release. I hope that makes your process of upgrading easier.

**Comment by sameersbn** [comment]
P.R. was merged in fd6f96db808803f0798b74ccd4a5f8c3fab4a9b8
Release has been made

**Pull request closed without merging**
