### PR TITLE
Add nginx retain ip header

### PR DESCRIPTION
**Pull request by gaoyifan**
If docker container runs behind a reverse proxy (like CDN), unicorn cannot get real client IP, because nginx overrides HTTP header `X-Forwarded-For` and `X-Real-IP`. 

`NGINX_RETAIN_IP_HEADER` parameter let nginx retain `X-Forwarded-For` and `X-Real-IP`.

### CODE REVIEW

**Comment by knight42** [comment]
ping @sameersbn @solidnerd

**Comment by solidnerd** [comment]
I will test this feature within a week and will give you feedback after that. I hope it's okay for you.

**Comment by knight42** [comment]
@solidnerd Any progress?

**Comment by lenovouser** [comment]
Seems like a good feature to me 👍

**Comment by solidnerd** [comment]
Should this be done for [nginx-ssl](https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/config/nginx/gitlab-ssl) as well ? Is it a possible test case ?

**Comment by lenovouser** [comment]
Yep, should be done for the SSL part too IMO

**Comment by knight42** [comment]
@solidnerd 
`nginx_configure_gitlab_retain_ip_header()` is called in `nginx_configure_gitlab()`, which means it directly modify `/etc/nginx/sites-enabled/gitlab`, hence I think there is no need for this to be done for `nginx-ssl`.

**Comment by phenomax** [comment]
Do we have any updates here?
I also agree that this PR adds an useful feature to this docker image.

**Comment by dmednis** [comment]
When can we expect this to be merged? 
This would be a really useful feature.

**Comment by gaoyifan** [comment]
@dmednis  You can try [this fork](https://github.com/ustclug/docker-gitlab). Maintained by @knight42

**Comment by 3kami3** [comment]
I tried setting [GitLabCE official document](https://docs.gitlab.com/omnibus/settings/nginx.html#configuring-gitlab-trusted_proxies-and-the-nginx-real_ip-module), so please also try this PR #1137.

**Comment by gaoyifan** [comment]
Agree with @3kami3 😀.  I think the implementation in #1137 is safer. And I will close this one.

**Pull request closed without merging**
