### PR TITLE
Add helm chart

### PR DESCRIPTION
**Pull request by yuanying**
Helm chart is useful to install this project into Kubernetes
environment. This makes kubernetes manifest configurable for
each own environment.

### CODE REVIEW

**Comment by solidnerd** [comment]
Hey @yuanying, 
this is looking really great. I think we should synchronise it with #1211 and see the progress for that. Probably what I think is that we make an new folder for kubernetes it could be `k8s` and it contains the chart and the plain from #1211

**Comment by yuanying** [comment]
@solidnerd Hi, thanks for your review!
Yes, I saw #1211.
Which is better to create k8s folder before this commit or after this?
Or I should create k8s folder in this PR?

**Comment by solidnerd** [comment]
@yuanying Is it still in WIP or could I do a final check to merge it ?

**Comment by yuanying** [comment]
Hi, I'm still working this but I'll update soon.

**Comment by yuanying** [comment]
@solidnerd Hi, sorry for late reply. Now it's ok to merge this!

**Pull request closed without merging**
