### PR TITLE
Upgrade GitLab CE to 14.10.4 - Critical security release

### PR DESCRIPTION
**Pull request by omueller**
GitLab Critical Security Release: 15.0.1, 14.10.4, and 14.9.5
https://about.gitlab.com/releases/2022/06/01/critical-security-release-gitlab-15-0-1-released/

**14.10.4***
- gitlab: upgrade CE to v14.10.4
- gitaly: upgrade to v14.10.4

### CODE REVIEW

**Comment by omueller** [comment]
Hi, this is an attempt at getting 14.10.3 upgraded to 14.10.4, using tags/14.10.3.   Not sure I did this correctly...  Best regards & nice week-end to you, Olivier

**Comment by omueller** [comment]
Hi @sameersbn and @sachilles, checks/build/test seems fine, do you think a release of 14.10.4 sometime later would be possible ?  We plan to wait a bit until upgrading to the 15.x.y branch, and applying this critical security update would still be quite important under 14.10.x. 

Please let me know if there is anything else I can/should do, 14.10.3->14.10.4 was a simple search/replace. 

Best regards & merci!  --Olivier

**Comment by sachilles** [comment]
@omueller First of all I would like to thank you for your contribution.

> Hi, this is an attempt at getting 14.10.3 upgraded to 14.10.4, against tags/14.10.3. Not sure I did this correctly... Best regards & nice week-end to you, Olivier

I guess you did a mistake. Could you change the target of your PR? Currently, the PR is to be placed on the HEAD of the master branch. Please change the target (currently it corresponds to `sameersbn:master`).

**Comment by omueller** [comment]
Hi @sachilles, thx for your reply, no sure how to do that, I will have a look.  Here I see only this:

**Comment by sachilles** [comment]
Hi,

sorry for my late reply. I created a branch `14.10.x-stable` in order to catch your PR.

grafik

 Hopefully, the CI does not complain while using this branch for releasing. But let's go step by step. First, please be free to merge your PR on the head of the suitable branch.

**Comment by omueller** [comment]
Thanks a lot @sachilles, base branch switched now, I hope this will be ok like this!  Best regards & bonne journée!

**Review by sachilles — APPROVED** [review]
LGTM

**Comment by sachilles** [comment]
@omueller The CI is running and the corresponding release will be published automatically. Thanks for your contribution.

**Comment by omueller** [comment]
Thanks for the release, installed in production this week-end, everything working as expected.

**Pull request merged**
