### PR TITLE
[GitLab Security Release] Upgrade GitLab CE to 14.9.2

### PR DESCRIPTION
**Pull request by sachilles**
GitLab Critical Security Release: 14.9.2 (see https://about.gitlab.com/releases/2022/03/31/critical-security-release-gitlab-14-9-2-released/)

### CODE REVIEW

**Comment by sachilles** [comment]
Build failure due to missing version of gitlab pages

```
Downloading gitlab-pages v.1.56.1...
warning: Could not find remote branch v1.56.1 to clone.
fatal: Remote branch v1.56.1 not found in upstream origin
```

This is really strange. Following https://gitlab.com/gitlab-org/gitlab-foss/-/blob/v14.9.2/GITLAB_PAGES_VERSION GitLab Pages in version 1.56.1 has to be used. On the other hand, in the [gitlab pages repo](https://gitlab.com/gitlab-org/gitlab-pages/-/tags) exactly this tag is currently missing...

Probably I should wait until tomorrow and check the information and published versions again.

**Comment by sachilles** [comment]
Reported this issue in https://gitlab.com/gitlab-org/gitlab-pages/-/issues/724 .

**Comment by sachilles** [comment]
Now that the missing tag has appeared, I restart the pipeline.

**Comment by xueshanf** [comment]
@sachilles Thank you  for releasing this security patch image so promptly!

**Pull request merged**
