### PR TITLE
Upgrade GitLab CE to 16.3.0

### PR DESCRIPTION
**Pull request by sachilles**
GitLab 16.3 Release (see <https://about.gitlab.com/releases/2023/08/22/gitlab-16-3-released/>)

### CODE REVIEW

**Comment by kkimurak** [comment]
Test fails because gitlab does not launch. This is reproduced on my local test environment.

There is a bug in a process to add lfs object URL to allow list of content security policy setting.
See original MR gitlab-org/gitlab!127059 : https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127059.  
It tries to load `gitlab.lfs.object_store.connection` even `gitlab.lfs.object_store.enabled = false`.  
Luckyly fix MR is going on upstream (not merged yet): https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129985 , but we may be o add patch for sameersbn/gitlab:16.3.0 release.

````diff
diff --git a/lib/gitlab/content_security_policy/config_loader.rb b/lib/gitlab/content_security_policy/config_loader.rb
index 9fb3c7d362f..d012c8b3b7b 100644
--- a/lib/gitlab/content_security_policy/config_loader.rb
+++ b/lib/gitlab/content_security_policy/config_loader.rb
@@ -84,7 +84,7 @@ def allow_snowplow_micro(directives)
         end
 
         def allow_lfs(directives)
-          return unless Gitlab.config.lfs.enabled && LfsObjectUploader.direct_download_enabled?
+          return unless Gitlab.config.lfs.enabled && Gitlab.config.lfs.object_store.enabled && LfsObjectUploader.direct_download_enabled?
 
           lfs_url = build_lfs_url
           return unless lfs_url.present?

````

----

<details>
  <summary>docker log on launching 16.3.0 (local build by me)</summary>

  ```
Loading /etc/docker-gitlab/runtime/env-defaults
Initializing logdir...
Initializing datadir...
Generating OpenSSH host keys... RSA DSA ECDSA ED25519 
Container TimeZone -> Asia/Tokyo
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database.......
Configuring /home/git/.postgresqlrc to avoid version mismatch on dumping
- Detected server version: 140008
- Generating /home/git/.postgresqlrc
14 postgresql:5432 gitlabhq_production
- Uninstalling unused client(s): postgresql-client-13 postgresql-client-15 
Configuring gitlab::redis
Configuring gitlab::actioncable
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::gitaly...
Configuring gitlab::monitoring...
Configuring gitlab::gitlab-workhorse...
Configuring gitlab::puma...
Configuring gitlab::timezone...
Configuring gitlab::rack_attack...
Configuring gitlab::ci...
Configuring gitlab::artifacts...
Configuring gitlab::packages...
Configuring gitlab::terraform_state...
Configuring gitlab::lfs...
Configuring gitlab::uploads...
Configuring gitlab::mattermost...
Configuring gitlab::project_features...
Configuring gitlab::smtp_settings...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::cron_jobs...
Configuring gitlab::backups...
Configuring gitlab::backups::schedule...
Configuring gitlab::registry...
Configuring gitlab::pages...
Configuring gitlab::sentry...
Configuring gitlab::content_security_policy...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...
Setting up GitLab for firstrun. Please be patient, this could take a while...
2023-08-23 11:15:18,799 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2023-08-23 11:15:18,799 INFO Included extra file "/etc/supervisor/conf.d/gitaly.conf" during parsing
2023-08-23 11:15:18,799 INFO Included extra file "/etc/supervisor/conf.d/gitlab-workhorse.conf" during parsing
2023-08-23 11:15:18,799 INFO Included extra file "/etc/supervisor/conf.d/groups.conf" during parsing
2023-08-23 11:15:18,799 INFO Included extra file "/etc/supervisor/conf.d/mail_room.conf" during parsing
2023-08-23 11:15:18,799 INFO Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2023-08-23 11:15:18,799 INFO Included extra file "/etc/supervisor/conf.d/puma.conf" during parsing
2023-08-23 11:15:18,799 INFO Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
2023-08-23 11:15:18,799 INFO Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
2023-08-23 11:15:18,799 INFO Set uid to user 0 succeeded
2023-08-23 11:15:18,804 INFO RPC interface 'supervisor' initialized
2023-08-23 11:15:18,804 INFO supervisord started with pid 1715
2023-08-23 11:15:19,808 INFO spawned: 'gitaly' with pid 1721
2023-08-23 11:15:19,810 INFO spawned: 'puma' with pid 1722
2023-08-23 11:15:19,811 INFO spawned: 'gitlab-workhorse' with pid 1723
2023-08-23 11:15:19,812 INFO spawned: 'sidekiq' with pid 1724
2023-08-23 11:15:19,813 INFO spawned: 'sshd' with pid 1725
2023-08-23 11:15:19,814 INFO spawned: 'nginx' with pid 1730
2023-08-23 11:15:19,816 INFO spawned: 'cron' with pid 1731
2023-08-23 11:15:21,280 INFO success: gitaly entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-23 11:15:21,280 INFO success: puma entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-23 11:15:21,280 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-23 11:15:21,280 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-23 11:15:21,280 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-23 11:15:21,280 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-23 11:15:21,280 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
/home/git/gitlab/lib/gitlab/instrumentation/redis.rb:9: warning: already initialized constant Gitlab::Instrumentation::Redis::ActionCable
/home/git/gitlab/lib/gitlab/instrumentation/redis.rb:9: warning: previous definition of ActionCable was here
2023-08-23 11:15:43,309 INFO exited: sidekiq (exit status 1; not expected)
2023-08-23 11:15:43,311 INFO spawned: 'sidekiq' with pid 1775
rake aborted!
GitlabSettings::MissingSetting: option 'connection' not defined
/home/git/gitlab/lib/gitlab_settings/options.rb:159:in `method_missing'
/home/git/gitlab/app/uploaders/object_storage.rb:165:in `object_store_credentials'
/home/git/gitlab/app/uploaders/object_storage.rb:366:in `fog_credentials'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/carrierwave-1.3.3/lib/carrierwave/storage/fog.rb:485:in `fog_provider'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/carrierwave-1.3.3/lib/carrierwave/storage/fog.rb:359:in `public_url'
/home/git/gitlab/lib/gitlab/content_security_policy/config_loader.rb:197:in `build_lfs_url'
/home/git/gitlab/lib/gitlab/content_security_policy/config_loader.rb:89:in `allow_lfs'
/home/git/gitlab/lib/gitlab/content_security_policy/config_loader.rb:24:in `default_directives'
/home/git/gitlab/lib/gitlab/content_security_policy/config_loader.rb:206:in `initialize'
/home/git/gitlab/config/initializers/content_security_policy.rb:12:in `new'
/home/git/gitlab/config/initializers/content_security_policy.rb:12:in `block in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/actionpack-7.0.6/lib/action_dispatch/http/content_security_policy.rb:175:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/application/configuration.rb:422:in `new'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/application/configuration.rb:422:in `content_security_policy'
/home/git/gitlab/config/initializers/content_security_policy.rb:11:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/engine.rb:667:in `load'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/engine.rb:667:in `block in load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.6/lib/active_support/notifications.rb:208:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/engine.rb:666:in `load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/engine.rb:619:in `each'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/engine.rb:619:in `block in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `run'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/initializable.rb:50:in `each'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/initializable.rb:60:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/application.rb:372:in `initialize!'
/home/git/gitlab/config/environment.rb:7:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/application.rb:348:in `require_environment!'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/railties-7.0.6/lib/rails/application.rb:506:in `block in run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:24:in `execute'
/home/git/gitlab/lib/tasks/gitlab/helpers.rake:7:in `block in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:24:in `execute'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)
```
</details>

**Comment by sachilles** [comment]
Thanks for the hint. Should we also take into account the second adjustment of the MR in [#129985](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129985) (i.e. `spec/lib/gitlab/content_security_policy/config_loader_spec.rb`)?

**Comment by kkimurak** [comment]
> Should we also take into account the second adjustment of the MR in [#129985](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129985) (i.e. spec/lib/gitlab/content_security_policy/config_loader_spec.rb)?

Not required, I think. It is a change for test code. I made sure gitlab launches successfully without it.

**Comment by Swati-Gawali** [comment]
Please share the upgrade path from Gitlab CE from 15.9.1 to 16.x.x

**Pull request merged**
