### PR TITLE
Upgrade to Gitlab CE 10.5.3 and 10.5.4 and 10.5.5

### PR DESCRIPTION
**Pull request by Kiina**
On top of #1532 

https://about.gitlab.com/2018/03/09/gitlab-10-5-4-released/

Currently running on my Server without any issues.

### CODE REVIEW

**Comment by xNevo** [comment]
lgtm

**Comment by fmauNeko** [comment]
GITLAB_PAGES_VERSION should be bumped to 0.6.1, as in https://gitlab.com/gitlab-org/gitlab-ce/blob/v10.5.4/GITLAB_PAGES_VERSION

**Comment by Kiina** [comment]
Oh forgot about that. Should be correct now

**Comment by cwildfoerster** [comment]
lgtm @sameersbn @solidnerd

**Comment by GJRTimmer** [comment]
@sameersbn @solidnerd Any idea when this will be merged ?

**Comment by Kiina** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG.md

10.5.5 is already tagged. Blogpost will probably follow soon, so I already pushed the commit for 10.5.5

**Comment by mathewpeterson** [comment]
I believe they require a single PR per version bump because they cut a docker image for each release.

It might be better to create multiple pull requests.

**Comment by Kiina** [comment]
I'm think dockerhub builds a release for each tag and it only needs to be separated by commit, but maybe I'm wrong on that.

**Comment by masakij** [comment]
https://about.gitlab.com/2018/03/16/gitlab-critical-release-preannouncement/

Critical Security update is announced. It will be released on Tuesday, March 20th, 2018 at 23:59 UTC.
They recommend installations running affected versions to upgrade immediately.
Probably, 10.5.x may also be affected.

**Comment by solidnerd** [comment]
@Kiina  Thanks for you work looks so far good to me. I will cherry-pick them to release every patch as an independent release.

**Comment by solidnerd** [comment]
Everything is done I will close this PR now.

**Pull request closed without merging**
