### PR TITLE
Add LDAP_VERIFY_SSL var

### PR DESCRIPTION
**Pull request by LordFPL**
Since https://about.gitlab.com/2017/09/22/gitlab-10-0-released/#ldap-config-%22verify_certificates%22-defaults-to-secure, this config should be accessible (https://github.com/sameersbn/docker-gitlab/issues/1366).

### CODE REVIEW

**Comment by osixia** [comment]
hello,
would be nice to add also : 
`ca_file` and `ssl_version` what do you think ?

**Comment by solidnerd** [comment]
Hey @LordFPL, 

thanks for your PR. I checked it. I would like to have a single commit because this is only a single feature for a clean history and an easy revert. As well I checked the upstream config and I think we should adjust them to it. You can add my following patch for that. It's only reordering the part of the config file.

```git
commit a3d01c11a105ec247c050fc078763f85d223d938
Author: solidnerd <niclas@mietz.io>
Date:   Wed Oct 4 17:57:56 2017 +0200

    Reorder the ldap config structure to the upstream

    Signed-off-by: solidnerd <niclas@mietz.io>

diff --git a/assets/runtime/config/gitlabhq/gitlab.yml b/assets/runtime/config/gitlabhq/gitlab.yml
index c440fa9..0ef2df8 100644
--- a/assets/runtime/config/gitlabhq/gitlab.yml
+++ b/assets/runtime/config/gitlabhq/gitlab.yml
@@ -261,14 +261,32 @@ production: &base
         # Example: 'Paris' or 'Acme, Ltd.'
         label: '{{LDAP_LABEL}}'

+        # Example: 'ldap.mydomain.com'
         host: '{{LDAP_HOST}}'
-        port: {{LDAP_PORT}}
-        uid: '{{LDAP_UID}}'
-        encryption: '{{LDAP_METHOD}}' # "tls" or "ssl" or "plain"
-        verify_certificates: '{{LDAP_VERIFY_SSL}}'
+        # This port is an example, it is sometimes different but it is always an integer and not a string
+        port: {{LDAP_PORT}} # usually 636 for SSL
+        uid: '{{LDAP_UID}}' # This should be the attribute, not the value that maps to uid.
+
+
+        # Examples: 'america\\momo' or 'CN=Gitlab Git,CN=Users,DC=mydomain,DC=com'
         bind_dn: '{{LDAP_BIND_DN}}'
         password: '{{LDAP_PASS}}'

+        # Encryption method. The "method" key is deprecated in favor of
+        # "encryption".
+        #
+        #   Examples: "start_tls" or "simple_tls" or "plain"
+        #
+        #   Deprecated values: "tls" was replaced with "start_tls" and "ssl" was
+        #   replaced with "simple_tls".
+        #
+        encryption: '{{LDAP_METHOD}}'
+
+        # Enables SSL certificate verification if encryption method is
+        # "start_tls" or "simple_tls". (Defaults to false for backward-
+        # compatibility)
+        verify_certificates: '{{LDAP_VERIFY_SSL}}'
+
         # Set a timeout, in seconds, for LDAP queries. This helps avoid blocking
         # a request if the LDAP server becomes unresponsive.
         # A value of 0 means there is no timeout.
```

@osixia  Feel free to make an PR for that . I would be in the next release `10.0.2-1`

**Comment by pschmitt** [comment]
Why don't just you just squash the commits on merge?

**Comment by LordFPL** [comment]
I will try to look at this... but i'm at work... and not very friend with git. My PR was done with github website only.
If you want to do anything else with my commit, or do another with other methods, i will be totaly ok ;)

**Comment by vipseixas** [comment]
Hi, just upgraded to 10.0.3 and this fix has a problem, the config is not working with the single quotes, instead of `verify_certificates: '{{LDAP_VERIFY_SSL}}'` it should be `verify_certificates: {{LDAP_VERIFY_SSL}}`

I had to remove the quotes manually to make it work.

**Comment by pschmitt** [comment]
Can confirm what @vipseixas reported. `'false' != false`

**Comment by jostyee** [comment]
@vipseixas submit a PR to fix this issue would be welcomed.

**Comment by solidnerd** [comment]
@vipseixas  Please make an issue for that and a PR is wecolmed .

**Comment by LordFPL** [comment]
My fault sorry, PR is done https://github.com/sameersbn/docker-gitlab/pull/1380

**Pull request merged**
