### PR TITLE
Refactor Repository (Massive update incl Documentation website)

### LINKED ISSUE #1569: Suggestion: Add pre/post-config hook support to entrypoint.sh
Having to deal with a rather unorthodox LDAP setup beyond my control, I found myself in a situation where I needed to modify the LDAP `username` and LDAP `name` in `gitlab.yml` in order to show intelligible information to the user.  I made and tested my changes in a running container and restarted gitlab *inside* the running container.  That works fine.  Restarting the container does not because the entrypoint resets any runtime changes.  That's a Good Thing, but mighty inconvenient for me.

I could write a Dockerfile that starts `FROM` this image and make the necessary changes in there.  That should work, but only for me.  I could also clone this project, write a patch adding `LDAP_USERNAME` and `LDAP_NAME` environment variables to the already lengthy list and submit a merge request so everyone can benefit.  While waiting for the MR to be accepted, I build my own images.  Big fun, that :sleeping:.

However, the logical conclusion for the environment variable approach is having one environment variable for every single setting in every single configuration file.  And corresponding documentation that duplicates most of what GitLab already documents.  I'm not sure that that is a workable approach in the long run.

So what I did for a short term solution is bind mount a slightly modified `entrypoint.sh` onto `/sbin/entrypoint.sh`.  The change I made is just a single `sed` command that modifies `${GITLAB_CONFIG}`.  It is executed after `configure_nginx`.  No need to build my own image anymore, no need to clone, create a patch and MR and wait for it to get accepted :smile:.

That made me wonder whether it would be a good idea to support `run-parts`-style directories so that users can add their own tweaks by means of little scripts that run as the last step before the second `case` statement in `entrypoint.sh` and, if deemed useful, before `initialize_system`.  The scripts would live in `entrypoint.post.d/` and `entrypoint.pre.d/` directories and processed by `run-parts`.

Does that make sense?

\# BTW, I keep the `docker-compose.yml`, documentation and all other run-time snippets of my GItLab instance(s) under version control with `git` so the whole setup is "reproducible".

### LINKED ISSUE #1636: Large LFS Transfers Fail
Hello,
It would appear that large LFS transfers are failing with "i/o error". According to ( https://gitlab.com/gitlab-org/gitlab-ce/issues/31871#note_29480359 ) this appears to be solved by modifying the nginx site config to include:
> proxy_request_buffering off;

### LINKED ISSUE #1793: Gitlab Pages is too old / Gitlab Pages Access requires additional arguments
For the Gitlab Pages access control, gitlab pages `v1.3.0` is required, current gitlab pages is too old.

### LINKED ISSUE #1797: Versions in Dockerfile don't match gitlab-ce repository
Correct should be for current 11.5.1 release as per https://gitlab.com/gitlab-org/gitlab-ce/tree/v11.5.1

    GITLAB_SHELL_VERSION="8.4.1" \
    GITLAB_WORKHORSE_VERSION="7.1.3" \
    GITLAB_PAGES_VERSION="1.3.1" \
    GITALY_SERVER_VERSION="0.129.0"

### LINKED ISSUE #1816: Update to Gitlab Version 11.5.4
Are you have any plan to upgrade from 11.5.3 to 11.5.4 ?

Because it's Critical Security Patch

See more https://about.gitlab.com/2018/12/13/critical-security-release-gitlab-11-dot-5-dot-4-released/

### PR DESCRIPTION
**Pull request by GJRTimmer**
@solidnerd @sameersbn Massive update of repository.

Cannot be auto merged, requires replacement of master branch.

Main features are:
* documentation is now website auto generation with `Hugo`.
  * Documentation is still in Markdown so that contributions are very easy.
  * See https://docker.timmertech.nl/gitlab/ for the documentation end result.
  * Final todo is to add the deployment of the documentation website to circleci.
* Entire repository configuration with a global `config.yml` which means that if you update the container to a new version of gitlab all the version numbers of the documentation will change with it too.
* Documentation uses a `config.template` file more variables can be added to make the documentation even more automatic. When you run `make docs` it will generate the `config.yml` for the documentation and generate it in `docs/public` see the .gitlab-ci.yml `pages` job. We still need to add a job / script to circleci which will publish the documentation to the gh-pages branch. This is possible found some examples on github on how to do this.
* After you replaced the master branch with this refactoring you will have to update the `config.yml` to reflect the config of the `sameersnm/docker-gitlab` repository.
* Also note that while it looks like contrib files are missing they are actually moved to their respective documentation page as attachment see the following links as examples
  * https://docker.timmertech.nl/gitlab/configuration/examples/
  * https://docker.timmertech.nl/gitlab/guides/kubernetes/
* After circleci job for deployment to branch gh-pages has been added the README.md must be updated to use this repo gh-pages instead of mine.
* Circle CI will now also push to Dockerhub, value of repository image in `config.yml` (Global) and Circle-CI config has to be changed. Also two variables has to be added to Circle-CI build environment
  * DOCKERHUB_USERNAME
  * DOCKERHUB_PASSWORD
* Upgrade Gitlab: 11.5.4 [Tagged]
* Upgrade Gitlab: 11.5.5 [Tagged]
* Upgrade Gitlab: 11.6.0 [Current]
* Upgrade Gitlab Components

# Repository Refactor

- Update build to multi-stage docker build
  - Layer compression due to multistage build
  - TODO: Strip Gitlab of unnecessary files
  - TODO: When COPY --chown option supports env / arg variables, update Dockerfile
- Updated build to use a base image
  - Allow nightly scheduled base image to speed up builds
  - Allow nightly scheduled builder image to speed up build
- Allow user to override base image for faster builds
- Allow user to override builder image for faster builds
- Implemented global configuration (config.yml)
- Implemented new setup for quickstart/testing of image
- Repository refactoring
- Rewrite documentation for Pages (Github & Gitlab)
  - Automatic documentation generation with [Hugo](https://gohugo.io/)
  - Documentation uses the global configuration (config.yml)
- Update format of CHANGELOG for pages generation
- Upgrade Gitlab: 11.6
- Upgrade Components
  - Workhorse: 8.0.0
  - Gitaly: 1.12.0
  - Shell: 8.4.4
- Renamed Changelog.md -> CHANGELOG.md for Gitlab compliancy
- Moved `exec_as_git` from function to script
- Moved `exec_as_git` => /sbin because of symlinks / layer compression
- Formatted exec_as_git to 2 spaces ident
- CI
  - Gitlab-CI
    - Update Gitlab-CI to build Pages
    - Update Gitlab-CI to allow user arguments
  - Circle-CI
    - TODO: Update Circle-CI to build Pages and deploy to github pages
    - Switched to `docker_layer_caching: true` instead of manually saving layers
    - Update image name
    - Added support for build `tag`
    - Add deploy to DockerHub
      - Add CI-ENV: DOCKERHUB_USERNAME
      - Add CI-ENV: DOCKERHUB_PASSWORD
    - Deploy to Dockerhub is now optional based on presence of DOCKERHUB_* variables
    - Only deploy master and tags to DockerHub
- Add CRON=1 to backup cron command
- Do not send documentation to docker daemon
- Update build scripts suppress
  - Add variable `DEBUG`
  - Suppress DEBUG logging by default
  - Allow override of DEBUG variable from command line `DEBUG=true make docker`
  - Suppress GIT Detached HEAD advice
  - Add forced docker fail on failed command
    - Added `|| exit 1` to non build commands
- Fix `Makefile` target `logs`
- Issues / Merge Requests
  - Fixes #690  (Explain [Options])
  - Fixes #699  (LDAP Attributes)
  - Fixes #737  (Add guide on how to use docker host ssh daemon)
  - Fixes #738  (Implemented Labels from org.label-schema)
  - Fixes #1468 (Auto build script)
  - Fixes #1472 (Backup restore documentation)
  - Fixes #1477 (Add support for building enterprise edition)
  - Fixes #1569 (Implemented pre / post config hook)
  - Fixes #1636 (LFS Uploads)
  - Fixes #1637 (LFS Uploads)
  - Fixes #1695 (Update documentation)
  - Fixes #1746 (LDAP Attributes)
  - Fixes #1768 (Container Timezone)
  - Fixes #1791 (Gitlab Pages Custom Domain Setup)
  - Fixes #1792 (Backup Subdirectory)
  - Fixes #1793 (Gitlab Pages Access Control)
  - Fixes #1794 (Gitlab Pages Access Control)
  - Fixes #1797 (Versions in Dockerfile don't match gitlab-ce repository)
  - Fixes #1814 (LDAP Attributes)
  - Fixes #1816 (Update to Gitlab Version 11.5.4)

### CODE REVIEW

**Comment by GJRTimmer** [comment]
@solidnerd @sameersbn 
* Prefer not to squash the commit for these will close several open issues and PR's.
* Documentation still requires some work of course but I think this is a good start one of the todo's is to replace all the links for references.

**Comment by CrystalMethod** [comment]
awesome work

**Comment by GJRTimmer** [comment]
@CrystalMethod 
> awesome work

Have you seen the documentation ? Currently there is still quite some work to be done, like fixing all the references. I'm hoping to make that community work. What is your impression about the new documentation ? Is it in the right direction ?

**Comment by luv2code** [comment]
> What is your impression about the new documentation ? Is it in the right direction ?

I like the it, and I think having an organised document site is a great idea. There is only one thing that I would change. When you click on a top level topic, I would expect it to bring up a page with all the content for the topic on it. Then in the navigation, clicking on a 2nd level topic would take you to anchors within the top level content.  That way I can scan the whole top level topic without having to click very much; but if I know the subtopic I'm looking for, I can still quickly jump to it.

Thank you.

**Comment by CrystalMethod** [comment]
Yes, I have looked at the docs briefly and I like them too. But what delights me the most is that your PR includes some very old PRs that I've missed for a long time.  (mainly LDAP) So I can only hope that this PR will pass through and serve as a "new basis" for the project. We have been using this container for quite some time and are very happy with it.

**Comment by GJRTimmer** [comment]
@luv2code Would be a great addition, currently don't know if it is possible maybe just as simple as adding it to the _index.md files.

To give you a quick summary how it works.
* Its built with [Hugo](https://gohugo.io/)
* Theme [DocDock](https://themes.gohugo.io/docdock/)
* [Theme Demo with all its functionality](https://themes.gohugo.io/theme/docdock/)
* All the documentation content is in `docs/content`

Check out the demo of the theme to see what an insane amount of features it has.

**Comment by GJRTimmer** [comment]
@CrystalMethod I've updated the Circle-CI config of this new repository, and is it able to push the latest and tags to DockerHub. Also this PR now includes update of subcomponents and upgrade of Gitlab-CI to `11.5.4`. It is available on my DockerHub account. So if you cannot wait until this PR is merged and want to play with the new image check here on [DockerHub](https://hub.docker.com/r/datacore/gitlab)

Have fun playing.

P.S.
I've you decide to upgrade, as always make full backup of your data, so you can roll back.

*Note: This repository  update also fixes the local testing. So if you clone my fork you only have to give `make all` and afterwards `make test` it will spin up a full testing environment.
docker-compose located in `docker/quickstart.yml` exposes localhost port `10080`.

Have fun playing

**Comment by solidnerd** [comment]
# 

Hey @GJRTimmer,

thank you for your Pull Request. I seems that there is a lot of work in it. But it has also a lot of breaking changes for this repository. Also there are some new features that at the moment out of scope. To clarify we should start a roadmap for the project and future changes. (This will come from my side)

First of all I’ll say that I won’t replace the current master with your master branch, because of the breaking changes and that I can’t guarantee anyone from my side that this will work backwards and with no migration steps. (This is the current state of the Pull Request) .

Now let’s dive inside your Components:

> Upgrade Components
> Workhorse: 8.0.0
> Gitaly: 1.12.0
> Shell: 8.4.4

These versions are the latest from master and for the release. This could have breaking changes and breaks the whole releases or unintended side effects.

> Implemented global configuration (config.yml) 

I’m not a really fan of an global configuration. This requires also a parser and structure for the configuration. I know you implemented it in bash but I won’t increase the readability. I think it increases only complexity, because not everyone has the use case to build difference gitlab images. 


I think we should cover some features here in the upstream but for this I need sometime to think about it how we can handle this in a good manner with a stable process without breaking changes until `12.X`  . 
For this we need smaller commits and probably more pull requests to implement them separately. 

Regarding the merged issues:

- Fixes #699 (LDAP Attributes)
	- For this routine we need some tests of how to integrate LDAP and see that it’s working.
- Features: GitLab Pages &&  GitLab Pages  Access Control
	- This should be included in the next release. I need only to verify that it works
- LFS Uploads
	-  This should be included in the next release. I need only to verify that it works


I hope you can understand my concerns regarding this pull request.  
It’s okay for me that you have your own fork with different changes.

**Comment by solidnerd** [comment]
I'll close this issue cause we can't integrate it directly and we have different directions. But I'm open for discussion so let's move this to an issue.

**Pull request closed without merging**
