### PR TITLE
upgrade Gitlab CE to 13.12.1

### PR DESCRIPTION
**Pull request by sachilles**
GitLab 13.12.1 released (see <https://about.gitlab.com/releases/2021/05/25/gitlab-13-12-1-released/>)

### CODE REVIEW

**Comment by sameersbn** [comment]
lgtm

**Comment by sameersbn** [comment]
@sachilles thank you for your efforts in keeping this repo up-to-date and inline with the upstream. with your permission i would like to invite you to be a maintainer for the repo. Is this acceptable to you?

**Comment by sachilles** [comment]
@sameersbn Wow, I feel this is a very great honor. 

But before I blindly say yes, I have a few questions. 

Could you tell me what tasks and also what amount of time I should reserve as a maintainer? Are there meetings to talk about the pull requests and the strategic direction of the repo? Are there guidelines for the repo maintenance?

If you want, we can discuss these points by e-mail. (Nevertheless I am very excited. At least this is the first request of this kind... ;D )

Translated with www.DeepL.com/Translator (free version)

**Comment by sameersbn** [comment]
Hello @sachilles ,

> Could you tell me what tasks 

You have already been doing  a great job contributing to the repo. The maintainer privileges will enable you to accept/merge pull request and most importantly allow you to release software quicker.

> what amount of time I should reserve as a maintainer?

This is a volunteer effort and I do not expect any time commitments. Contribute when you have the time to help out and do it as long as it makes you happy. We're all here to scratch our own itch 😄 

> Are there meetings to talk about the pull requests and the strategic direction of the repo?

At the moment we don't have any meetings as such. It could be a good idea to have a monthly sync-up to discuss the important issues, improvement and such. I live in India, so we'd have to find an appropriate time for these meetings.

>  Are there guidelines for the repo maintenance?

There aren't any formal guidelines as such. The maintenance of this repo is quite chaotic. We can work on getting things in order and plan to improve all the things overall.

> If you want, we can discuss these points by e-mail.

Whatever works. You can find my email on my profile page

> I am very excited. At least this is the first request of this kind... 

I am excited to have you. I'm sending you the collaboration invitation.

**Pull request merged**
