### PR TITLE
Upgrade to 13.7.0

### PR DESCRIPTION
**Pull request by sachilles**
Update to gitlab 13.7.0 (see also https://about.gitlab.com/releases/2020/12/22/gitlab-13-7-released/ ).

### CODE REVIEW

**Comment by cwildfoerster** [comment]
LGTM. Tested and working. (relative url may not work, not testet)

**Comment by danyill** [comment]
Should this also require PostgreSQL 12?

In my self-hosted Gitlab, I see in the Admin area: 

image

According to the [epic](https://gitlab.com/groups/gitlab-org/-/epics/2374):

* In 13.7 default to PostgreSQL 12 for new installs of GitLab
* In 13.7 auto upgrade users to PG12 (this was previously scheduled for 13.6 but has been pushed out by one milestone to allow for additional testing)
* In 14.0 PG 12 becomes the minimum required version

I guess it would make sense but not be mandatory to move to PG12 in step with upstream here? Should there be migration instructions and automatic migration in the `docker-compose.yml` file?

Just a thought...

**Comment by sachilles** [comment]
Hi,

I don't use a PostgreSQL container but an "external" database in version 12.5. In  the image the binaries of PostgreSQL 12 are already used:

https://github.com/sameersbn/docker-gitlab/blob/67a68d75ed9f72f5acf0d52a5bbd095e1e7bc32c/Dockerfile#L48

Do I miss something?

**Comment by cwildfoerster** [comment]
upgraded the postgresql container from `sameersbn/postgresql:11-20200524` to `sameersbn/postgresql:12-20200524`. Working fine, remember to delete all but the **latest** version folder inside the postgresql data directory, otherwise postgresql may upgrade to wrong/old database, happened before here, can't find the issue right now. Maybe @sameersbn could also bump the version/tag to something newer than may.

**Comment by cwildfoerster** [comment]
@sachilles would you mind updating the docker-compose.yml to use postgresql 12?

**Comment by sachilles** [comment]
Hi,

yes of course (and well, now I got your point).

**Comment by sachilles** [comment]
Hi,

just finished the rebase session. Should I add the change to the file `changelog.md`.

**Comment by cwildfoerster** [comment]
Thank you @solidnerd

**Comment by solidnerd** [comment]
@sachilles  Thanks for your work. I really appreciate it 👍  💯  . 

I added only a fix for `GITLAB_RELATIVE_URL_ROOT`  working again. 

image


LGTM! And ready for shipment!

**Pull request merged**
