### PR TITLE
Upgrade GitLab CE to 11.9.4

### PR DESCRIPTION
**Pull request by greyferret**
[Changelog](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.0/CHANGELOG.md)
[GITALY_SERVER_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.0/GITALY_SERVER_VERSION) updated to 1.27.0.
[GITLAB_WORKHORSE_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.0/GITLAB_WORKHORSE_VERSION) not changed.
[GITLAB_SHELL_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.0/GITLAB_SHELL_VERSION) updated to 8.7.1. 
[GITLAB_PAGES_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.0/GITLAB_PAGES_VERSION) not changed.

upd. + update to 11.9.1
[Changelog](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.1/CHANGELOG.md)
[GITALY_SERVER_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.1/GITALY_SERVER_VERSION) updated to 1.27.1.
[GITLAB_WORKHORSE_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.1/GITLAB_WORKHORSE_VERSION) not changed.
[GITLAB_SHELL_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.1/GITLAB_SHELL_VERSION) not changed.
[GITLAB_PAGES_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.1/GITLAB_PAGES_VERSION) not changed.

upd.2 + update to 11.9.4, security release
[Changelog](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.4/CHANGELOG.md)
[GITALY_SERVER_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.4/GITALY_SERVER_VERSION) not changed.
[GITLAB_WORKHORSE_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.4/GITLAB_WORKHORSE_VERSION) updated to 8.3.3.
[GITLAB_SHELL_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.4/GITLAB_SHELL_VERSION) not changed.
[GITLAB_PAGES_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.9.4/GITLAB_PAGES_VERSION) not changed.

### CODE REVIEW

**Comment by greyferret** [comment]
ping @solidnerd :)

**Comment by paolomainardi** [comment]
any updated here ?

**Comment by mprochazka** [comment]
ping @sameersbn

**Comment by greyferret** [comment]
[GITLAB_WORKHORSE_VERSION refers to non-existent tag 8.3.3](https://gitlab.com/gitlab-org/gitlab-ce/issues/59813) :( I'll wait for fix.

**Comment by greyferret** [comment]
Guys from GitLab fixed missed tag 🙄5 days ago
https://gitlab.com/gitlab-org/gitlab-workhorse/tags/v8.3.3

**Comment by solidnerd** [comment]
Hey @greyferret ,

I'll close this PR because I cherry-picked your commits on master branch. So you real commits will be there. This was needed because we do for every release also a separate release. With your PR I needed to skip some off this. Don't worry. Thanks for your work I really appreciate it :+1:

**Pull request closed without merging**
