### PR TITLE
upgrade to CE v8.15.0

### PR DESCRIPTION
**Pull request by timfeirg**

### CODE REVIEW

**Comment by solidnerd** [comment]
Hey, 

thanks for this PR. But for a Minor Releases we need more to do.  What's is missing in your PR. 

- [ ] Update GitLab workhose version
- [ ] Update GitLab shell version
- [ ] Update all configurations that are under `assets/runtime/config`


In the Blog post i read about that they want to use Postgressql 9.6 so we need to update this image as well. Another point is to check if the base image can be updated.

**Comment by timfeirg** [comment]
Thanks for the quick response, gitlab-workhorse and gitlab-shell version updated.

I don't think I can decide if anything under `assets/runtime/config` needs changing, but I've read changelogs for both projects, from what I learned I guess the configs are probably good.

**Comment by solidnerd** [comment]
Please make separate commits for gitlab shell and gitlab workhorse

**Comment by reynold-lariza** [comment]
I'm just wondering, whenever I get a notifcation fo new release, and try to build it. the branch/tag does not exist (https://github.com/gitlabhq/gitlabhq/tags) until a sometime later? :/

**Comment by Ilya-Kuchaev** [comment]
@reynold-lariza Just try to use the proper repository
https://gitlab.com/gitlab-org/gitlab-ce/tags

**Comment by jostyee** [comment]
This PR should be updated with 8.15.1 https://about.gitlab.com/2016/12/23/gitlab-8-dot-15-dot-1-released/

**Comment by timfeirg** [comment]
I've extract gitlab-shell / gitlab-workhorse changes into separate commits @solidnerd 

Upgraded to gitlab CE v8.15.1 @jostyee

**Comment by solidnerd** [comment]
@timfeirg Let's please do one Step after the other. So let's focus to ship 8.15.0 . For the patch make an separate PR. I will have look for the configuruation updates later and send you a patch.

**Comment by timfeirg** [comment]
I've removed the gitlab CE v8.15.1 patch @solidnerd

**Comment by solidnerd** [comment]
Merry Christmas ! 

Here all configuration related changes for `8.15.0`. Could you apply these to your branch ?

```
From aa215412bd0988d3dbc4346aeedf52fb2dfd9ff3 Mon Sep 17 00:00:00 2001
From: solidnerd <niclas@mietz.io>
Date: Sat, 24 Dec 2016 21:45:36 +0100
Subject: [PATCH 1/4] Add GITLAB_MATTERMOST_ENABLED and GITLAB_MATTERMOST_URL

Signed-off-by: solidnerd <niclas@mietz.io>
---
 README.md                                 | 2 ++
 assets/runtime/config/gitlabhq/gitlab.yml | 6 ++++++
 assets/runtime/env-defaults               | 4 ++++
 assets/runtime/functions                  | 8 ++++++++
 4 files changed, 20 insertions(+)

diff --git a/README.md b/README.md
index 998ac11..f2b8311 100644
--- a/README.md
+++ b/README.md
@@ -833,6 +833,8 @@ Below is the complete list of available options that can be used to customize yo
 | `GITLAB_ARTIFACTS_DIR` | Directory to store the artifacts. Defaults to `$GITLAB_SHARED_DIR/artifacts` |
 | `GITLAB_LFS_ENABLED` | Enable/Disable Git LFS support. Defaults to `true`. |
 | `GITLAB_LFS_OBJECTS_DIR` | Directory to store the lfs-objects. Defaults to `$GITLAB_SHARED_DIR/lfs-objects` |
+| `GITLAB_MATTERMOST_ENABLED` | Enable/Disable GitLab Mattermost for *Add Mattermost button*. Defaults to `false`. |
+| `GITLAB_MATTERMOST_URL` | Sets Mattermost URL. Defaults to `https://mattermost.example.com`. |
 | `GITLAB_BACKUP_SCHEDULE` | Setup cron job to automatic backups. Possible values `disable`, `daily`, `weekly` or `monthly`. Disabled by default |
 | `GITLAB_BACKUP_EXPIRY` | Configure how long (in seconds) to keep backups before they are deleted. By default when automated backups are disabled backups are kept forever (0 seconds), else the backups expire in 7 days (604800 seconds). |
 | `GITLAB_BACKUP_PG_SCHEMA` | Specify the PostgreSQL schema for the backups. No defaults, which means that all schemas will be backed up. see #524 |
diff --git a/assets/runtime/config/gitlabhq/gitlab.yml b/assets/runtime/config/gitlabhq/gitlab.yml
index fd01ba9..e619c48 100644
--- a/assets/runtime/config/gitlabhq/gitlab.yml
+++ b/assets/runtime/config/gitlabhq/gitlab.yml
@@ -155,6 +155,12 @@ production: &base
     # The location where LFS objects are stored (default: shared/lfs-objects).
     storage_path: {{GITLAB_LFS_OBJECTS_DIR}}
 
+  ## Mattermost
+  ## For enabling Add to Mattermost button
+  mattermost:
+    enabled: {{GITLAB_MATTERMOST_ENABLED}}
+    host: '{{GITLAB_MATTERMOST_URL}}'
+
   ## Gravatar
   ## For Libravatar see: http://doc.gitlab.com/ce/customization/libravatar.html
   gravatar:
diff --git a/assets/runtime/env-defaults b/assets/runtime/env-defaults
index 9a877fc..d37939c 100644
--- a/assets/runtime/env-defaults
+++ b/assets/runtime/env-defaults
@@ -105,6 +105,10 @@ GITLAB_ARTIFACTS_DIR="${GITLAB_ARTIFACTS_DIR:-$GITLAB_SHARED_DIR/artifacts}"
 GITLAB_LFS_ENABLED=${GITLAB_LFS_ENABLED:-true}
 GITLAB_LFS_OBJECTS_DIR="${GITLAB_LFS_OBJECTS_DIR:-$GITLAB_SHARED_DIR/lfs-objects}"
 
+## Mattermose
+GITLAB_MATTERMOST_ENABLED=${GITLAB_MATTERMOST_ENABLED:-false}
+GITLAB_MATTERMOST_URL=${GITLAB_MATTERMOST_URL:-https://mattermost.example.com}
+
 GITLAB_SECRETS_DB_KEY_BASE=${GITLAB_SECRETS_DB_KEY_BASE:-}
 GITLAB_SECRETS_SECRET_KEY_BASE=${GITLAB_SECRETS_SECRET_KEY_BASE:-}
 GITLAB_SECRETS_OTP_KEY_BASE=${GITLAB_SECRETS_OTP_KEY_BASE:-}
diff --git a/assets/runtime/functions b/assets/runtime/functions
index 56be271..4b907c0 100644
--- a/assets/runtime/functions
+++ b/assets/runtime/functions
@@ -832,6 +832,13 @@ gitlab_configure_lfs() {
     GITLAB_LFS_OBJECTS_DIR
 }
 
+gitlab_configure_mattermost() {
+  echo "Configuring gitlab::mattermost..."
+  update_template ${GITLAB_CONFIG} \
+    GITLAB_MATTERMOST_ENABLED \
+    GITLAB_MATTERMOST_URL
+}
+
 gitlab_configure_project_features() {
   echo "Configuring gitlab::project_features..."
   update_template ${GITLAB_CONFIG} \
@@ -1242,6 +1249,7 @@ configure_gitlab() {
   gitlab_configure_ci
   gitlab_configure_artifacts
   gitlab_configure_lfs
+  gitlab_configure_mattermost
   gitlab_configure_project_features
   gitlab_configure_mail_delivery
   gitlab_configure_mailroom
-- 
2.11.0
```
```
From 0112605c070557825fcdfd335de1fdca314e1d0a Mon Sep 17 00:00:00 2001
From: solidnerd <niclas@mietz.io>
Date: Sat, 24 Dec 2016 22:03:02 +0100
Subject: [PATCH 2/4] Add OAUTH Authentiq support

Signed-off-by: solidnerd <niclas@mietz.io>
---
 README.md                                 |  4 ++++
 assets/runtime/config/gitlabhq/gitlab.yml |  4 ++++
 assets/runtime/env-defaults               |  6 ++++++
 assets/runtime/functions                  | 14 ++++++++++++++
 4 files changed, 28 insertions(+)

diff --git a/README.md b/README.md
index f2b8311..97ff3d9 100644
--- a/README.md
+++ b/README.md
@@ -940,6 +940,10 @@ Below is the complete list of available options that can be used to customize yo
 | `OAUTH_FACEBOOK_APP_SECRET` | Facebook App API secret. No defaults. |
 | `OAUTH_TWITTER_API_KEY` | Twitter App API key. No defaults. |
 | `OAUTH_TWITTER_APP_SECRET` | Twitter App API secret. No defaults. |
+| `OAUTH_AUTHENTIQ_CLIENT_ID` | authentiq Client ID. No defaults. |
+| `OAUTH_AUTHENTIQ_CLIENT_SECRET` | authentiq Client secret. No defaults. |
+| `OAUTH_AUTHENTIQ_SCOPE` | Scope of Authentiq Application Defaults to `'aq:name email~rs address aq:push'`|
+| `OAUTH_AUTHENTIQ_REDIRECT_URI` |  Callback URL for Authentiq. No defaults. |
 | `OAUTH_GITHUB_API_KEY` | GitHub App Client ID. No defaults. |
 | `OAUTH_GITHUB_APP_SECRET` | GitHub App Client secret. No defaults. |
 | `OAUTH_GITHUB_URL` | Url to the GitHub Enterprise server. Defaults to https://github.com |
diff --git a/assets/runtime/config/gitlabhq/gitlab.yml b/assets/runtime/config/gitlabhq/gitlab.yml
index e619c48..51643ca 100644
--- a/assets/runtime/config/gitlabhq/gitlab.yml
+++ b/assets/runtime/config/gitlabhq/gitlab.yml
@@ -371,6 +371,10 @@ production: &base
                   login_url: '{{OAUTH_CAS3_LOGIN_URL}}',
                   service_validate_url: '{{OAUTH_CAS3_VALIDATE_URL}}',
                   logout_url: '{{OAUTH_CAS3_LOGOUT_URL}}'} }
+       - { name: 'authentiq',
+          app_id: '{{OAUTH_AUTHENTIQ_CLIENT_ID}}',
+          app_secret: 'OAUTH_AUTHENTIQ_CLIENT_SECRET',
+          args: { scope: {{OAUTH_AUTHENTIQ_SCOPE}}, redirect_uri: '{{OAUTH_AUTHENTIQ_REDIRECT_URI}}' } }
       - { name: 'github',
           label: 'GitHub',
           app_id: '{{OAUTH_GITHUB_API_KEY}}',
diff --git a/assets/runtime/env-defaults b/assets/runtime/env-defaults
index d37939c..92674d2 100644
--- a/assets/runtime/env-defaults
+++ b/assets/runtime/env-defaults
@@ -266,6 +266,12 @@ OAUTH_FACEBOOK_APP_SECRET=${OAUTH_FACEBOOK_APP_SECRET:-}
 OAUTH_TWITTER_API_KEY=${OAUTH_TWITTER_API_KEY:-}
 OAUTH_TWITTER_APP_SECRET=${OAUTH_TWITTER_APP_SECRET:-}
 
+## Authentiq
+OAUTH_AUTHENTIQ_CLIENT_ID=${OAUTH_AUTHENTIQ_CLIENT_ID:-}
+OAUTH_AUTHENTIQ_CLIENT_SECRET=${OAUTH_AUTHENTIQ_CLIENT_SECRET:-}
+OAUTH_AUTHENTIQ_SCOPE=${OAUTH_AUTHENTIQ_SCOPE:-'aq:name email~rs address aq:push'}
+OAUTH_AUTHENTIQ_REDIRECT_URI=${OAUTH_AUTHENTIQ_REDIRECT_URI:-}
+
 ### GITHUB
 OAUTH_GITHUB_API_KEY=${OAUTH_GITHUB_API_KEY:-}
 OAUTH_GITHUB_APP_SECRET=${OAUTH_GITHUB_APP_SECRET:-}
diff --git a/assets/runtime/functions b/assets/runtime/functions
index 4b907c0..478ac0f 100644
--- a/assets/runtime/functions
+++ b/assets/runtime/functions
@@ -489,6 +489,20 @@ gitlab_configure_oauth_twitter() {
   fi
 }
 
+gitlab_configure_oauth_authentiq() {
+  if [[ -n ${OAUTH_AUTHENTIQ_CLIENT_ID} && -n ${OAUTH_AUTHENTIQ_CLIENT_SECRET} ]]; then
+    echo "Configuring gitlab::oauth::authentiq..."
+    OAUTH_ENABLED=${OAUTH_ENABLED:-true}
+    update_template ${GITLAB_CONFIG} \
+      OAUTH_AUTHENTIQ_CLIENT_ID \
+      OAUTH_AUTHENTIQ_CLIENT_SECRET \
+      OAUTH_AUTHENTIQ_SCOPE \
+      OAUTH_AUTHENTIQ_REDIRECT_URI 
+  else
+    exec_as_git sed -i "/name: 'authentiq'/,/{{OAUTH_AUTHENTIQ_SCOPE}}/d" ${GITLAB_CONFIG}
+  fi
+}
+
 gitlab_configure_oauth_github() {
   if [[ -n ${OAUTH_GITHUB_API_KEY} && -n ${OAUTH_GITHUB_APP_SECRET} ]]; then
     echo "Configuring gitlab::oauth::github..."
-- 
2.11.0
```
```
From c1fd9d3bdd36105d94648b7fb8c10cf56b413344 Mon Sep 17 00:00:00 2001
From: solidnerd <niclas@mietz.io>
Date: Sun, 25 Dec 2016 11:19:12 +0100
Subject: [PATCH 3/4] Fix Typos and Grammar

---
 assets/runtime/config/gitlabhq/unicorn.rb | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/assets/runtime/config/gitlabhq/unicorn.rb b/assets/runtime/config/gitlabhq/unicorn.rb
index 54d05d8..62f650c 100644
--- a/assets/runtime/config/gitlabhq/unicorn.rb
+++ b/assets/runtime/config/gitlabhq/unicorn.rb
@@ -44,7 +44,7 @@ listen "127.0.0.1:8080", :tcp_nopush => true
 # nuke workers after 30 seconds instead of 60 seconds (the default)
 #
 # NOTICE: git push over http depends on this value.
-# If you want be able to push huge amount of data to git repository over http
+# If you want to be able to push huge amount of data to git repository over http
 # you will have to increase this value too.
 #
 # Example of output if you try to push 1GB repo to GitLab over http.
-- 
2.11.0
```
```
From 42380f7072501edc27b741a213a8e1f42c2750d1 Mon Sep 17 00:00:00 2001
From: solidnerd <niclas@mietz.io>
Date: Sun, 25 Dec 2016 11:20:53 +0100
Subject: [PATCH 4/4] Update NGINX configuration files to add websocket support

---
 assets/runtime/config/nginx/gitlab     | 7 +++++++
 assets/runtime/config/nginx/gitlab-ssl | 8 ++++++++
 2 files changed, 15 insertions(+)

diff --git a/assets/runtime/config/nginx/gitlab b/assets/runtime/config/nginx/gitlab
index 6cba103..701437f 100644
--- a/assets/runtime/config/nginx/gitlab
+++ b/assets/runtime/config/nginx/gitlab
@@ -20,6 +20,11 @@ upstream gitlab-workhorse {
   server localhost:8181 fail_timeout=0;
 }
 
+map $http_upgrade $connection_upgrade_gitlab {
+    default upgrade;
+    ''      close;
+}
+
 ## Normal HTTP host
 server {
   ## Either remove "default_server" from the listen line below,
@@ -56,6 +61,8 @@ server {
     proxy_set_header    X-Real-IP           $remote_addr;
     proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
     proxy_set_header    X-Forwarded-Proto   {{NGINX_X_FORWARDED_PROTO}};
+    proxy_set_header    Upgrade             $http_upgrade;
+    proxy_set_header    Connection          $connection_upgrade_gitlab;
 
     proxy_pass http://gitlab-workhorse;
   }
diff --git a/assets/runtime/config/nginx/gitlab-ssl b/assets/runtime/config/nginx/gitlab-ssl
index 22ba6bb..786eda1 100644
--- a/assets/runtime/config/nginx/gitlab-ssl
+++ b/assets/runtime/config/nginx/gitlab-ssl
@@ -24,6 +24,11 @@ upstream gitlab-workhorse {
   server localhost:8181 fail_timeout=0;
 }
 
+map $http_upgrade $connection_upgrade_gitlab {
+    default upgrade;
+    ''      close;
+}
+
 ## Redirects all HTTP traffic to the HTTPS host
 server {
   ## Either remove "default_server" from the listen line below,
@@ -103,6 +108,9 @@ server {
     proxy_set_header    X-Forwarded-Ssl     on;
     proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
     proxy_set_header    X-Forwarded-Proto   {{NGINX_X_FORWARDED_PROTO}};
+    proxy_set_header    Upgrade             $http_upgrade;
+    proxy_set_header    Connection          $connection_upgrade_gitlab_ssl;
+    
     proxy_pass http://gitlab-workhorse;
   }
 
-- 
2.11.0
```

**Comment by timfeirg** [comment]
I've added your patch as a separate commit, should I `git commit --amend` them instead? @solidnerd

**Comment by timfeirg** [comment]
I've added your patch as a separate commit, should I `git commit --amend` them instead? @solidnerd

**Comment by mrslain** [comment]
@timfeirg @solidnerd I think you have forgotten.
```
diff --git a/assets/runtime/functions b/assets/runtime/functions
index a05d645..aee1d13 100644
--- a/assets/runtime/functions
+++ b/assets/runtime/functions
@@ -637,6 +637,7 @@ gitlab_configure_oauth() {
   gitlab_configure_oauth_google
   gitlab_configure_oauth_facebook
   gitlab_configure_oauth_twitter
+  gitlab_configure_oauth_authentiq
   gitlab_configure_oauth_github
   gitlab_configure_oauth_gitlab
   gitlab_configure_oauth_bitbucket
```

**Comment by timfeirg** [comment]
I've applied your patches as one separate commits, should I amend them into the commit titled *upgrade to CE v8.15.0*? @solidnerd 
I'm not familiar with this process, I feel like you could just edit my PR or pull my branch and push all the necessary commits yourself, it's actually less work, faster.

**Comment by solidnerd** [comment]
> I've added your patch as a separate commit, should I git commit --amend them instead? @solidnerd

You can use `git am` to apply all patches .  So for the proccess copy every block in a file that is called `xxx.patch`and then you can use `git am ` to apply those. It's quite easy with `git am *.patch`

**Comment by solidnerd** [comment]
@mrslain You are right 😄  .

**Comment by timfeirg** [comment]
done, including the last patch @mrslain suggested.
this PR has been very educating, thanks @solidnerd

**Comment by solidnerd** [comment]
@timfeirg You are welcome ! That's the way it should be 👍  . I will start with testing later and will prepare the last things for a release.

**Comment by solidnerd** [comment]
LGTM ! for everything so I released it.

**Comment by paolomainardi** [comment]
I know that this MR has been closed, but you wrote `In the blog post i read about that they want to use Postgressql 9.6 so we need to update this image as well. Another point is to check if the base image can be updated.` but i cannot find any reference about that, can you clarify if the pgsql is needed ?

**Comment by solidnerd** [comment]
At the moment it's not needed to upgrade postgresql. On the first I misinterpretted the message of blog post. But what's actually says is that the update there omnibus postgresql from `9.2.8` to `9.6.1` and you have now the abillity to do an `pg-upgrade` easily. This is not needed for the image because the image from sameersbn checks the version and do a `pg-upgrade` when a newer version will be used. I run currently `8.15.1` with postgresql 9.5.4 and everything wokrs for me as excepted. Update the base image happens through eafe2bd7e65e3e3ed90b007703bda0d8933cfeaf .

But I prepared a PR for that in the [related repository](https://github.com/sameersbn/docker-postgresql/pull/88) .

**Comment by paolomainardi** [comment]
Thanks a lot @solidnerd, everything is clear now 👍

**Pull request merged**
