### PR TITLE
Upgrading to Workhorse 1.0.1 - Fixes missing version tag

### PR DESCRIPTION
**Pull request by phenomax**
As explained by GitLab [here](https://gitlab.com/gitlab-org/gitlab-ce/commit/5981a0f365b9a312b87bfcebfb0d9365cb2f9c9a) the upgrade to v1.0.1 fixes the missing version tag for workhorse @reynold-lariza has already discovered when testing GitLab v8.14.0 in [this](https://github.com/sameersbn/docker-gitlab/pull/979) pull request

### CODE REVIEW

**Comment by sash** [comment]
+1 - missing version tag is annoying!

**Comment by phenomax** [comment]
Unfortunately, we have to wait until GitLab releases the new workhorse version.
[Currently](https://gitlab.com/gitlab-org/gitlab-workhorse/blob/master/VERSION) we're still on v1.0.0 and the [upgrade to v1.0.1](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/changelogs/unreleased/workhorse-v1-0-1.yml) is still pending.
So, referring to #985 we cant do anything than waiting

**Comment by phenomax** [comment]
Today workhorse has been upgraded to [v1.1.0](https://gitlab.com/gitlab-org/gitlab-workhorse/blob/master/CHANGELOG). Lets look forward, if this fixes our problem

**Comment by solidnerd** [comment]
For me it's not a real problem to see the workhorse version in the admin panel with `1.0.1` it's isn't. I won't update to `1.1.0` until it's on the `8-14-stable` branch. The hole issue should be resolved in the upstream. Sorry for that. But If you wan't to test it with `1.1.0` than make your fork and try it.

**Comment by Ilya-Kuchaev** [comment]
I still do not see the Workhorse's version.

**Pull request closed without merging**
