### PR TITLE
[WIP] Upgrade GitLab CE to 10.5.0

### PR DESCRIPTION
**Pull request by ppcat**

### CODE REVIEW

**Comment by perryprog** [comment]
[10.5.1](https://about.gitlab.com/2018/02/22/gitlab-10-5-1-released/) was released as well due to some weirdness, might as well update to that as well.

**Comment by ppcat** [comment]
https://github.com/sameersbn/docker-gitlab/pull/1521 Here comes 10.5.1.

**Comment by boeserwolf91** [comment]
It might be that you have to update the configuration gitlab.rb, evironments etc. as well because there's a new lets encrypt option: see https://about.gitlab.com/2018/02/22/gitlab-10-5-released/#instant-ssl-with-lets-encrypt-for-gitlab

**Comment by solidnerd** [comment]
Hey @ppcat ,

I'm back from busy week. Could you fix your merge conflicts to that we could take this as a next release. It will be neat that your changes are based on #1516. So that we could make direct update from 10.4.4 to 10.5.0 . If you need help with this let me know.

**Comment by ppcat** [comment]
Hi @solidnerd, I’m studying the source code, but not sure when can I figure out how to hook the new config path into environment variable. Maybe someone can open new PR for this version upgrade. Thanks!

**Comment by solidnerd** [comment]
@ppcat I did a new PR for you. I gonna close this in favor of #1524 .

**Comment by ppcat** [comment]
@solidnerd Thank you.

**Pull request closed without merging**
