### PR TITLE
Upgrade to GitLab 9.0.2

### PR DESCRIPTION
**Pull request by jostyee**
- Upgrade to GitLab CE 9.0.2
- Upgrade to GitLab Workhorse 1.4.2
- Upgrade to GitLab Shell 5.0.2

### CODE REVIEW

**Comment by paolomainardi** [comment]
LGTM 👍

**Comment by gravis** [comment]
"This version contains two important security fixes for the newly released nested groups feature of GitLab 9.0, and we recommend that all affected GitLab installations be upgraded as soon as possible." 

Could you merge this asap please?

Thanks

**Comment by paolomainardi** [comment]
ping @solidnerd @sameersbn

**Comment by f3l1x** [comment]
Thank you guys for your work. :-)

**Comment by lnxmad** [comment]
Let's do this.

**Comment by gravis** [comment]
It would be nice if we could have major versions as tags as well (ie: like official images having `9.0.2` tagged as `9` too). Thanks :)

**Comment by paolomainardi** [comment]
Ehy please merge this one guys.

**Comment by solidnerd** [comment]
I didn't bump the GitLab Shell to 5.0.2, because this not available on the stable branch in the upstream. 9.0.1 and 9.0.2 is shipped.  Next time make please single commits for bumping shell or other version in a separate commit. I will close this PR now because it's on the master branch.

**Pull request closed without merging**
