### PR TITLE
Update to V15.0.2

### PR DESCRIPTION
**Pull request by antt1995**
Update to V15.0.2

### CODE REVIEW

**Comment by sachilles** [comment]
Just as an hint. This PR is incomplete. A PR to complete this PR is provided to the branch of the contributor. As soon as the additional changes are merged to the branch `patch-1`of the original contributor, this PR can be checked for correctness and will be merged.

@antt1995 Please accept the provided changes. Thanks in advance.

**Comment by antt1995** [comment]
@sachilles Thanks I'll keep that all in mind next time I try and contribute 

All Merged

**Review by sachilles — APPROVED** [review]
LGTM

**Comment by sachilles** [comment]
@antt1995 You're welcome and thanks for your contribution.

**Pull request merged**
