### PR TITLE
Add configuration parameters to control Feature flag

### PR DESCRIPTION
**Pull request by kkimurak**
At now, we can enable / disable feature flags via rails console (`docker exec -u git -it gitlab bundle exec rails console -e production`) or Feature flags API (which requires API access token).  

There were some request to provide configuration parameter to control them (for example: #2832, #2682, #2083 and #1930 - some issues are already closed, though). This PR introduces following configuration parameter to achieve that:

- `GITLAB_FEATURE_FLAGS_DISABLE_TARGETS`
- `GITLAB_FEATURE_FLAGS_ENABLE_TARGETS`

The value should be an comma-separated list of target feature flag name like `auto_devops_banner_disabled,ci_enable_live_trace`.

Since this process must be done in the rails production environment, this PR adds a ruby script to achieve this setup. If one or more targets are specified, the setting script will be executed by rails runner.

Since the DB must be initialized (with the correct schema) and ready to go in order to set the Feature flags, this PR adds a process to the entrypoint.sh to set the status of them after the DB migration.

### CODE REVIEW

**Comment by kkimurak** [comment]
Force-pushed following changes:

- Fixed changes to README.md :`GITLAB_FEATURE_FLAGS_DISABLE_TARGETS` was described that to be enabled by mistake
- Minor update on progress message

I would be happy to receive feedback on the verbosity of message. The current planned changes will result in messages appearing in the container logs like below.

With no target specified:

````
Configuring gitlab::feature_flags...
- No targets specified. skipping...
````

With `GITLAB_FEATURE_FLAGS_DISABLE_TARGETS=auto_devops_banner_disabled,invalid_flag_name` and `GITLAB_FEATURE_FLAGS_ENABLE_TARGETS=git_push_create_all_pipelines,another_invalid_flag_name`:

````
Configuring gitlab::feature_flags...
- Launching rails runner to set feature flags. This will take some time....
- specified feature flags: {:to_be_disabled=>["auto_devops_banner_disabled", "invalid_flag_name"], :to_be_enabled=>["git_push_create_all_pipelines", "another_invalid_flag_name"]}
- Following flags are probably invalid and have been ignored: invalid_flag_name,another_invalid_flag_name
- auto_devops_banner_disabled : off
- git_push_create_all_pipelines : on
````

**Comment by sachilles** [comment]
@kkimurak In my modest opinion, this PR is a very nice PR. Regarding your question about the feedback on the log entries: I am afraid that the output (via the line `specified feature flags`) will become very confusing if several features are to be activated or deactivated.

Wouldn't a list output for the features specified by the user be more helpful? For example in the form

```
Configuring gitlab::feature_flags...
- Launching rails runner to set feature flags. This will take some time....
- Specified feature flags  to be disabled: 
--- "auto_devops_banner_disabled"
--- "invalid_flag_name"
- Specified feature flags  to be enabled
--- "git_push_create_all_pipelines"
--- "another_invalid_flag_name"
- Following flags are probably invalid and have been ignored
--- invalid_flag_name
--- another_invalid_flag_name
- Apply user defined feature flags:
--- auto_devops_banner_disabled : off
--- git_push_create_all_pipelines : on
```

I am not sure whether indentations in the form of three hyphens are more legible than blanks.

**Comment by kkimurak** [comment]
@sachilles Indeed, it was redundant, difficult to read, and confusing to display all the specified options on a single line.  
Updated as suggested.

**Comment by kkimurak** [comment]
Rebased onto 16.10.0

**Pull request merged**
