### PR TITLE
Upgrade to Gitlab CE 13.5.2

### PR DESCRIPTION
**Pull request by bjf893**
https://about.gitlab.com/releases/2020/11/02/security-release-gitlab-13-5-2-released/

### CODE REVIEW

**Comment by bjf893** [comment]
@solidnerd 13.5.2 is a security release. Would be great if you could merge this.

**Comment by cwildfoerster** [comment]
Tested and working. LGTM

**Comment by omueller** [comment]
Thanks a lot for your work !   Maybe @solidnerd / @sameersbn could give @bjf893 (and/or other devs) direct write access to the project, as last commit was nearly a month ago ?

**Comment by cwildfoerster** [comment]
Yes, i second this thought. The last months were kind of really slow...

**Pull request merged**
