### PR TITLE
Upgrade to 12.0.3

### PR DESCRIPTION
**Pull request by obi12341**
Depends on #1949

### CODE REVIEW

**Comment by drujd** [comment]
LGTM, maybe update Go to 1.12.7?

**Comment by drujd** [comment]
LGTM, maybe update go to 1.12.7?

**Comment by solidnerd** [comment]
@obi12341  Could you also rebase this ?

**Comment by obi12341** [comment]
@solidnerd done

**Comment by phenomax** [comment]
LGTM @solidnerd

**Comment by MatthiasHertel** [comment]
LGTM @solidnerd

**Comment by cwildfoerster** [comment]
ping @solidnerd

**Comment by solidnerd** [comment]
I will close this. I cherry picked the changes and it was released with `12.0.3`

**Pull request closed without merging**
