### PR TITLE
Upgrade GitLab to 8.14.2

### PR DESCRIPTION
**Pull request by solidnerd**
Hey,

i prepared the upgrade for `8.14.2` this includes the update for workhorse. So there will be the mission version fixed. 

Closes #989

### CODE REVIEW

**Comment by solidnerd** [comment]
Waiting for a sync of https://github.com/gitlabhq/gitlabhq .

Ping @smcgivern could you let this happen ?

**Comment by smcgivern** [comment]
That's done now!

Just out of curiosity, could you use the GitLab.com repo instead? https://gitlab.com/gitlab-org/gitlab-ce/tags

That's guaranteed to be up-to-date 😃

**Comment by phenomax** [comment]
You have to upgrade workhorse to v1.**1**.0 instead of v1.**0.1**. 🔢 
[Workhorse changelog](https://gitlab.com/gitlab-org/gitlab-workhorse/blob/master/CHANGELOG)

**Comment by solidnerd** [comment]
@smcgivern Last time we switched to gitlab.com we got some problems with shallow cloning. Here is a pr for that #842 .

I have a second question why is the github repo not automically mirrored from gitlab. This could be done by a CI Job 😄  .

But thanks anyway for the work 😄  .

**Comment by smcgivern** [comment]
@solidnerd fair enough! Just bear https://github.com/gitlabhq/gitlabhq#canonical-source in mind 😉 

I don't know why we don't mirror, but we do push to GitHub as [part of our release process](https://gitlab.com/gitlab-org/release-tools/blob/master/doc/push-to-multiple-remotes.md) - it just got missed for some reason on this patch. Sorry about that!

**Pull request merged**
