### PR TITLE
Upgrade GitLab to 9.4.0

### PR DESCRIPTION
**Pull request by solidnerd**

### CODE REVIEW

**Comment by phenomax** [comment]
What is missing?

**Comment by jostyee** [comment]
Seems there're more work to do the upgrade: https://gitlab.com/gitlab-org/gitlab-ce/issues/35438#note_35677506

**Comment by solidnerd** [comment]
Nothing was missing so far I know. I waited for the BaseImage update. I'm gonna release this today.

**Comment by reynold-lariza** [comment]
There seems to be some problem with migrating from 9.3 to 9.4 https://gitlab.com/gitlab-org/gitlab-ce/issues/35438, I've encountered similar issue with MariaDB as database

```
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Cannot add or update a child row: a foreign key constraint fails (`gitlab`.`#sql-1_4331`, CONSTRAINT `fk_rails_9ffc86a3d9` FOREIGN KEY (`protected_branch_id`) REFERENCES `protected_branches` (`id`) ON DELETE CASCADE): ALTER TABLE `protected_branch_push_access_levels` ADD CONSTRAINT `fk_rails_9ffc86a3d9`
FOREIGN KEY (`protected_branch_id`)
  REFERENCES `protected_branches` (`id`)
 ON DELETE CASCADE

```

**Pull request merged**
