### PR TITLE
Upgrade Workhorse to 1.0.1 and GitLab to 8.14.1

### PR DESCRIPTION
**Pull request by phenomax**
Because GitLab has released [v8.14.1](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG.md), I will now prepare everything for upgrade.
Because the new version includes the workhorse version v1.0.1, this pull request will now be 
changed to the general upgrade of gitlab.

### CODE REVIEW

**Comment by reynold-lariza** [comment]
I suppose this can be ignore, since there is already [8.14.1 release](https://about.gitlab.com/2016/11/28/gitlab-8-14-1-released/)

**Comment by solidnerd** [comment]
@reynold-lariza  I think this shouldn't be ignored. We need this for `8.14.0`. 

@phenomax Thanks for your work. I will test this later and merge it .

**Comment by phenomax** [comment]
Yeah, I also noticed it. I will now start preparing a pull request for GitLab 8.14.1 :)

**Comment by solidnerd** [comment]
@phenomax Could you please make a seperate pull request for the `8.14.1` update, because I wan't to release an updated version of `8.14.0`. Futhermore I would appreciate that your commit message for the upgrade look like `Upgrade to GitLab 8.14.1` .

**Comment by phenomax** [comment]
@solidnerd Sure.

**Comment by phenomax** [comment]
See #989 for the separate commit for v8.14.0

**Comment by evenh** [comment]
Please add a note for the changelog as well :-)

**Comment by reynold-lariza** [comment]
The missing version seems to be still there :|

image

**Comment by sash** [comment]
Im guessing https://github.com/sameersbn/docker-gitlab/pull/989 will fix that

**Comment by reynold-lariza** [comment]
I've already it applied on mine, but still didn't show the version number

**Pull request closed without merging**
