### PR TITLE
Remove build files after installation finished

### PR DESCRIPTION
**Pull request by chengweiv5**
Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>

### CODE REVIEW

**Comment by adamlc** [comment]
Because this is being done in an addition RUN command it'll actually create an additional layer, so won't really have any affect to the build size, assuming thats what you want to do!

**Comment by chengweiv5** [comment]
@adamlc oh, that's correct! so it's should be removed in the install script.

**Comment by chengweiv5** [comment]
updated

**Comment by jostyee** [comment]
@solidnerd this pr can reduce almost 600MB of the final image size.

**Comment by solidnerd** [comment]
But I think it will brake some functionality. So one case would be that `GITLAB_RELATIVE_URL_ROOT` is working also after this.

**Pull request closed without merging**
