### PR TITLE
Upgrade GitLab to 10.6.0

### PR DESCRIPTION
**Pull request by solidnerd**

### CODE REVIEW

**Comment by Ilya-Kuchaev** [comment]
Something wrong with the PR?

**Comment by Kiina** [comment]
Have it running for 5 days now without problem

**Comment by jameswalmsley** [comment]
@solidnerd Will this be merged soon?

**Comment by masakij** [comment]
https://about.gitlab.com/2018/03/28/gitlab-10-6-1-released/

10.6.1 was released. This resolves  a number of  regressions and bugs in 10.6.0.

**Pull request merged**
