### PR TITLE
Upgrade to 12.0.0

### LINKED ISSUE #1909: GitLab 11.10 requires Python 3 for reStructuredText markup
Starting with GitLab 11.10, Python 3 is required to render files in reStructuredText markup.  Update the installed packages in the Dockerfile with python3 and python3-docutils.

GitLab Issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/59062
GitLab Documentation: https://docs.gitlab.com/ee/development/python_guide/#python-development-guidelines

### PR DESCRIPTION
**Pull request by obi12341**
This one is a new MR, because of restructuring. See original MR #1941

Resolves #1909

### CODE REVIEW

**Comment by obi12341** [comment]
ping @solidnerd :)

**Comment by solidnerd** [comment]
I tested your first version of 12.0.0 it was good for me. Currently I'm testing the other mr that I plan to move in for 12.0.0. I think it need one or two days to ship it. Patches going all faster in general.

**Comment by obi12341** [comment]
okay cool :) thanks for the info :+1:

**Comment by solidnerd** [comment]
LGTM !

**Pull request merged**
