### PR TITLE
Update to GItLab 8.16.3

### PR DESCRIPTION
**Pull request by solidnerd**
Hey,
like i said in previous pr i look in the prs on the evening . @sameersbn  Handled it all so. I saw a new release 😄  . So let's take it and ship it .

### CODE REVIEW

**Comment by solidnerd** [comment]
LGTM !

**Comment by phenomax** [comment]
Thanks for the quick update... GitLab does really annoy me with their minutely updates xD

**Comment by sameersbn** [comment]
@phenomax If you are using GitLab in productio  you should wait a couple of weeks after a new releases before upgrading. I think a good upgrade strategy for GitLab in production would be to delay upgrades by a month.

**Comment by solidnerd** [comment]
@phenomax There were a discussion about it in #1058  .

**Comment by phenomax** [comment]
@sameersbn Normally, I do. But if GitLab publishes a new version, including important security fixes, I am about to update asap.

**Comment by iamchanghyunpark** [comment]
@phenomax #1065 Checkout the last comment I added.

**Pull request merged**
