### PR TITLE
[GitLab Critical Security Release] Update GitLab version to 16.7.2

### PR DESCRIPTION
**Pull request by nickshek**
I would like to merge the changes from GitLab 16.7.2 into our project. 

This version contains a critical security fix that addresses a vulnerability in the software. 

The details of the security issue can be found in https://about.gitlab.com/releases/2024/01/11/critical-security-release-gitlab-16-7-2-released/

### CODE REVIEW

**Comment by omueller** [comment]
Thanks, also really looking forward to those packages, CVE rating 10...

**Review by rageAgainstTheMachine99 — APPROVED** [review]

**Comment by sachilles** [comment]
@nickshek Please merge my PR on your repo!

Thank you for contributing to this project.

**Comment by ymazzer** [comment]
@sachilles it seems the tag 16.7.2 has not been push so no release has been created and image is not built :\

**Comment by sachilles** [comment]
@ymazzer The image isn't build so far. I'm planning to include #2879 to be up to date regarding go.

**Comment by ymazzer** [comment]
> @ymazzer The image isn't build so far. I'm planning to include #2879 to be up to date regarding go.

Ok thanks for the clarification :)

**Comment by sachilles** [comment]
The build should be published within the next 60 minutes.

**Pull request merged**
