### PR TITLE
Upgrade GitLab to 9.3.8

### PR DESCRIPTION
**Pull request by solidnerd**

### CODE REVIEW

**Comment by solidnerd** [comment]
It seems that this patch adds new depedencies and that breaks the build process of incomplete libs. I will wait to see what happened in the upstream.

**Comment by abeltay** [comment]
These are the release notes...
https://about.gitlab.com/2017/07/19/gitlab-9-dot-3-dot-8-released/

**Comment by abeltay** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/35342

**Comment by maikelvl** [comment]
There is a new dependency: re2 library

I've managed to complete the gem install with the following:

```
apt-get install -y checkinstall
prev_pwd=$PWD
cd /tmp
git clone https://github.com/google/re2.git
cd re2/
make
make test
checkinstall -D --install=no -y
dpkg -i re2_20170720-1_amd64.deb
ldconfig
apt-get remove checkinstall
cd $prev_pwd
rm -rf /tmp/*
```

But now the `exec_as_git bundle exec rake gitlab:assets:compile USE_DB=false SKIP_STORAGE_VALIDATION=true` fails with the following:

```
/home/git/gitlab/node_modules/.bin/webpack --config /home/git/gitlab/config/webpack.config.js --bail
rake aborted!
Command failed with status (): [/home/git/gitlab/node_modules/.bin/webpack...]
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/webpack-rails-0.9.10/lib/tasks/webpack.rake:17:in `block (2 levels) in <top (required)>'
Tasks: TOP => gitlab:assets:compile => webpack:compile
(See full trace by running task with --trace)
```

**Comment by maikelvl** [comment]
With `--trace`:

```
Command failed with status (): [/home/git/gitlab/node_modules/.bin/webpack...]
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `sh'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:37:in `sh'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/webpack-rails-0.9.10/lib/tasks/webpack.rake:17:in `block (2 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
Tasks: TOP => gitlab:assets:compile => webpack:compile
```

**Comment by phenomax** [comment]
gitlab

**Comment by greyferret** [comment]
Upgrade to 9.3.9 and RE2 installation by separate commits in #1297

**Comment by solidnerd** [comment]
@greyferret I cherry-picked your commit for the re2 library to use this directly with the 9.3.8 release. After this is working I will work on the 9.3.9

**Comment by solidnerd** [comment]
@greyferret I removed all unused stuff after installing re2

**Comment by solidnerd** [comment]
Now it's LGTM !

**Pull request merged**
