### PR TITLE
Add ability to use Google Cloud as Object Store provider

### PR DESCRIPTION
**Pull request by drubin**
Adds the ability to use Google Cloud Storage as an Object Store.

Add default config  for 

* `GITLAB_OBJECT_STORE_CONNECTION_PROVIDER`
* `AWS_ACCESS_KEY_ID`
*  `AWS_SECRET_ACCESS_KEY `
*  `GITLAB_OBJECT_STORE_CONNECTION_GOOGLE_CLIENT_EMAIL`
* `GITLAB_OBJECT_STORE_CONNECTION_GOOGLE_JSON_KEY_LOCATION`
* `GITLAB_OBJECT_STORE_CONNECTION_GOOGLE_PROJECT`

I will rebase/fix commits if we are happy.

### CODE REVIEW

**Comment by drubin** [comment]
@solidnerd hi any chance you can give a review?

**Comment by drubin** [comment]
Maybe we can still get this into the 11.8 version.

**Comment by solidnerd** [comment]
Hey @drubin,

I'll check this out later. Do you have a small example config to test this directly ? Probably we can pick this up in 11.8.0

**Comment by drubin** [comment]
Hi @solidnerd 

You can add the following to your docker-compose file. 

`gcs-bucket` will need to be a real google cloud bucket and updated for each of `uploads` `lfs` and `artifacts`

`GITLAB_OBJECT_STORE_CONNECTION_GOOGLE_PROJECT` a google projectID 
`GITLAB_OBJECT_STORE_CONNECTION_GOOGLE_CLIENT_EMAIL` should be a service account email
`GITLAB_OBJECT_STORE_CONNECTION_GOOGLE_JSON_KEY_LOCATION` location for the downloaded service account key file. 

Sorry, I can't really share my personal Google account with you.


```yaml
    - GITLAB_OBJECT_STORE_CONNECTION_GOOGLE_PROJECT=gcs-project
    - GITLAB_OBJECT_STORE_CONNECTION_GOOGLE_CLIENT_EMAIL=aa@b.com
    - GITLAB_OBJECT_STORE_CONNECTION_GOOGLE_JSON_KEY_LOCATION=/gcs/creds.json
    - GITLAB_OBJECT_STORE_CONNECTION_PROVIDER=Google

    - GITLAB_LFS_OBJECT_STORE_ENABLED=true
    - GITLAB_LFS_OBJECT_STORE_BACKGROUND_UPLOAD=true
    - GITLAB_LFS_OBJECT_STORE_REMOTE_DIRECTORY=gcs-bucket

    - GITLAB_ARTIFACTS_OBJECT_STORE_ENABLED=true
    - GITLAB_ARTIFACTS_OBJECT_STORE_BACKGROUND_UPLOAD=true
    - GITLAB_ARTIFACTS_OBJECT_STORE_REMOTE_DIRECTORY=gcs-bucket
    
    - GITLAB_UPLOADS_OBJECT_STORE_ENABLED=true
    - GITLAB_UPLOADS_OBJECT_STORE_BACKGROUND_UPLOAD=true
    - GITLAB_UPLOADS_OBJECT_STORE_REMOTE_DIRECTORY=gcs-bucket
```

Let me know if you need any further input.

**Comment by drubin** [comment]
Hi @solidnerd do you need anything else from me or can we get this merged

**Comment by solidnerd** [comment]
Hey @drubin,

I only time to check this. I didn't get it until now. I'll try it on the weekend. 

A first view it's looking good to me. But let's me try this and when everything is working for me. I think it can be in the next release. As a first shot my side.

**Comment by drubin** [comment]
@solidnerd Thanks for confirming.

**Pull request merged**
