### PR TITLE
Re-word 'Generation of Self Signed Certificate' section

### PR DESCRIPTION
**Pull request by ngpestelos**
Replace plural certificates with singular.

Minor grammar fixes (e.g. fix punctuation and omit extra words).

### CODE REVIEW

**Comment by sameersbn** [comment]
You would need to update the TOC as well.

**Comment by ngpestelos** [comment]
@sameersbn Done.

**Comment by nsymms** [comment]
If I may offer a couple of items to this PR just to make sure we're correcting the grammar without creating new issues...

- I'm sure it's an oversight, but on line 520 you've left out out the word "have". Actually IMHO there is nothing wrong with the original sentence. It's a little awkward and needs a capital 'Y', but that's all.
- Line 500 should have an article before "SSL certificate". It should be "an SSL certificate" (or 'a' -- there's probably room for debate).

And sorry if I didn't do this properly. I'm not sure if I'm supposed to make a pull request of a pull request or how that works.

**Comment by sameersbn** [comment]
@nsymms can you make a PR with your proposed changes.

**Comment by ngpestelos** [comment]
@sameersbn @nsymms Thank you for your feedback. I'm going through the other docs as well.

**Comment by sameersbn** [comment]
nice. thats great guys.

**Pull request merged**
