### PR TITLE
Upgrade GitLab CE to 16.1.0

### PR DESCRIPTION
**Pull request by sachilles**
GitLab 16.1 Release (see <https://about.gitlab.com/releases/2023/06/22/gitlab-16-1-released/>)

### CODE REVIEW

**Comment by sachilles** [comment]
The test isn't successful since GitLab does not start correctly. There is an issue with puma that fails on start.

**Comment by sachilles** [comment]
In `puma.rb:41` the line looks like

```ruby
40: require_relative "/home/git/gitlab/lib/gitlab/cluster/lifecycle_events"
41: require_relative "/home/git/gitlab/lib/gitlab/cluster/puma_worker_killer_initializer"
```

but the directory `/home/git/gitlab/lib/gitlab/cluster/` does not provide the `puma_worker_killer_initializer`

```
root@431410575dcb:/home/git/gitlab/lib/gitlab/cluster# ls -alh
total 40K
drwxrwxr-x   3 git git 4.0K Jun 23 19:27 .
drwxrwxr-x 157 git git  20K Jun 23 19:27 ..
-rw-rw-r--   1 git git 6.1K Jun 23 19:27 lifecycle_events.rb
drwxrwxr-x   2 git git 4.0K Jun 23 19:27 mixins
-rw-rw-r--   1 git git 1.3K Jun 23 19:27 rack_timeout_observer.rb
```

**Comment by kkimurak** [comment]
The file `` have been removed v16.1.0-ee release, especially in commit https://gitlab.com/gitlab-org/gitlab/-/commit/8ef0e7b5913fffdc1a991f0b2e56de857fa6c337

We must remove the line in `assets/runtime/config/gitlabhq/puma.rb`.

````diff
diff --git a/assets/runtime/config/gitlabhq/puma.rb b/assets/runtime/config/gitlabhq/puma.rb
index f48ff788..df5b5eea 100644
--- a/assets/runtime/config/gitlabhq/puma.rb
+++ b/assets/runtime/config/gitlabhq/puma.rb
@@ -39,7 +39,6 @@ bind 'tcp://127.0.0.1:8080'
 workers {{PUMA_WORKERS}}
 
 require_relative "{{GITLAB_INSTALL_DIR}}/lib/gitlab/cluster/lifecycle_events"
-require_relative "{{GITLAB_INSTALL_DIR}}/lib/gitlab/cluster/puma_worker_killer_initializer"
 
 on_restart do
   # Signal application hooks that we're about to restart
````


----

I think they are not be required, but there were some changes for `puma.rb.example (as usual).  

````diff
diff --git a/assets/runtime/config/gitlabhq/puma.rb b/assets/runtime/config/gitlabhq/puma.rb
index f48ff788..df5b5eea 100644
--- a/assets/runtime/config/gitlabhq/puma.rb
+++ b/assets/runtime/config/gitlabhq/puma.rb
@@ -60,6 +59,11 @@ on_worker_boot do
   Gitlab::Cluster::LifecycleEvents.do_worker_start
 end
 
+on_worker_shutdown do
+  # Signal application hooks that a worker is shutting down
+  Gitlab::Cluster::LifecycleEvents.do_worker_stop
+end
+
 # Preload the application before starting the workers; this conflicts with
 # phased restart feature. (off by default)
 preload_app!
@@ -72,6 +76,9 @@ tag 'gitlab-puma-worker'
 #
 worker_timeout {{PUMA_TIMEOUT}}
 
+# https://github.com/puma/puma/blob/master/5.0-Upgrade.md#lower-latency-better-throughput
+wait_for_less_busy_worker ENV.fetch('PUMA_WAIT_FOR_LESS_BUSY_WORKER', 0.001).to_f
+
 # Use json formatter
 require_relative "{{GITLAB_INSTALL_DIR}}/lib/gitlab/puma_logging/json_formatter"
 
@@ -79,3 +86,12 @@ json_formatter = Gitlab::PumaLogging::JSONFormatter.new
 log_formatter do |str|
   json_formatter.call(str)
 end
+
+lowlevel_error_handler do |ex, env|
+  if Raven.configuration.capture_allowed?
+    Raven.capture_exception(ex, tags: { 'handler': 'puma_low_level' }, extra: { puma_env: env })
+  end
+
+  # note the below is just a Rack response
+  [500, {}, ["An error has occurred and reported in the system's low-level error handler."]]
+end

**Comment by sachilles** [comment]
I'll provide an additional commit.

**Comment by sachilles** [comment]
@kkimurak Can you confirm that the image 16.1.0 works? (In my case the server is up but I get always the status code 500. This could be a result of an interrupted migration.)

**Comment by kkimurak** [comment]
@sachilles I'll check but I'm on out so that I cannot access to easy confirmution environment I usually use. It may takes a time.  
Do you see any error on docker log or `/var/log/gitlab/*` in container?

**Comment by sachilles** [comment]
@kkimurak My installation wasn't working since the migrations haven't been finished due to the broken image. After checking and rerunning the migrations again, everything seems to work as expected. (Luckily.) Thanks for your fast reply.

**Comment by kkimurak** [comment]
Yay my new installation is up successfully anyway, glad to hear that.

**Pull request merged**
