### PR TITLE
upgrade GitLab CE to 13.10.3

### PR DESCRIPTION
**Pull request by ErwinJunge**
Critical security release: https://about.gitlab.com/releases/2021/04/14/security-release-gitlab-13-10-3-released/

### CODE REVIEW

**Comment by bjf893** [comment]
@ErwinJunge Would you mind updating the VERSION file as well? Not sure if anybody uses the Makefile, but VERSION is referenced in there.

**Comment by ErwinJunge** [comment]
Thanks for pointing it out @bjf893, I missed that one!

**Comment by omueller** [comment]
Hi @sameersbn and @bjf893, and thanks for the PR @ErwinJunge!  Do you think there are chances to have this released later today or the next days?  It is always nice to be able to apply important (according to gitlab) security fixes...   Thanks for your work & nice week-end to you!

**Comment by bjf893** [comment]
@solidnerd Sorry to bug you, but would you be willing to merge this? It's a critical security update.

**Comment by sameersbn** [comment]
thanks for the contribution, the patch release will be available soon...

**Pull request merged**
