### PR TITLE
[GitLab Security Release] Upgrade to 13.10.1

### PR DESCRIPTION
**Pull request by sachilles**
GitLab Patch Release: 13.10.1 (see <https://about.gitlab.com/releases/2021/03/31/security-release-gitlab-13-10-1-released/>)

This PR is based on #2327 .

### CODE REVIEW

**Comment by sachilles** [comment]
Unfortunately, the build fails with the message

```
$ NODE_OPTIONS="--max-old-space-size=3584" webpack --config config/webpack.config.js
IncrementalWebpackCompiler: Status – disabled
Warning: fragment with name PageInfo already exists.
graphql-tag enforces all fragment names across your application to be unique; read more about
this in the docs: http://dev.apollodata.com/core/fragments.html#unique-names
Error: EEXIST: file already exists, open '/home/git/gitlab/node_modules/.cache/compression-webpack-plugin/tmp/5235afea'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Unable to compile webpack production bundle.
The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 1
```

Do you have any idea?

**Comment by sachilles** [comment]
I have initiated the build again. No problems were encountered on the second run.

I guess that the build environment was "not clean" and may have contained fragments from previous pipelines.

Can this be confirmed?

**Comment by sachilles** [comment]
It seems that the build cannot be built even on Gitlab itself. 

grafik


Now I get the following error message:

```
#9 2066.2 yarn run v1.22.5
#9 2066.3 $ NODE_OPTIONS="--max-old-space-size=3584" webpack --config config/webpack.config.js
#9 2068.6 IncrementalWebpackCompiler: Status – disabled
#9 2140.6 Killed
#9 2140.9 error Command failed with exit code 137.
#9 2140.9 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#9 2141.0 Error: Unable to compile webpack production bundle.
```

That's really very weird.

**Comment by sameersbn** [comment]
resolved conflicts after merge of #2331

**Pull request merged**
