### PR TITLE
Upgrade gitlab to 13.4.2

### PR DESCRIPTION
**Pull request by bjf893**
https://about.gitlab.com/releases/2020/09/24/gitlab-13-4-1-released/

### CODE REVIEW

**Comment by bjf893** [comment]
@solidnerd Is there any other way I can help get new releases merged? I closed the other pull requests, as those version are already outdated again.

**Comment by cwildfoerster** [comment]
Tested and it working like a charm.

**Comment by cwildfoerster** [comment]
ping @solidnerd @sameersbn

**Comment by solidnerd** [comment]
hey 👋,
I‘ll merge it after my work.

Constantin <notifications@github.com> schrieb am Do. 1. Okt. 2020 um 12:15:

**Comment by gimler** [comment]
https://about.gitlab.com/releases/2020/10/01/security-release-13-4-2-release/ security release

**Comment by mash1t** [comment]
Hey @solidnerd, it would be great to either release 13.4.1 or https://github.com/sameersbn/docker-gitlab/pull/2229 to solve the 2fa bug which accidentally slipped in by Gitlab in version 13.3.4, see https://gitlab.com/gitlab-org/gitlab/-/issues/244638.

**Comment by f-io** [comment]
@bjf893 may you update your pull request in favor of 13.4.2, preferably before solidnerd is done with his work :) ..

**Pull request merged**
