### PR TITLE
Use Ruby 2.4

### PR DESCRIPTION
**Pull request by splattael**
Hi,

the purpose of this PR is to try out GitLab with Ruby 2.4.

"It works for me". No failures so far.

screenshot from 2017-04-04 12 19 14

As am not sure what's the official status is of upgrading to Ruby 2.4 I'd love to hear more success/failure stories :grinning: :green_heart: 

Kind regards,
  Peter

### CODE REVIEW

**Comment by splattael** [comment]
The GitLab Install Docs states:

> Note: The current supported Ruby version is 2.3.x. GitLab 9.0 dropped support for Ruby 2.1.x.

https://github.com/gitlabhq/gitlabhq/blob/master/doc/install/installation.md#2-ruby

**Comment by splattael** [comment]
I am seeing this warning after `git push`

> remote: /home/git/gitlab-shell/lib/vendor/redis/lib/redis/client.rb:459: warning: constant ::Fixnum is deprecated

I think this warning would go away after upgrading to `redis ~> 3.3.3`.
It's been fixed in https://github.com/redis/redis-rb/commit/9da74357491a77e128474aa929054fa402fc211d

**Comment by solidnerd** [comment]
Hey, 
thanks for the PR. At the moment I'm not sure if we should upgrade to `2.4` because it's official not supported by GitLab. 

To Fix this warning we need to upgrade our gitlab shell because it's an dependency from GitLab Shell and not GitLab by it self. Or is the way I'm thinking wrong?

**Comment by phpb-com** [comment]
Tried it and issues board is broke, influxdb stats for many metrics is missing. Would not advice to go with 2.4 for now. Though, on a plus side, it is noticeably faster ...

**Comment by splattael** [comment]
@phpb-com Thanks for trying!

I do not see errors for the issue board. Could you please provide more insight?

As for metrics, I do not use them anymore :-( Which metrics are missing?

Kind regards,
  Peter

**Comment by phpb-com** [comment]
@splattael I think, looking at the logs, most of the metrics had integer vs. float mismatch. Since I played with gems as well, that could be the problem. 

As for the board of issues, now I am not sure if it was a problem with me being partially logged out or if that was the real problem. You can help me troubleshoot if you want, try pulling gotfix/gitlab:2858e06e and see if you have different results.

**Comment by splattael** [comment]
The warning from https://github.com/sameersbn/docker-gitlab/pull/1164#issuecomment-291786644 has disappeared since 9.5.0.

Still, I do not experience any problems running Ruby 2.4.

screenshot from 2017-09-04 09-33-21

Just my 2 cents :smiley_cat:

**Comment by jostyee** [comment]
@splattael We're still seeing

```log
==> unicorn.stderr.log <==
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/html/document.rb:164: warning: constant ::Fixnum is deprecated
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node.rb:390: warning: constant ::Fixnum is deprecated
```

after upgrade ruby to 2.4.1 and redis to 4.0.1

**Comment by splattael** [comment]
@jostyee Oh, you are right :+1: 

I was talking about the :warning: warning which appeared after you `git push`. This should be gone.

Other than the warnings, do you see any problems? Just curios.

**Comment by jostyee** [comment]
https://stackoverflow.com/a/44477520/391464 said Rails 4.2.8 already supports Ruby 2.4, kinda weird.

**Comment by splattael** [comment]
@jostyee It seems that the :warning: warnings you talked about disappeared for me.

`grep warning log/*.log` is empty :tada: 

BTW, I am still running on Ruby 2.4 w/o any issues:

screenshot from 2017-11-11 21-44-29

Any other success stories or failures with Ruby 2.4? :pray:

**Comment by splattael** [comment]
I've just rebased againts the latest `master`.

Still no failures running Ruby 2.4 :smile: 

screenshot from 2018-01-26 08-23-43

Any other success stories? :thinking:

**Comment by splattael** [comment]
Rebased. Ruby 2.4 still works like a charm :green_heart: 

screenshot from 2018-05-02 10-44-33

**Comment by splattael** [comment]
Rebase. Still no problems with `10.8.4`

screenshot from 2018-06-07 14-00-14

**Comment by splattael** [comment]
@solidnerd It seems that GitLab CE (and EE) is using Ruby 2.4.4 since 11.0.0 :exclamation: :astonished: :nerd_face: 
See MR https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/19055

Sooooo, let's merge this PR :question: :1st_place_medal: 

WDYT?

**Comment by splattael** [comment]
Rebased. Still no problems with Ruby `2.4.4` on GitLab `11.0.1`.

screenshot from 2018-06-27 12-16-25

**Comment by solidnerd** [comment]
I tested it and it will be included in the next release `11.0.3`. Thanks for your patient and work ;)

**Comment by solidnerd** [comment]
So,

LGTM !

**Comment by solidnerd** [comment]
@splattael  Could you rebase against master ? I think I did some crappy stuff currently.

**Comment by splattael** [comment]
@solidnerd Sure, will do.

**Comment by splattael** [comment]
@solidnerd Rebased :grin:

**Comment by solidnerd** [comment]
LGTM !

**Pull request merged**
