### PR TITLE
[ADD] Let's Encrypt and default theme setting

### PR DESCRIPTION
**Pull request by KartoffelToby**
Env:

    - GITLAB_DEFAULT_THEME=9 // 1-10 Theme Color ID

    - LETSENCRYPT_ENABLED=true
    - LETSENCRYPT_CONTACT_MAIL=cert@admin.de
    - LETSENCRYPT_GROUP=root
    - LETSENCRYPT_KEY_SIZE=2048
    - LETSENCRYPT_OWNER=root
    - LETSENCRYPT_AUTO_RENEW=true
    - LETSENCRYPT_RENEW_DAYOFMONTH="*/4"

### CODE REVIEW

**Comment by reynold-lariza** [comment]
cool! thanks! but you might want to separate them to two PRs? theme and letsencrypt. I've added the theme configuration to mine, but not LE, as I don't really need it :)

**Comment by KartoffelToby** [comment]
The Color Theme is tested and functional. But the LE isn't working. Maybe i missed something.

@offtopic: I splitt this merge request. Color Theme without LE is in: #1659

**Comment by Ilya-Kuchaev** [comment]
Any news here?

**Comment by rozpuszczalny** [comment]
I'm also intrested in this

**Comment by KartoffelToby** [comment]
@Ilya-Kuchaev @rozpuszczalny 

The Config:
letsencrypt['enable'] = true
letsencrypt['auto_renew_hour'] = "12"
letsencrypt['auto_renew_minute'] = "30"
letsencrypt['auto_renew_day_of_month'] = "*/7"
letsencrypt['auto_renew'] = true

must be set in /etc/gitlab/gitlab.rb

And also "external_url" must be https

I think one of my configs dosn't work with the current setup, i need help here

**Comment by phancey** [comment]
hi, I am using this container on my QNAP NAS and want to use the LETS_ENCRYPT settings but can't really figure out if this has been implemented or if it has what I need to do to enable it? Can someone advise please?
Thanks

**Comment by KartoffelToby** [comment]
It's two years ago 😅 Maybe my pull still work with the current Version, feel free to Test it. But i think most people including me use a proxy Container with le.

**Pull request closed without merging**
