### PR TITLE
Adds GITLAB_REGISTRY_HTTPS var

### LINKED ISSUE #1200: Support of GITLAB_REGISTRY_HTTPS variable
For people running GitLab and Registry behind a load balancer with SSL termination it would be great to support running registry without HTTPS, only HTTPS. This was already fixed in GitLab, see [here](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1312) and [here](https://gitlab.com/gitlab-org/omnibus-gitlab/merge_requests/796). 

My name suggestion for the environment variable is ** GITLAB_REGISTRY_HTTPS**.

### PR DESCRIPTION
**Pull request by galexrt**
This var allows to disable https for usage behind a loadbalancer, like the already existing `GITLAB_HTTPS` var.

Fixes #1200

### CODE REVIEW

**Comment by fmauNeko** [comment]
I already had it done in #1237, looks like I'm not the only one who needs it :D

**Comment by galexrt** [comment]
@fmauNeko I'll ping @solidnerd, maybe he can help get this or #1237 to be merged soon. :)

**Comment by fmauNeko** [comment]
Any news about this ?

**Comment by nachokb** [comment]
I'm interested in this as well

**Comment by cdalvaro2** [comment]
Is this enhancement forgotten?

**Comment by galexrt** [comment]
Closing as no comments from the project owners / maintainers.

For people wanting this feature, feel free to pick up the commit into your own PR.

**Pull request closed without merging**
