### PR TITLE
Added OpenID Connect support

### PR DESCRIPTION
**Pull request by bencurio**
👋 Successfully tested with [ZITADEL](https://zitadel.com/) in GitLab CE 15.5.1

#### docker-compose.yml
```yaml
    - OAUTH_ENABLED=true
[...]
    - OPENID_LABEL=ZITADEL
    - OPENID_ICON=https://<auth_host>/ui/console/assets/icons/favicon-32x32.png
    - OPENID_SCOPE="['openid', 'profile', 'email']"
    - OPENID_RESPONSE_TYPE=code
    - OPENID_ISSUER=https://<auth_host>
    - OPENID_DISCOVERY=true
    - OPENID_CLIENT_AUTH_METHOD=query
    - OPENID_UID_FIELD=uid
    - OPENID_SEND_SCOPE_TO_TOKEN_ENDPOINT=false
    - OPENID_CLIENT_OPTIONS_IDENTIFIER=...
    - OPENID_CLIENT_OPTIONS_SECRET=...
    - OPENID_CLIENT_OPTIONS_REDIRECT_URI=https://<auth_host>/users/auth/openid_connect/callback
```

Docs:
- https://docs.gitlab.com/ee/administration/auth/oidc.html
- https://zitadel.com/docs/guides/integrate/services/gitlab-self-hosted

### CODE REVIEW

**Comment by bencurio** [comment]
@sameersbn  Did I forget something?

**Review by kkimurak — COMMENTED** [review]
Hi @bencurio , Functionally it looks fine to me. Thanks for the contribution and confirmation.

Regarding the name of the parameter, I think it would be nice to prefix it with `GITLAB_OAUTH_`.
Yes, of course I do know that OpenID offers more than just plain Oauth. However, for gitlab, it is just one of the authentication providers and these configurations are in `oauth` section in configuration.

----

Also note that sameersbn is not actively involved in maintenance these years. sachilles is the most active maintainer, but he is not in `watch` status. Please ping him by yourself.

**Comment by jfreax** [comment]
@bencurio Do you plan to update the parameter name to start with  `GITLAB_OAUTH_`? 

@sachilles Is this the only blocker to merge this?

**Comment by bencurio** [comment]
Thank you for your reply!

I finally chose OpenID because the Zitadel documentation recommends it:

https://zitadel.com/docs/guides/integrate/services/gitlab-self-hosted#gitlab-configuration

@jfreax  I'll look into how to configure oAuth instead of OpenID for ZITADEL, but I'll ask for some patience as the test infrastructure is no longer available to me, so I'll have to rebuild it. If everything is correct I will be able to work on it this weekend.

**Pull request closed without merging**
