### PR TITLE
Upgrade GitLab CE to 10.4.3

### PR DESCRIPTION
**Pull request by lordvlad**

### CODE REVIEW

**Comment by ValCapri** [comment]
10.4.4 was released : https://about.gitlab.com/2018/02/16/gitlab-10-dot-4-dot-4-released/

**Comment by lenovouser** [comment]
@solidnerd @sameersbn can you merge this and #1516 / `v10.4.4`

**Comment by Ilya-Kuchaev** [comment]
Any chance to see it merged?

**Comment by solidnerd** [comment]
Sorry for my late response I got very busy last week. I'm back now and I will work on all PR's now.

**Comment by solidnerd** [comment]
LGTM !

**Pull request merged**
