### PR TITLE
Upgrade to GitLab 8.15.2

### PR DESCRIPTION
**Pull request by winggundamth**

### CODE REVIEW

**Comment by paolomainardi** [comment]
LGTM

**Comment by phenomax** [comment]
Any reasons for the delay?

**Comment by solidnerd** [comment]
The reason ist that im currently not available for this because I'm at the
33c3. I will check this during my train travel in the evening.

Am 30.12.2016 3:44 nachm. schrieb "Max" <notifications@github.com>:

**Comment by solidnerd** [comment]
LGTM !

**Pull request merged**
