### PR TITLE
Upgrade to GitLab 9.3.8

### PR DESCRIPTION
**Pull request by greyferret**
With R2 lib build dependencie
https://gitlab.com/gitlab-org/gitlab-ce/issues/35342

### CODE REVIEW

**Comment by solidnerd** [comment]
Hey @greyferret,
I would use your PR instead of mine. For this it would be great to make two commits. First for the Upgrade of GitLab and a second one for the dependency. In future when we are upgrading to Ubuntu Xenial or higher than we don't need the compilation anymore. So than we can revert this commit with no effort.

**Comment by solidnerd** [comment]
If you need help by this let me know.

**Comment by solidnerd** [comment]
@greyferret  Why closing this ?

**Comment by greyferret** [comment]
@solidnerd Sorry, i'm github newbie :) I made a new request with upgrade to 9.3.9 #1297

**Pull request closed without merging**
