### PR TITLE
Upgrade to 12.0.1

### PR DESCRIPTION
**Pull request by obi12341**
Depends on #1947

### CODE REVIEW

**Comment by solidnerd** [comment]
Hey @obi12341,

could you rebase against master please ?

**Comment by obi12341** [comment]
@solidnerd done :)

**Comment by nachokb** [comment]
it failed because of a timeout; could have been a network issue

anybody with write permissions care to retry it?

**Comment by obi12341** [comment]
ping @solidnerd

**Comment by cwildfoerster** [comment]
ping @solidnerd

**Pull request merged**
