### PR TITLE
add env vars for LDAP Attributes

### PR DESCRIPTION
**Pull request by hknochi**
added the possibility to set the attributes for LDAP Users with environment variables

### CODE REVIEW

**Comment by robinro** [comment]
looks good to me, did not run it though

**Comment by SolidNerd** [comment]
LGTM on the first view. 

ping @sameersbn.

**Comment by fheusel** [comment]
Could this please be merged @sameersbn?

**Comment by CrystalMethod** [comment]
:+1::+1:

**Pull request closed without merging**
