### PR TITLE
Upgrade to 12.0.3

### LINKED ISSUE #1909: GitLab 11.10 requires Python 3 for reStructuredText markup
Starting with GitLab 11.10, Python 3 is required to render files in reStructuredText markup.  Update the installed packages in the Dockerfile with python3 and python3-docutils.

GitLab Issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/59062
GitLab Documentation: https://docs.gitlab.com/ee/development/python_guide/#python-development-guidelines

### PR DESCRIPTION
**Pull request by obi12341**
I prepared the release of 12.0.0.
Please review the MR.

Resolves #1909.

### CODE REVIEW

**Comment by darthferretus** [comment]
@obi12341 
Wrong Ruby version: https://gitlab.com/gitlab-org/gitlab-ce/blob/v12.0.0/.ruby-version
Wrong gitlab pages version: https://gitlab.com/gitlab-org/gitlab-ce/blob/v12.0.0/GITLAB_PAGES_VERSION
Wrong gitlab shell version: https://gitlab.com/gitlab-org/gitlab-ce/blob/v12.0.0/GITLAB_SHELL_VERSION

**Comment by obi12341** [comment]
Oh yeah,
missed that. Fixed it and squashed the commits into one commit.

**Comment by ziirish** [comment]
Could you please integrate changes from #1910 as well?
Python3 is now a mandatory requirement for reStructuredText markup since 11.10.

**Comment by obi12341** [comment]
done

**Comment by illusi0nary** [comment]
Once more someone who's faster than me! dang it! :)

**Comment by ziirish** [comment]
Awesome thanks @obi12341

**Comment by illusi0nary** [comment]
Will it be merged soon or have i to create my own image again to have 12.0.0 ?

**Comment by darthferretus** [comment]
ping @solidnerd :)

**Comment by pieterlange** [comment]
> Will it be merged soon or have i to create my own image again to have 12.0.0 ?

It usually helps if someone posts a screenshot of the new version running in prod ;-)

**Comment by Kiina** [comment]
I think it's preferred to have everything split in the commits, so one commit each for Ruby, pages, shell, 12.0.0, gitaly and python

**Comment by Ilya-Kuchaev** [comment]
@solid @sameersbn ping

**Comment by obi12341** [comment]
pushed it the newest bugfix release

**Comment by pieterlange** [comment]
Its the holiday season and solidnerd is probably away. Anyone running this branch yet?

**Comment by drubin** [comment]
>Could you please integrate changes from #1910 as well?
> Python3 is now a mandatory requirement for reStructuredText markup since 11.10. 

This is purely a requirement for development env, not in the compiled released images. [See comment on original MR](https://github.com/sameersbn/docker-gitlab/pull/1910#issuecomment-489461529)

Where is python a runtime requirement of gitlab?

**Comment by ziirish** [comment]
> Where is python a runtime requirement of gitlab?

Try to render a .rst file from within your repo without py3 and then tell me it's only a dev requirement.

**Comment by obi12341** [comment]
@drubin what is the problem? python was included before it now is only a newer version.

**Comment by solidnerd** [comment]
Regarding my response time. My spare time is limited at the moment, but it will be improved in August. So that we can ship features and releases faster starting from august.

**Comment by obi12341** [comment]
Opened a new MR. I will close this one

**Pull request closed without merging**
