### PR TITLE
upgrade GitLab CE to 13.11.0

### PR DESCRIPTION
**Pull request by sachilles**
https://about.gitlab.com/releases/2021/04/22/gitlab-13-11-released/

### CODE REVIEW

**Comment by echavaillaz** [comment]
And today the `13.11.1` is released...

**Comment by sachilles** [comment]
Thank you for pointing this out. I have opened a new PR (see #2346).

**Comment by sameersbn** [comment]
lgtm

**Comment by sameersbn** [comment]
the ci passed the build/tests (https://app.circleci.com/pipelines/github/sameersbn/docker-gitlab/390/workflows/c8bf6e8b-acc3-4c7e-9454-c942e8c39674) but somehow the PR status did not get updated. using admin powers to merge

**Pull request merged**
