### PR TITLE
Upgrade to 13.4.4

### PR DESCRIPTION
**Pull request by bjf893**
https://about.gitlab.com/releases/2020/10/15/gitlab-13-4-4-released/

A more conservative merge request, as requested by @f-io in #2244

### CODE REVIEW

**Comment by cwildfoerster** [comment]
LGTM

**Comment by mash1t** [comment]
more or less superseeded by https://github.com/sameersbn/docker-gitlab/pull/2247

**Comment by solidnerd** [comment]
Hey @bjf893,

sorry for my late delayed response had a lot to do with the last weeks. I'll accept all merge requests of course and will check now more often in the future for updates or doing it on my own.

/cc @cwildfoerster

**Comment by cwildfoerster** [comment]
Glad you back

**Pull request merged**
