### PR TITLE
Upgrade to Gitlab 9.5.4

### PR DESCRIPTION
**Pull request by evenh**
GitLab 9.5.4 is a security patch for a [list of ugly vulnerabilities](https://about.gitlab.com/2017/09/07/gitlab-9-dot-5-dot-4-security-release/)

### CODE REVIEW

**Comment by evenh** [comment]
Huh, very strange that the tag [refers to this version](https://gitlab.com/gitlab-org/gitlab-ce/blob/v9.5.4/GITLAB_PAGES_VERSION). Maybe we should consider not upgrading GitLab Pages for now?

**Comment by solidnerd** [comment]
@evenh  Thanks. I think would should make an issue in the upstream. Would you like to do it ?

**Comment by evenh** [comment]
Filed as https://gitlab.com/gitlab-org/gitlab-ce/issues/37617

**Comment by evenh** [comment]
Rémy Coutable replied and said:
> The v0.5.1 tag for gitlab-pages does exist there: https://gitlab.com/gitlab-org/gitlab-pages/tags/v0.5.1

When I _now_ try to manually download https://gitlab.com/gitlab-org/gitlab-pages/repository/archive.tar.gz?ref=v0.5.1 - it succeeds. I will try to add the updated version again.

**Comment by phenomax** [comment]
LGTM!

**Comment by solidnerd** [comment]
LGTM !

**Pull request merged**
