### PR TITLE
Upgrade GitLab to 10.7.0

### PR DESCRIPTION
**Pull request by solidnerd**

### CODE REVIEW

**Comment by pieterlange** [comment]
Works for me :+1:

**Comment by reynold-lariza** [comment]
Not mine. Encountered `Error while loading the project data. Please try again.` For web ide

**Comment by splattael** [comment]
WebIDE works for me :+1: 

No problems so far. More success/failure stories with 10.7.0 would be awesome :purple_heart:

**Comment by phenomax** [comment]
Just tested. Everything ist working fine

**Comment by reynold-lariza** [comment]
Maybe not all instances will encounter it, but this was reported at https://gitlab.com/gitlab-org/gitlab-ce/issues/45707

All other functionalities seems to be working fine, except for this web-ide feature.

**Comment by nixel2007** [comment]
@reynold-lariza looks like it will be fixed at upstream in 10.7.1

**Comment by solidnerd** [comment]
Currently there is blocker in pr. I would like to have the new shiny shiny features. And the most and interessting feature is this https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/17358 . 

I think I can gonna work on this tomorrow/friday. If anyone has more time todo that I would appreciate it ;) .

**Comment by fire** [comment]
Since the last release breaks the image and there's no downgrade path. Would be good to release this soon.

**Comment by solidnerd** [comment]
If someone has a better regex for d2f1262dfa658811db04dfe37ce32e562fe401e9 I would be very open for this . 

Otherwise LGTM !

**Comment by mfeltscher** [comment]
@solidnerd Is there a reason this tag doesn't show up on [Docker Hub](https://hub.docker.com/r/sameersbn/gitlab/tags/)?

**Comment by solidnerd** [comment]
@mfeltscher It takes some time check https://hub.docker.com/r/sameersbn/gitlab/builds/ . But the tag should be there know.

**Comment by mfeltscher** [comment]
Perfect, thanks!

**Comment by gazben** [comment]
If you are havong trouble with the WebIDE feature and your instance is running behind an apache2 reverse proxy add the following to the config:
```
AllowEncodedSlashes NoDecode and ProxyPass / https://backend/ nocanon
```
Source: https://gitlab.com/gitlab-org/gitlab-ce/issues/45707

**Pull request merged**
