### PR TITLE
Allow DB_COLLATION to be set.

### PR DESCRIPTION
**Pull request by bluecamel**
The motivation for this was needing to override mysql collation to `utf8mb4_general_ci`.

### CODE REVIEW

**Comment by solidnerd** [comment]
Hey, thanks for your PR. Please Remove your https://github.com/sameersbn/docker-gitlab/pull/1098/commits/4247b07d4125d7949ec4a4a728e8829b7f287c4f Commit . And I would prefer a default DB_COLLATION for Postgres as well.

**Comment by davidwindell** [comment]
@bluecamel can you make the requested changes?

We had some problems migrating from 8x to 9x because of collation issues.

**Comment by splattael** [comment]
@solidnerd Kind ping :grinning: 

The README in this PR should note that `DB_COLLATION` is not supported for `postgresql`. Similar to #1239

**Comment by solidnerd** [comment]
@splattael I will put this PR in the next release (9.3.0) . I hope it's okay for you.  Do you want to send me a patch for the README ? Or should I do it on my own 😏 .

**Comment by splattael** [comment]
@solidnerd Well, you could basically just merge #1239? :D

**Comment by solidnerd** [comment]
@splattael Or so :D

**Comment by solidnerd** [comment]
I will close this PR now it's merged through #1262 and available in `9.3.0`

**Pull request closed without merging**
