### PR TITLE
Increase default memory max to address 9.5.x performance problems

### PR DESCRIPTION
**Pull request by lekoder**
Gitlab defaults to unicorn memory limit of ~350MB. In 9.5.x this causes poor performance, as unicorn workers are constantly killed and re-spawned, leading to terrible performance even on small deployments. This problem is detailed in issue #1347 

While it is possible to adjust this limit with environment variables, this PR should provide a sane default.

### CODE REVIEW

**Comment by phenomax** [comment]
Thanks for your PR!
Could you also add your new env. var to the [env-defaults](https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/env-defaults) and the [functions](https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/functions) class, so that it can be used in production?
Otherwise it won't be replaced/used

**Comment by lekoder** [comment]
@phenomax `functions` seems to [source env-defaults already](https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/functions#L3), so we should have this variable set up in production.

Since passing this option in environment already works (just without default), I'm not sure what change is required in `unicorn.rb`. Could you elaborate?

**Comment by andypost** [comment]
btw Why 512M? min-max is 300-350 https://gitlab.com/gitlab-org/gitlab-ce/blob/master/config.ru#L10

**Comment by andypost** [comment]
Also interesting measures https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2421

**Comment by lekoder** [comment]
I took 512M from @chaosversum at #1347. I have tested this on our installations and it worked great - performance was greatly increased, to levels we seen in 8.x. Whole docker uses now 3.8G of RAM (with 8 unicorn workers). With default of 350M workers are killed constantly. Issue itself is detailed in #1347.

**Comment by phenomax** [comment]
@lekoder Correct me, if I am wrong, but don't we have to add the environment variable to the unicorn config and replace it to apply our custom value? Otherwise we won't change the unicorn memory in any way?

**Comment by lekoder** [comment]
@phenomax Isn't env picked up by [config.ru](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/config.ru#L10) anyway? If it was not, setting it via docker command line would not work either. Then again, I didn't actually dwell that deep into gitlab, I don't have experience in ruby. But from my limited knowledge, if env is there, it should work.

**Comment by phenomax** [comment]
Oh sorry. I didnt see the env var in the config.ru

**Comment by lekoder** [comment]
...and my confusion came from fact, that it was you who pointed this particular line in #1347. Good thing that we have this cleared out.

**Comment by solidnerd** [comment]
LGTM ! I will merge this for the 10.0 release and make a note in changelog for that.

**Pull request merged**
