### PR TITLE
Update to Gitlab CE 15.4.0

### PR DESCRIPTION
**Pull request by antt1995**
Update to Gitlab CE 15.4.0

### CODE REVIEW

**Comment by omueller** [comment]
That is nice, PR even before the release of the corresponding Gitlab release, it is not even visible under https://about.gitlab.com/releases/categories/releases/ yet :)   (but it should come later today, as they normally do this every 22. of the month).   

Thanks @antt1995 & cheers!

**Comment by antt1995** [comment]
@omueller I look at the Repo Tags
https://gitlab.com/gitlab-org/gitlab-foss/-/tags

**Comment by antt1995** [comment]
Finally Dropped
https://about.gitlab.com/releases/2022/09/22/gitlab-15-4-released/

**Comment by omueller** [comment]
And here we go again...   https://about.gitlab.com/releases/2022/09/29/security-release-gitlab-15-4-1-released/
No time to do a PR today or tomorrow here unfortunately.

**Pull request merged**
