### PR TITLE
support pages with gitlab relative path

### PR DESCRIPTION
**Pull request by th-2021**

### CODE REVIEW

**Comment by th-2021** [comment]
@sachilles Is this the only blocker to merge this? I rebased the PR against master.

**Comment by sachilles** [comment]
@th-2021 I guess, there is no blocker in general. Since I don't use gitlab pages by myself, and thus I have to familiarize myself with it for  the review.

**Comment by victorelec14** [comment]
@th-2021 ???

**Comment by th-2021** [comment]
This PR was so old (and not merged), so that I merged it with the upcoming pages PR with namespace-in-path.

You can see it at https://github.com/th-2021/docker-gitlab in the pages-update branch.

**Pull request closed without merging**
