### PR TITLE
upgrade Gitlab CE to 13.8.0

### PR DESCRIPTION
**Pull request by sachilles**
Update to Gitlab CE 13.8.0 (see also https://about.gitlab.com/releases/2021/01/22/gitlab-13-8-released/ ).

### CODE REVIEW

**Comment by solidnerd** [comment]
LGTM !

**Comment by Akanoa** [comment]
Hello

The 13.8.0 tag seems to be absent on docker-hub.

Is it legit ? When can we expect to pull gitlab:13.8.0 ?

I'm really impatient to use the new pipeline visualization :D

Thanks by advance

**Comment by brunosavyofs** [comment]
Just like @Akanoa, I'm also unable to pull 13.8.0 version from Docker Hub.

**Comment by Akanoa** [comment]
@brunosavyofs It seems that the  18.3.0 has been skip in favor to 18.3.1 which security patch.
https://hub.docker.com/layers/sameersbn/gitlab/13.8.1/images/sha256-d958722879074d7b508baeb7972d82f9d8c6f8398825c6e62cf083a280c98185?context=explore

**Comment by solidnerd** [comment]
@Akanoa @brunosavyofs It seems that something went wrong in the release process for 13.8.0

**Comment by brunosavyofs** [comment]
> @Akanoa @brunosavyofs It seems that something went wrong in the release process for 13.8.0

That's ok, I'm already running 13.8.1 version. 
Thanks.

**Pull request merged**
