### PR TITLE
Add google cloud storage support

### PR DESCRIPTION
**Pull request by paolomainardi**
As in the subject, this PR adds the google cloud storage backup support.

Just a note, i cannot be defined the best in terms of bash skills, i hope to have followed your coding style as best as possible :)

### CODE REVIEW

**Comment by paolomainardi** [comment]
Any chance to get this MR reviewed any time soon before the 8.15.0 release ?
Merry Christmas :)

**Comment by solidnerd** [comment]
I thought that I answered on your PR  😅 . 

On the first view it's look very neat .

 I will test it with the `8.15.0` release and if everything works as excepted I will merge this.

**Comment by paolomainardi** [comment]
Thanks Nicolas!

**Comment by solidnerd** [comment]
I thought a little more about it and I would prefer that we add more logic in the shell script to cover all storage provider that are supported by fog and gitlab. We should have not so much changes in the `gitlab.yml` . For me i think it would be good that we have only the provider environment variable and add the rest dynamically dependent from the provider.

**Comment by paolomainardi** [comment]
@solidnerd i agree with that but i didn't find any way to do it without be BC.

**Comment by paolomainardi** [comment]
A solution that can be implemented can be the following one:

```
### REMOTE BACKUPS
REMOTE_BACKUPS=${REMOTE_BACKUPS:-false}
REMOTE_BACKUP_PROVIDER=${REMOTE_BACKUP_PROVIDER}
REMOTE_BACKUP_DIRECTORY=${REMOTE_BACKUP_DIRECTORY}
```

That can be instantiated like this:

```
REMOTE_BACKUP_PROVIDER=Google
REMOTE_BACKUP_DIRECTORY=
REMOTE_BACKUP_CONNECTION_OPTIONS_KEY_1=google_storage_access_key_id
REMOTE_BACKUP_CONNECTION_OPTIONS_VAL_1=12341234
REMOTE_BACKUP_CONNECTION_OPTIONS_KEY_2='google_storage_secret_access_key'
REMOTE_BACKUP_CONNECTION_OPTIONS_VAL_2=12341234
```
Where key_N/val_N will be iterated by the bash script using the name as a pattern, building the exact portion needed by the fog storage.

If you have simpler solutions in mind, let me know :)

**Comment by paolomainardi** [comment]
@solidnerd just a follow-up, thanks :)

**Comment by lenovouser** [comment]
Yep, would really like to see this too :)

**Comment by paolomainardi** [comment]
@lenovouser would like to see the gce integration or the gce integration like the last proposal ?

**Comment by paolomainardi** [comment]
@solidnerd do you have time to check this PR ?

**Comment by paolomainardi** [comment]
Can I propose to merge this one while discussing a more generic way to support the providers supported by fog ?

**Comment by sameersbn** [comment]
We can implement some generic logic in future iterations, for now its better to land this.

**Comment by sameersbn** [comment]
On second thought, I dont really like the changes this PR makes. I agree with @solidnerd we should be able to make this configuration generic.

**Comment by paolomainardi** [comment]
Ok what do you suggest ?

**Comment by paolomainardi** [comment]
What do you think about my more generic proposal ?

**Comment by paolomainardi** [comment]
ping @sameersbn @solidnerd

**Comment by solidnerd** [comment]
Hey, 

sorry for my delay. I thought a little more about it. I would be fine with it when we have the following logic. 

Constraint: 
- You can set only one of Cloud Backups AWS OR GCS
- Both set will be result in an error.

1. If Both not set than delete the upload key
2. If AWS is set than fill the `upload:` key with aws related envs if all required not empty.
3. If AWS is not set and GCS is set than check the gcs envs.

So far what I see is that all logic is implemented. 

I wouldn't introduce a new key. I would duplicate only the connection key with google provider and document it that this one will be removed or the google connection.

**Comment by paolomainardi** [comment]
@solidnerd got it, as you said most of the logic is already implemented, what do you want let me change ?

**Comment by solidnerd** [comment]
Like this ?
```yaml  
upload:
     # One of the connection provider will be used
     # Only Once can be used at the time.
      # Fog storage connection settings, see http://fog.io/storage/ .
      connection:
        provider: AWS
        region: {{AWS_BACKUP_REGION}}
        aws_access_key_id: {{AWS_BACKUP_ACCESS_KEY_ID}}
        aws_secret_access_key: '{{AWS_BACKUP_SECRET_ACCESS_KEY}}'
      # The remote 'directory' to store your backups. For S3, this would be the bucket name.
      remote_directory: '{{AWS_BACKUP_BUCKET}}'
       # Use multipart uploads when file size reaches 100MB, see
       #  http://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html
       multipart_chunk_size: 104857600
       # Turns on AWS Server-Side Encryption with Amazon S3-Managed Keys for backups, this is optional
       # encryption: 'AES256'
      Fog storage connection settings, see http://fog.io/storage/ .
      connection:
        provider: Google
        google_storage_access_key_id: {{GCS_BACKUP_ACCESS_KEY_ID}}
        google_storage_secret_access_key: '{{GCS_BACKUP_SECRET_ACCESS_KEY}}'
      remote_directory: '{{GCS_BACKUP_BUCKET}}'
```

**Comment by paolomainardi** [comment]
@solidnerd thanks, i am going to implement it in the next few days.

**Comment by paolomainardi** [comment]
@solidnerd finally did as requested, i hope that now can be merged :)

**Comment by paolomainardi** [comment]
@solidnerd just a follow-up

**Comment by solidnerd** [comment]
Sorry for my late delay and thanks for you patient. I want to merge this. This will be on latest and later in the next release `8.16.5` .

**Comment by paolomainardi** [comment]
Thanks a lot @solidnerd :+1:

**Pull request merged**
