### PR TITLE
Expose `DB_COLLATION` parameter

### PR DESCRIPTION
**Pull request by splattael**
## Problem

Before this commit the database `collation` in `config/database.yml` was hard-coded to `utf8_general_ci`.

This collation does not play nice with `encoding` `utf8mb4` as shown by the following error:

```
E, [2017-06-04T19:38:10.016023 #3220] ERROR -- : COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4' (Mysql2::Error)
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:897:in `query'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:897:in `configure_connection'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:264:in `configure_connection'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:37:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:20:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:20:in `mysql2_connection'
```

## Solution

This PR exposes `DB_COLLATION` as a parameter and defaults to `utf8_general_ci`. So, it's backwards-compatible.

In order to make multibyte work [follow GitLab's MySQL guide](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/database_mysql.md#tables-and-data-conversion-to-utf8mb4) and configure:
* `DB_ENCODING=utf8mb4`
* `DB_COLLATION=utf8mb4_general_ci`

## PostgreSQL

The PR does not affect PostgreSQL as the `collation` option from `config/database.yml` [will be removed](https://github.com/sameersbn/docker-gitlab/blob/2c396c05ee26c1e7813e6c9052ec72e298cad7fe/assets/runtime/functions#L215,L220) on startup.

## Testing

My private instance runs on MySQL with `--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci` and `DB_ENCODING=utf8mb4` and`DB_COLLATION=utf8mb4_general_ci` smootly.
More testing is, of course, much appreciated :green_heart: 

Kind regards,
  Peter

### CODE REVIEW

**Comment by splattael** [comment]
Oops, I've just seen #1098 :cry:

**Comment by solidnerd** [comment]
Yeah thanks for your recognition. I would test #1098 with an PostgreSQL setup. Could you test it with your MySQL Setup so if it works for us. I will make a Patch to solve your Problem.

**Comment by solidnerd** [comment]
In flavor of #1098 . I will close this PR.

**Comment by splattael** [comment]
@solidnerd :+1: 

MySQL works fine for me™ :neckbeard: 

As I described above, PostgreSQL installations should be not affected by this PR as the `collation` option from `database.yml` [is removed](https://github.com/sameersbn/docker-gitlab/blob/2c396c05ee26c1e7813e6c9052ec72e298cad7fe/assets/runtime/functions#L215,L220) on startup.

Thanks for taking your time and keep up great work! :green_heart:

**Comment by splattael** [comment]
@solidnerd As mentioned in https://github.com/sameersbn/docker-gitlab/pull/1098#issuecomment-310658098 you *could* just merge this PR in order to add `DB_COLLATION`.

I've restored this branch and rebased it against the latest master.

Ready to :twisted_rightwards_arrows: merge!

**Comment by solidnerd** [comment]
@splattael At GitHub I can't reopen the PR so I guess I need to do it by hand.

**Comment by splattael** [comment]
@solidnerd I've "re-opened" it in #1262

**Pull request closed without merging**
