### PR TITLE
Upgrade to 11.10.4

### PR DESCRIPTION
**Pull request by Kiina**

### CODE REVIEW

**Comment by drujd** [comment]
Thanks! Maybe update golang to 1.11.9 as well?

**Comment by Kiina** [comment]
Probably won't do much as the only update that will affect us is the 1.11.7, but probably won't hurt to keep it updated

**Comment by Kiina** [comment]
Included 11.10.3 and 11.10.4 + workhorse update

**Comment by paolomainardi** [comment]
ping @solidnerd

**Comment by solidnerd** [comment]
Hey @Kiina,
thanks for your work. I tested everything it works fine for me. For the next please create for every pr a separate pr. It's easier for me to manage this.

I'll cherry pick now all the changes and do the separate releases.

**Comment by solidnerd** [comment]
At rest Image updates will be available during the evening.

**Comment by Kiina** [comment]
Will remember that for the next time

**Comment by solidnerd** [comment]
Images will be available later during a maintenance on the docker hub. https://success.docker.com/article/docker-hub-maintenance

**Comment by solidnerd** [comment]
I'll close this now.

**Pull request closed without merging**
