### PR TITLE
Fixed readme to match new backup file naming

### PR DESCRIPTION
**Pull request by eiabea**
Automated backups are creating tar files like "1515629493_2018_01_11_10.3.3_gitlab_backup.tar", readme only mentioned the old pattern e.g. "1515629493_gitlab_backup.tar"

### CODE REVIEW

**Comment by drubin** [comment]
They changed the format in 9.2 https://docs.gitlab.com/ce/raketasks/backup_restore.html#backup-timestamp.

**Comment by eiabea** [comment]
@drubin yes, but the documentation about it in the readme was still outdated

**Comment by drubin** [comment]
@eiabea I know I am just validating your change with the official docs :) 
Thanks for fixing this.

**Comment by drubin** [comment]
@eiabea Maybe you can re-run the CI job? Travis had issues earlier today https://www.traviscistatus.com/incidents/c1s4dlyxd4lf

**Comment by eiabea** [comment]
@drubin are there some additional steps to do for me? Because i already fixed the third merge conflict due to version updates :smile:

**Comment by drubin** [comment]
@eiabea Sorry I don't have merge permissions, I just suggested a few comments based on what I had gone through with my merge requests.

**Pull request merged**
