### PR TITLE
Update to 8.13.1

### PR DESCRIPTION
**Pull request by adimit**
See #938, #939

### CODE REVIEW

**Comment by reynold-lariza** [comment]
I've testing this PR changes, the MR is now working fine! :)

**Comment by solidnerd** [comment]
@reynold-lariza Okay so the error comes from the upstream but it's fixed. I will work on the 8.13.0 release and after that I will work on 8.13.1 

@adimit Are you there ? So you need to rebase later that I can start with testing and merging of the patch version.

**Comment by adimit** [comment]
I'm here, just tell me what needs rebasing.

**Comment by solidnerd** [comment]
@adimit You can start with a rebase the changelog needs it. And could you chnage your commit message to `Upgrade to Gitlab 8.13.1`.

**Comment by adimit** [comment]
@solidnerd done.

**Comment by solidnerd** [comment]
Thanks I will work on this now.

**Comment by solidnerd** [comment]
LGTM ! I will start with release.

**Pull request merged**
