### PR TITLE
Update Gitlab to 9.0.0

### PR DESCRIPTION
**Pull request by phpb-com**
This PR should cover all of the necessary changes for the update to Gitlab 9.0.0

### CODE REVIEW

**Comment by phpb-com** [comment]
Needed to modify commit message for gitlab-pages

**Comment by phpb-com** [comment]
Similar update was done in [my fork](https://gotfix.com/docker/gitlab) of this project with no issues.

**Comment by iamchanghyunpark** [comment]
I think there were some [changes in the CI variable names](https://about.gitlab.com/2017/03/22/gitlab-9-0-released/#gitlab-ci-ce-ee).
The older variables will be available for a short time but are deprecated.

Will we need to change the variables in `docker-gitlab`? If so, I think the best time to do it would be now :)

**Comment by iamchanghyunpark** [comment]
I did a quick `grep` through the repo, but there seems to be no use of the CI variables.
I guess, no need to worry :)

**Comment by ninja-** [comment]
:y:

**Comment by paolomainardi** [comment]
LGTM :+1:

**Comment by boeserwolf91** [comment]
Why is this PR marked as WIP? Is there still something to do?

**Comment by phpb-com** [comment]
There was one last change that I missed, needed to update the cron section of gitlab.yml

**Comment by f3l1x** [comment]
Good job guys :+1:

**Comment by solidnerd** [comment]
LGTM !

**Comment by mikehaertl** [comment]
Thanks guys!

One thing: I've just updated from 8.16.3 to 9.0.0. Everything looks good so far but during the upgrade there was a warning:

> Missing Rails.application.secrets.jws_private_key for production environment. The secret will be generated and stored in config/secrets.yml

Can this be ignored?

**Comment by HashDot** [comment]
@mikehaertl I've upgraded from 8.17.4 to 9.0.0. Same warning. I think we can ignore the warning.

**Comment by phpb-com** [comment]
All of the investigations I've done so far, indicate that it can be ignored. I am still looking into this in my fork and will submit PR if I find otherwise.

**Comment by drandreas** [comment]
jws_private_key is accessed in GitLab in various functions. 

The warning originates from `config/initializers/secret_token.rb`
> Transition material in .secret to the secret_key_base key in config/secrets.yml.
> Historically, ENV['SECRET_KEY_BASE'] takes precedence over .secret, so we maintain that
> behavior.
> 
> It also used to be the case that the key material in ENV['SECRET_KEY_BASE'] or .secret
> was used to encrypt OTP (two-factor authentication) data so if present, we copy that key
> material into config/secrets.yml under otp_key_base.
> 
> Finally, if we have successfully migrated all secrets to config/secrets.yml, delete the
> .secret file to avoid confusion.

If I understand the method description correctly everything should be fine as long as `GITLAB_SECRETS_SECRET_KEY_BASE` is set. the above function will happily recreate `secrets.yml` during every launch.

**Comment by remohammadi** [comment]
I have set `GITLAB_SECRETS_SECRET_KEY_BASE` in my deployment, but I see `Missing Rails.application.secrets.jws_private_key for ...` every time I deploy a new version of `quay.io/sameersbn/gitlab`, since `9.0.0`.

**Pull request merged**
