### PR TITLE
Upgrade to Gitlab 8.13.0

### PR DESCRIPTION
**Pull request by Pegasuz**
Updated Gilab to version 8.13.0

### CODE REVIEW

**Comment by evenh** [comment]
Great initiative :+1:

I've never upgraded a to minor release before, but I would think that at least the following changes must be applied as well:

- Upgrade gitlab-shell to `3.6.6`
- Upgrade gitlab-workhorse to `0.8.5`

Both of these can be modified in the `Dockerfile` and should be made as two separate commits as per convention of the last few releases (8.12.0, 8.11.0, 8.10.0) to make reverting easier if needed.

**Comment by Pegasuz** [comment]
@evenh I have updated the PR accordingly. Anything else you need me to do?

**Comment by sameersbn** [comment]
@Pegasuz Please apply this patch too 

```diff
diff --git a/assets/build/install.sh b/assets/build/install.sh
index 5320a47..3122840 100755
--- a/assets/build/install.sh
+++ b/assets/build/install.sh
@@ -231,16 +231,7 @@ priority=10
 directory=${GITLAB_INSTALL_DIR}
 environment=HOME=${GITLAB_HOME}
 command=bundle exec sidekiq -c {{SIDEKIQ_CONCURRENCY}}
-  -q post_receive
-  -q mailers
-  -q archive_repo
-  -q system_hook
-  -q project_web_hook
-  -q gitlab_shell
-  -q incoming_email
-  -q runner
-  -q common
-  -q default
+  -C ${GITLAB_INSTALL_DIR}/config/sidekiq_queues.yml
   -e ${RAILS_ENV}
   -t {{SIDEKIQ_SHUTDOWN_TIMEOUT}}
   -P ${GITLAB_INSTALL_DIR}/tmp/pids/sidekiq.pid
```

**Comment by sameersbn** [comment]
this too: 

```diff
diff --git a/assets/runtime/config/gitlab-shell/config.yml b/assets/runtime/config/gitlab-shell/config.yml
index 82fe460..bcaaefa 100644
--- a/assets/runtime/config/gitlab-shell/config.yml
+++ b/assets/runtime/config/gitlab-shell/config.yml
@@ -68,3 +68,10 @@ audit_usernames: false
 # For Debian and Ubuntu systems this can be done with: sudo apt-get install git-annex
 # For CentOS: sudo yum install epel-release && sudo yum install git-annex
 git_annex_enabled: false
+
+# Git trace log file.
+# If set, git commands receive GIT_TRACE* environment variables
+# See https://git-scm.com/book/es/v2/Git-Internals-Environment-Variables#Debugging for documentation
+# An absolute path starting with / – the trace output will be appended to that file.
+# It needs to exist so we can check permissions and avoid to throwing warnings to the users.
+git_trace_log_file:
```

**Comment by sameersbn** [comment]
and this last one :stuck_out_tongue: 

```diff
diff --git a/README.md b/README.md
index 87fdce9..8bb9070 100644
--- a/README.md
+++ b/README.md
@@ -805,6 +805,7 @@ Below is the complete list of available options that can be used to customize yo
 | `GITLAB_EMAIL` | The email address for the GitLab server. Defaults to value of `SMTP_USER`, else defaults to `example@example.com`. |
 | `GITLAB_EMAIL_DISPLAY_NAME` | The name displayed in emails sent out by the GitLab mailer. Defaults to `GitLab`. |
 | `GITLAB_EMAIL_REPLY_TO` | The reply-to address of emails sent out by GitLab. Defaults to value of `GITLAB_EMAIL`, else defaults to `noreply@example.com`. |
+| `GITLAB_EMAIL_SUBJECT_SUFFIX` | The e-mail subject suffix used in e-mails sent by GitLab. No defaults. |
 | `GITLAB_EMAIL_ENABLED` | Enable or disable gitlab mailer. Defaults to the `SMTP_ENABLED` configuration. |
 | `GITLAB_INCOMING_EMAIL_ADDRESS` | The incoming email address for reply by email. Defaults to the value of `IMAP_USER`, else defaults to `reply@example.com`. Please read the [reply by email](http://doc.gitlab.com/ce/incoming_email/README.html) documentation to curretly set this parameter. |
 | `GITLAB_INCOMING_EMAIL_ENABLED` | Enable or disable gitlab reply by email feature. Defaults to the value of `IMAP_ENABLED`. |
diff --git a/assets/runtime/config/gitlabhq/gitlab.yml b/assets/runtime/config/gitlabhq/gitlab.yml
index 07d4fa7..7efbb2c 100644
--- a/assets/runtime/config/gitlabhq/gitlab.yml
+++ b/assets/runtime/config/gitlabhq/gitlab.yml
@@ -67,6 +67,7 @@ production: &base
     email_from: {{GITLAB_EMAIL}}
     email_display_name: {{GITLAB_EMAIL_DISPLAY_NAME}}
     email_reply_to: {{GITLAB_EMAIL_REPLY_TO}}
+    email_subject_suffix: '{{GITLAB_EMAIL_SUBJECT_SUFFIX}}'
 
     # Email server smtp settings are in config/initializers/smtp_settings.rb.sample
 
diff --git a/assets/runtime/env-defaults b/assets/runtime/env-defaults
index ec8940b..95421c9 100644
--- a/assets/runtime/env-defaults
+++ b/assets/runtime/env-defaults
@@ -186,6 +186,7 @@ SMTP_ENABLED=${SMTP_ENABLED:-false}
 GITLAB_EMAIL_ENABLED=${GITLAB_EMAIL_ENABLED:-${SMTP_ENABLED}}
 GITLAB_EMAIL=${GITLAB_EMAIL:-${SMTP_USER}}
 GITLAB_EMAIL_REPLY_TO=${GITLAB_EMAIL_REPLY_TO:-${GITLAB_EMAIL}}
+GITLAB_EMAIL_SUBJECT_SUFFIX=${GITLAB_EMAIL_SUBJECT_SUFFIX:-}
 GITLAB_EMAIL=${GITLAB_EMAIL:-example@example.com}
 GITLAB_EMAIL_REPLY_TO=${GITLAB_EMAIL_REPLY_TO:-noreply@example.com}
 GITLAB_EMAIL_DISPLAY_NAME=${GITLAB_EMAIL_DISPLAY_NAME:-GitLab}
diff --git a/assets/runtime/functions b/assets/runtime/functions
index ac2bab4..1145bd6 100644
--- a/assets/runtime/functions
+++ b/assets/runtime/functions
@@ -359,7 +359,8 @@ gitlab_configure_mail_delivery() {
     GITLAB_EMAIL_ENABLED \
     GITLAB_EMAIL \
     GITLAB_EMAIL_DISPLAY_NAME \
-    GITLAB_EMAIL_REPLY_TO
+    GITLAB_EMAIL_REPLY_TO \
+    GITLAB_EMAIL_SUBJECT_SUFFIX
 }
 
 gitlab_configure_mailroom() {
```

With these changes I think we should be good to test before releasing a new version.

**Comment by Ilya-Kuchaev** [comment]
Please look at https://gitlab.com/gitlab-org/omnibus-gitlab/compare/8-12-stable...8-13-stable#diff-34 changes. I believe there are some useful settings to set with variables.

**Comment by reynold-lariza** [comment]
Attaching issue #938

**Comment by reynold-lariza** [comment]
Hmn... while I was testing with the similar changes into my own fork... merge request get stuck, and not working at all even after refreshing the page :/

**Comment by Pegasuz** [comment]
@sameersbn Patches are applied ;)

**Comment by sameersbn** [comment]
thanks time for some testing..

**Comment by solidnerd** [comment]
Hey, 
i tested it on 2 case with an clean environment and update everything works for me as excepted, but I'm still confused with this auto merging issue.

**Comment by sameersbn** [comment]
Hi @solidnerd are you seeing the merge issue too?
I haven't tried testing yet.. have deferred it by a couple hours.

**Comment by reynold-lariza** [comment]
**Environment/observation with 8.13.0**

My testing is done with an existing (external) data for git, database, and redis. I had to revert to 8.12.7 yesterday morning, after I found that when I tried to accept a MR from one branch to another branch (to an existing project). 

**Behavior:**
The accept merge request button get stuck, and nothing happens. Then after refreshing the page, the MR wasn't merged.

**Comment by solidnerd** [comment]
@reynold-lariza  Thanks for your report. I will wait on your next test. Later at the day I will try to reproduce it.

@sameersbn I didn't make it yesterday, because of my spare time.

**Comment by adimit** [comment]
I've tested on 005f754a38ad98910e55e9f167fcaa02e31733d2 from @Pegasuz branch. Accepted a 149 commit merge request without a problem (topic-branch into master)

**Comment by Ilya-Kuchaev** [comment]
GitLab 8.13.1 released
https://about.gitlab.com/2016/10/25/gitlab-8-dot-13-dot-1-released/

**Comment by adimit** [comment]
@Pegasuz, I've created a [PR](https://github.com/Pegasuz/docker-gitlab/pull/1) for 8.13.1. Works well here.

**Comment by solidnerd** [comment]
@adimit Please create the PR for `8.13.1` in this repo. So we can track it and better maintain it.

**Comment by adimit** [comment]
@solidnerd done.

**Comment by solidnerd** [comment]
So the error comes from the upstream but is fixed in `8.13.1`. I will start with release of 8.13 now and will release 8.13.1 shortly. 

@Pegasuz Thanks for your work and patient.

**Comment by Pegasuz** [comment]
@solidnerd You are very welcome!

**Pull request merged**
