### PR TITLE
Upgrade to 10.5.6

### PR DESCRIPTION
**Pull request by pieterlange**
Ref https://about.gitlab.com/2018/03/20/critical-security-release-gitlab-10-dot-5-dot-6-released/

### CODE REVIEW

**Comment by pieterlange** [comment]
(sorry for *ping* @solidnerd but this is a security release)

**Comment by drujd** [comment]
You missed a change in kubernetes/gitlab-rc.yml

**Comment by pieterlange** [comment]
I did, thanks for the heads up.

**Comment by solidnerd** [comment]
LGTM !

**Pull request merged**
