### PR TITLE
Fixup for multiple Backups

### PR DESCRIPTION
**Pull request by yfoelling**
I fixed an if condition, that caused multiple cron jobs for backups.

### CODE REVIEW

**Comment by yfoelling** [comment]
this should fix #1121

**Comment by solidnerd** [comment]
Hey,
is there anyway to reproduce it. Could you provide an example with before and after your improvement.

**Comment by yfoelling** [comment]
Hey,
the if condition you made is in "$()", which means you test if the returned output string is NOT 0 characters long.
And you suppress every output, so in every case it would be executed.
This causes every restart of the container to add a new cron job.

Examples for the IF clause:
```
if [[ 0 || 0 ]]; then echo true; fi
true
if [[ 1 || 0 ]]; then echo true; fi
true
if [[ 0 || 1 ]]; then echo true; fi
true
if [[ 1 || 1 ]]; then echo true; fi
true
```
```
if [[ "" ]]; then echo true; fi

if [[ ! "" ]]; then echo true; fi
true
```


Example of crontab file:

```
00 04 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
00 04 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
00 04 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
00 04 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
00 04 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
```

Putting the if clause without "[[ ]]" causes bash to listen only to the exit code of the command execution!

**Comment by otheus** [comment]
Bump up. 

Is there any way to customize this backup process? ie, post-run hook (for instance, to trigger save-to tape)

**Comment by dmednis** [comment]
Any news on when this could be merged? The multiple backups cause our server to fill up its disk space.
As it was said, this can be reproduced(reproducible in 9.4.3) by restarting the Gitlab container without deleting it.

**Comment by QuickJack** [comment]
I was also affected by this problem. Unfortunately, the server crashed during my vacation because of this. I would be nice to have a fix for this.

**Comment by froque** [comment]
I have version 9.5.5 and it is affected by this bug. This pull request seems OK, what is the delay for merging ?

**Comment by spelunker** [comment]
@solidnerd 
Steps to reproduce this issue:

1. Clone git repo.
``` bash
git clone https://github.com/sameersbn/docker-gitlab
cd docker-gitlab
```
2. Make dir for volumes and change permissions
``` bash
sudo mkdir -p /srv/docker/gitlab/redis
sudo mkdir -p /srv/docker/gitlab/postgresql
sudo mkdir -p /srv/docker/gitlab/gitlab
sudo chown your_name:your_group /srv/docker/gitlab
sudo chown your_name:your_group /srv/docker/gitlab/*
```
3. Docker compose up
``` bash
docker-compose up -d
```
4. After several minutes, check container names
``` bash
docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                   NAMES
0f54b8a1ec1b        sameersbn/gitlab:10.1.1      "/sbin/entrypoint...."   5 minutes ago       Up 5 minutes        443/tcp, 0.0.0.0:10022->22/tcp, 0.0.0.0:10080->80/tcp   dockergitlab_gitlab_1
7a9d8b8c37aa        sameersbn/postgresql:9.6-2   "/sbin/entrypoint.sh"    5 minutes ago       Up 5 minutes        5432/tcp                                                dockergitlab_postgresql_1
8cd4ab618e4b        sameersbn/redis:latest       "/sbin/entrypoint...."   5 minutes ago       Up 5 minutes        6379/tcp                                                dockergitlab_redis_1
```
5. Check cron table in gitlab container
``` bash
docker exec -it dockergitlab_gitlab_1 bash
root@0f54b8a1ec1b:/home/git/gitlab# crontab -u git -l
00 01 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
root@0f54b8a1ec1b:/home/git/gitlab# exit
```
6. Stop and start gitlab
``` bash
docker-compose stop
docker-compose start
```

7. ** After several minutes ** , re-check cron table in gitlab container
``` bash
docker exec -it dockergitlab_gitlab_1 bash
root@0f54b8a1ec1b:/home/git/gitlab# crontab -u git -l
00 01 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
00 01 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
root@0f54b8a1ec1b:/home/git/gitlab# exit
exit
```

**Comment by lyda** [comment]
Uh, yes. Please merge this. This is an important fix.

**Comment by yfoelling** [comment]
Is there anything i could add, so you would merge this @solidnerd ?
I‘m patching this fix manually after every upgrade.. It works and its used in production..

**Comment by solidnerd** [comment]
@yfoelling I think we can merge this. It would be in the next release `10.1.1-1`

**Comment by solidnerd** [comment]
It will be in `10.1.2`

**Pull request merged**
