### PR TITLE
Upgrade GitLab CE to 10.5.2

### PR DESCRIPTION
**Pull request by xNevo**
[https://about.gitlab.com/2018/02/27/gitlab-10-5-2-released/](https://about.gitlab.com/2018/02/27/gitlab-10-5-2-released/)

### CODE REVIEW

**Comment by masakij** [comment]
10.5.3 that contains security fixes was released.
https://about.gitlab.com/2018/03/06/security-10-5-3-plus-10-4-5-plus-10-3-8-1st-blog-post/

**Comment by ppcat** [comment]
10.5.4 was released.
https://about.gitlab.com/2018/03/09/gitlab-10-5-4-released/

**Comment by Ilya-Kuchaev** [comment]
@sameersbn @solidnerd Any news?

**Comment by GJRTimmer** [comment]
@sameersbn @solidnerd Any idea when this will be merged ?

**Comment by solidnerd** [comment]
LGTM !

**Pull request merged**
