### PR TITLE
generic_oauth variable name for automatic authentication

### PR DESCRIPTION
**Pull request by tom-dierckx**
Fix for Issue => https://github.com/sameersbn/docker-gitlab/issues/2125

### CODE REVIEW

**Comment by jorikseldeslachts** [comment]
Very nice fix! We are also very interested in this. I hope this gets merged soon! Cheers!

**Comment by sameersbn** [comment]
@tom-dierckx could you please document this option in the README? Thanks for the contribution and sorry about the delay

**Comment by tom-dierckx** [comment]
@sameersbn this should actually be included in the documentation of the omniauth package documentation in the gitlab docs (there is a reference to this in the README.md). I just removed the limitation that made using the oauth2_generic authentication with a different name impossible.

**Comment by sameersbn** [comment]
@tom-dierckx thanks for the clarification.

**Pull request merged**
