### PR TITLE
Updates to Gitlab 8.0.0

### PR DESCRIPTION
**Pull request by cuva**
This PR updates to docker 8.0.0.

`gitlab-shell`'s version hasn't been updated.

screen shot 2015-09-22 at 11 00 33 pm

### CODE REVIEW

**Comment by obi12341** [comment]
+1

**Comment by Allineer** [comment]
How about the [gitlab-git-http-server](https://gitlab.com/gitlab-org/gitlab-ce/blob/v8.0.0/doc/update/7.14-to-8.0.md#5-install-gitlab-git-http-server)?

**Comment by sameersbn** [comment]
I am working on the update to version `8.0.0` (actually its ready). A couple of changes have occurred in gitlab in this update including unification of gitlab-ce and gitlab-ci. I have made the required updates locally. However since existing `gitlab-ci` users would need to migrate to gitlab, I am working on some migration bits that hopefully will make the process simple.

Since I don't wan't your setup to break and so that you have a pleasant migration I have held back the update until I have this all figured and tested. This may take a couple of days so please bear.

**Comment by ivlis** [comment]
@Allineer now gitlab is using RoR, python, node.js and Go. What is next Rust, Erlang, Haskel, probably Basic?

**Comment by Allineer** [comment]
@ilvis, I'm not a GitLab developer.

**Comment by obi12341** [comment]
@ivlis this is not a bashing thread

**Comment by sameersbn** [comment]
GitLab Inc. is only interested in making their software better. There is no point complaining on the programming language choices they make as long as it is makes the software as a whole better.

And the beauty of using docker containers is that you don't have to bother what makes up the container as long as you have a functioning instance up and running in minutes.

btw, i don't think @ivlis is complaining, he/she is simply making an observation that they find interesting/funny for whatever reason :smile:

**Comment by okaufmann** [comment]
When will you release the docker-version for Gitlab 8.0.0 circa ?

**Comment by devinrsmith** [comment]
https://about.gitlab.com/2015/09/22/gitlab-8-dot-0-dot-1-released/

That was fast!

**Comment by sameersbn** [comment]
Upgrade should land by friday latest. Have all the bits working. Need to test all use cases and write a migration guide. Shall close this thread once the release is made.

**Comment by athieriot** [comment]
Thanks for all your hard work @sameersbn :)

**Comment by obi12341** [comment]
yeah :+1:  for that

**Comment by thiagoalmeidasa** [comment]
Man, just for notice you:
https://gitlab.com/gitlab-org/gitlab-ce/issues/2688

'I believe this is fixed by !1396 which has been merged and will go into the 8.0.2 patch release.'

**Comment by sameersbn** [comment]
@thiagoalmeidasa it does not effect this image as it is not based on omnibus. I have reply by email working just fine :smile:

**Comment by thiagoalmeidasa** [comment]
@sameersbn sorry man, my mistake.
I'm waiting your image to update my env. Thanks

**Comment by sameersbn** [comment]
don't worry about it. Just have a little patience for the release. Besides, since this release has some major changes I expect some quick releases from gitlab that fix issue with the 8.0.0 release. The longer you wait the better will be the stability of the release :smile:

**Comment by utrack** [comment]
Thanks for the hard work  :+1: :smile:

**Comment by sameersbn** [comment]
Making release for `8.0.0`. Release `8.0.1` has no code changes. Only some updates in the docs. So I will hold on to the `8.0.1` allowing me to address issues users may face while using the `8.0.0` release

**Comment by obi12341** [comment]
:+1: thanks for your effort :)

**Comment by xiemeilong** [comment]
:+1:

**Comment by thiagoalmeidasa** [comment]
:thumbsup:

**Pull request closed without merging**
