### PR TITLE
GitLab CE 10.0.3

### PR DESCRIPTION
**Pull request by evenh**
I saw that the [v10.0.3](https://gitlab.com/gitlab-org/gitlab-ce/tags/v10.0.3) now exists, so hopefully this PR will pass Travis :-)

### CODE REVIEW

**Comment by solidnerd** [comment]
LGTM !

**Comment by phenomax** [comment]
LGTM!

**Comment by evenh** [comment]
Official blog post at https://about.gitlab.com/2017/10/05/gitlab-10-dot-0-dot-3-released/

**Comment by cobbdesigngroup** [comment]
It looks like it's too early to upgrade yet from 9.5.5, too many fix releases in just one week.

**Comment by phenomax** [comment]
@solidnerd Is anything missing?

**Comment by solidnerd** [comment]
@phenomax nothing 😅 . My last days were a little bit stressful so I forget that . I will release it in the next few hours.

**Comment by phenomax** [comment]
@solidnerd Could you then please do as you told :D

**Pull request merged**
