### PR TITLE
WIP Add ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by solidnerd**
Hey @sameersbn,
I added a Issue template to make easier to predefine what we need to know in the case our help is needed.

### CODE REVIEW

**Comment by splattael** [comment]
I like the idea! :+1: 

Don't forget that it's Markdown (`.md`) after all so want to use Markdown carefully.
Currently, every "point" would be a `h1`, wouldn't be?

I searched for some other issue templates on GitHub and [docker's](https://github.com/docker/docker/blob/master/.github/ISSUE_TEMPLATE.md) quite nice. Maybe, you can steal and tweak it? :smile:

**Comment by solidnerd** [comment]
Ups 😅 . 
I will refactor it later today. Yeah you are right the template from docker is quietly nice.

**Comment by sameersbn** [comment]
LGTM!

**Comment by sameersbn** [comment]
I think we should just steal the one from  the docker repo. It includes everyrthing we should need.

**Comment by sameersbn** [comment]
@solidnerd @splattael i've amended some commits to the PR. Please review as time permits.
Thanks for your great contributions.

**Pull request closed without merging**
