### PR TITLE
refs #2549: Install git from gitaly

### PR DESCRIPTION
**Pull request by paolomainardi**
Installing git as explained here: https://docs.gitlab.com/ee/install/installation.html#git

the idea is to use the gif client bundled with Gitaly and not the one provided by the distro

### CODE REVIEW

**Comment by paolomainardi** [comment]
@sachilles it seems that it is just failed for some technical reasons on CircleCI

**Comment by sachilles** [comment]
@paolomainardi I restarted the pipeline.

**Comment by paolomainardi** [comment]
Thanks @sachilles

**Comment by gjrtimmer** [comment]
Can someone please merge this one, because 14.10 is broken due to the mentioned issue.

**Comment by gjrtimmer** [comment]
@sameersbn please merge

**Comment by sachilles** [comment]
Hi, I'll merge your PR. However

**Comment by gjrtimmer** [comment]
@sachilles | Confirmed, this MR fixes #2549, this also fixes the problem with the commitGraph problem because its now finally using the shipped (gitlab) correct/patched git version.

@sachilles Please push this MR all the way to the container repository and use it to overwrite version `14.10.0` so that this version container will start working again. A lot of people have problem with `14.10.0` because of this. Please overwrite the container in the container registry with a version of `14.10.0` that include this MR request.

Thank you very much.

**Pull request merged**
