### PR TITLE
Segregate nginx to a separate container

### PR DESCRIPTION
**Pull request by ivlis**
Following isolation principles of docker the nginx process is moved to a separate
container, instead running in the gitlab container. The nginx container uses an
official nginx image. The configuration scripts detects if an nginx container is
linked and does not start nginx inside the gitlab container in that case. If no
nginx container is detected the script works as normal.

Important changes:
* The gitlab-workhorse socket is moved to a more reasonable location
* Variable `NGINX_USE_EXTERNAL`. If true, the gitlab container does not start
  an nginx process, even if an nginx container is not detected. Useful if one have
  an nginx process outside of docker-compose

### CODE REVIEW

**Comment by veggiemonk** [comment]
Nice! 

> The configuration scripts detects if an nginx container is
linked and does not start nginx inside the gitlab container in that case. If no
nginx container is detected the script works as normal.

This is so convenient! Thanks a lot.

**Comment by ivlis** [comment]
#521 blocks this. It is better to wait till it will be fixed in the upstream gitlab-workhorse project. It is not possible to configure unicorn (or I don't know how) to open a socket at a location other from `tmp/sockets` and I don't want to mess with symlinks.

BTW, why not allow nginx to serve static files directly, comes as a great mystery to me.

**Comment by sameersbn** [comment]
@ivlis when using relative_urls gitlab rebuilds some of the assets to correct the urls. serving users the static assets using nginx would result in broken links for users who choose to use relative urls. when not in use, it is perfectly fine for nginx to serve these prebuilt assets.

Also I would like to mention that recently there has been a lot of activity in GitLab with regards to handing of http requests, wherein they are working towards offloading all http request handling to `gitlab-workhorse`. I believe that when this transition is complete nginx will become completely optional at which point we might would be able to drop it from the image altogether.

Given this development activity, I think we should avoid merging this change in the image, because with every release things will start breaking on the http request handling front and during this time it is best to stick with how gitlab inc. recommends installing Gitlab and finally make the transition when things are ready.  See "Decoupling GitLab from NGINX" section of [GitLab 8.3.0 Release Announcement](https://about.gitlab.com/2015/12/22/gitlab-8-3-released/)

**Comment by MeinAccount** [comment]
What is the current state about separating Nginx? [All requests are handled by `gitlab-workhorse` these days.](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/support/nginx/gitlab)

**Comment by ngpestelos** [comment]
Can we close this PR? @ivlis @sameersbn

**Comment by SolidNerd** [comment]
In my opinion we can close this, because we got #794 . And you don't need to communictae with nginx you can communicate with gitlab workhorse over `8181` that is possible since #793 .

**Comment by SolidNerd** [comment]
I will close this now because we got #794 and a schedule for it.

**Pull request closed without merging**
