### PR TITLE
Update to Gitlab 8.16.4

### PR DESCRIPTION
**Pull request by iamchanghyunpark**
Updated the build to 8.16.4

[8.16.4](https://about.gitlab.com/2017/02/02/gitlab-8-dot-16-dot-4-released/) introduces bug fixes.

Signed-off-by: Chang Hyun Park <heartinpiece@gmail.com>

### CODE REVIEW

**Comment by iamchanghyunpark** [comment]
Succesful build and run.

You may check if the build runs properly from [here](https://hub.docker.com/r/heartinpiece/gitlab/tags/)
image

**Comment by phenomax** [comment]
Seems fine to me... LGTM? @solidnerd @sameersbn

**Comment by Ilya-Kuchaev** [comment]
Any news here?

**Comment by solidnerd** [comment]
I will release it tonight.

Am 08.02.2017 7:18 nachm. schrieb "Kuchaev Ilya" <notifications@github.com>:

**Pull request merged**
