### PR TITLE
upgrade Gitlab CE to 13.7.4

### PR DESCRIPTION
**Pull request by bjf893**
https://about.gitlab.com/releases/2021/01/14/critical-security-release-gitlab-13-7-4-released/

@solidnerd security release

### CODE REVIEW

**Comment by lenovouser** [comment]
@solidnerd @sameersbn ping, this is a security release 😢

**Comment by lenovouser** [comment]
Maybe some other people can get merge permission so that security releases can get merged more quickly?

**Comment by f-io** [comment]
https://github.com/sameersbn/docker-gitlab/pull/2246#issuecomment-723303926

**Comment by solidnerd** [comment]
Hey @lenovouser,
I'm open to have more collaborators on board. The only problem that I got is that I don't have access to enable this for one.

**Pull request merged**
