### PR TITLE
Upgrade to 11.7.3

### PR DESCRIPTION
**Pull request by greyferret**

### CODE REVIEW

**Comment by solidnerd** [comment]
Hey, 

I think we should ship `11.7.1` and `11.7.2` because they weren't released while they got problems in the QA.

**Comment by greyferret** [comment]
@solidnerd Ok, I deleted 11.7.1 and 11.7.2

**Comment by leslau** [comment]
Can someone merge this plz, thats some security issues that's fixed in this version!

**Comment by pieterlange** [comment]
11.7.1 and 11.7.2 were never released to the public upstream either so i guess we can consider those internal project numbers? Just :shipit: ?

**Pull request merged**
