### PR TITLE
Upgrade GitLab CE to 15.1.0

### PR DESCRIPTION
**Pull request by sachilles**
GitLab Release: 15.1.0 (see <https://about.gitlab.com/releases/2022/06/22/gitlab-15-1-released/>)

### CODE REVIEW

**Comment by kkimurak** [comment]
Hmm the build fails with 

````sh
rake aborted!
ERROR: This installation of GitLab uses unsupported database names in 'config/database.yml': geo. The only supported ones are main, ci.
````

This is happen because [`geo` entry is exist on `config/database.yml.example.postgresql` of upstream source](https://gitlab.com/gitlab-org/gitlab/-/blob/4bff2971fa4640f7e9d844be4308070579eca005/config/database.yml.postgresql).  
To pass temporally, we need to delete it after [copying this as `database.yml`](https://github.com/sameersbn/docker-gitlab/blob/master/assets/build/install.sh#L187-L190) or have different approach.  

@sachilles Do you have any idea ?

**Comment by sachilles** [comment]
I think the temporary workaround you suggest is the simplest solution. (However, we should include a note in the installation script).

**Comment by sachilles** [comment]
We should perhaps include the configuration file in our repo below `assets/build` (e.g. as `assets/build/config/database.yml.postgresql`). 

This would then be a copy from the upstream repo, just without the `geo` entry.

**Comment by kkimurak** [comment]
OK build succeed. but let me remind you what #2580 was for :)

**Comment by sachilles** [comment]
Thanks, I'll check if I did a rebase or not. In any case, I guess including PRs #2579, #2580, and #2594 would be fine.

Probably, I should create an additional branch for version `15.0.x-stable`(or just `15.0.x`) the backport changes arising in version `15.1.x`. This is similar to the redmine repo (see <https://github.com/sameersbn/docker-redmine/>).

What do you think?

**Comment by kkimurak** [comment]
@sachilles I find it difficult to patch past versions on multiple branches and provide a fixed version. Even if we have only one release branch, we are still providing releases with bugs and stale configs. 

Above all, I'm worried that the job will be a burden to the maintainer and that you are the only active maintainer. I apologize for not being able to make any further efforts. I can still contribute, but I can't be a maintainer.

**Pull request merged**
