### PR TITLE
Upgrade to 8.16.6

### PR DESCRIPTION
**Pull request by iamchanghyunpark**
Upgrade to 8.16.6, changelog [gitlab-blog](https://about.gitlab.com/2017/02/17/gitlab-8-dot-16-dot-6-released/)
Looks like bug fixes.

Building: Successful [Docker hub](https://hub.docker.com/r/heartinpiece/gitlab/tags/)
Deploying(Test): Successful
image

Signed-off-by: Chang Hyun Park <heartinpiece@gmail.com>

### CODE REVIEW

**Comment by Ilya-Kuchaev** [comment]
Any news here?

**Comment by iamchanghyunpark** [comment]
@Ilya-Kuchaev Not sure...
FYI Gitlab should be releasing the 8.17.0 on the 22nd.
Not sure what'll happen to this PR

**Comment by solidnerd** [comment]
Hey,

**Comment by solidnerd** [comment]
LGTM !

**Pull request merged**
