### PR TITLE
[WIP] Upgrade GitLab to 10.3.4

### PR DESCRIPTION
**Pull request by solidnerd**

### CODE REVIEW

**Comment by pieterlange** [comment]
ping @solidnerd

**Comment by yuankunzhang** [comment]
Waiting for this PR to be merged.

**Comment by balajidl** [comment]
I am also waiting.

**Comment by torvitas** [comment]
Does someone use this branch already?

**Comment by pieterlange** [comment]
Yes, i built my own image for this

**Comment by pieterlange** [comment]
Thanks @solidnerd!

**Comment by solidnerd** [comment]
@pieterlange No problem. I got sick the last days this was the cause that it takes so long. I already released 10.3.5 ;)

**Pull request merged**
