### PR TITLE
add GITLAB_PORT_EXT, to cover cases where GITLAB_PORT is actually not the port the service is being accessed from

### PR DESCRIPTION
**Pull request by neta79**
This is necessary in those cases where GITLAB_PORT differs from the port used by a load balancer or proxy to publish the service to the outside world. Without this mapping GitLab generates wrong backlinks to itself.

### CODE REVIEW

**Comment by solidnerd** [comment]
This is not needed I you want to talk directly to gitlab-workhorse expose `8181` and let you load balancer handle it.

**Comment by monkeydri** [comment]
@solidnerd could you elaborate please ?

I run this docker-gitlab behind a nginx reverse-proxy (linuxserver/letsencrypt docker) so only 443 is exposed on host.

The thing is internally the port used by the gitlab instance for http is sometimes appended to the images URLs (therefore the images are not displayed because this port is not opened on host).

**Comment by neta79** [comment]
@solidnerd 
@monkeydri described precisely our same scenario. 
Gitlab generates urls with the only port info it is aware of. 
In our case, this patch keeps being essential to avoid occasional bad urls. 

Please reconsider merging.

**Comment by solidnerd** [comment]
@monkeydri @neta79  You don't need this. What you can do is to that the `GITLAB_PORT` and it will solve your problems. I also run GitLab behind a proxy and it's works for me.

**Pull request closed without merging**
