### PR TITLE
Upgrade GitLab CE to 13.2.1

### PR DESCRIPTION
**Pull request by cwildfoerster**
Tested on a fresh system, as well on my current installation (13.0.7, docker registry and working ci).

An update to gitaly/config.toml was needed (https://gitlab.com/gitlab-org/gitaly/-/issues/2981) and the gitaly patch from @solidnerd needed an update too because the to-be-patched file was changed.

Skipped version 13.1 entirly, because it is already superseded and just gotten to work on it today, sorry. But as stated by @solidnerd https://github.com/sameersbn/docker-gitlab/issues/2174#issuecomment-643576947 this shouldn't be a problem.

Should work in all cases, but maybe someone else should throw a test in, but create a backup first... also copy your files with all permissions (`copy -a`)... learn from my mistakes ;)

### CODE REVIEW

**Comment by walkerlee** [comment]
There are some image version error (gitlab:13.2.0 => gitlab:13.2.1) in README.me

**Comment by cwildfoerster** [comment]
> There are some image version error (gitlab:13.2.0 => gitlab:13.2.1) in README.me

Yes, you're right, sorry, will fix it later today.

**Comment by amarCosmospace** [comment]
hi, i'm getting this error, "Internal API unreachable" when creating a snippet or pushing to a repo. i used your files and upgraded from 13.0.7

**Comment by cwildfoerster** [comment]
> hi, i'm getting this error, "Internal API unreachable" when creating a snippet or pushing to a repo. i used your files and upgraded from 13.0.7
> 
> EDIT: it seems that this socket dosent exist in the container
> `gitlab-workhorse.socket`

Okay, let me check my installation...

**Comment by cwildfoerster** [comment]
> hi, i'm getting this error, "Internal API unreachable" when creating a snippet or pushing to a repo. i used your files and upgraded from 13.0.7
> 
> EDIT: it seems that this socket dosent exist in the container
> `gitlab-workhorse.socket`

Okay, fixed with https://github.com/sameersbn/docker-gitlab/pull/2197/commits/b6e518cd900f4d68368fbac0bc08ec8df7fc8150 . I just copied the configuration from the example because i thought the socket was the default, but it wasn't and somehow i didn't noticed it. I can now push and create snippets etc. again. Thank you for your testing.

**Comment by amarCosmospace** [comment]
You are welcome, good job 👍

**Comment by solidnerd** [comment]
Hey at all,
I'm planning to review it today and my plan will be merge it over the weekend. So that we are back in in the game ;)

**Comment by f3l1x** [comment]
Thank you @cwildfoerster for PR and @solidnerd for review. We're are looking forward to test it. :-)

**Comment by martinspaeth** [comment]
Hey @solidnerd great new to see the repo catching up! Is this fix (https://github.com/sameersbn/docker-gitlab/issues/2155) 
 for the pages deamon part of the merge marathon or is it  no longer relevant for 13.2.1?

**Comment by cwildfoerster** [comment]
> Hey @solidnerd great new to see the repo catching up! Is this fix (#2155)
> for the pages deamon part of the merge marathon or is it no longer relevant for 13.2.1?

I guess https://github.com/sameersbn/docker-gitlab/pull/2177 must still be merged. I currently don't use pages, so can't speak for that issue.

**Comment by solidnerd** [comment]
Thanks for your awesome work @cwildfoerster also all others in pr :+1:

**Pull request merged**
