### PR TITLE
11.11.3

### PR DESCRIPTION
**Pull request by drujd**
I have also updated golang (GitLab team runs tests using 1.12 since April)

### CODE REVIEW

**Comment by illusi0nary** [comment]
I like it, was about to do it myself, thanks for saving me time.

**Comment by paolomainardi** [comment]
@solidnerd can this MR be merged soon ?

**Comment by paddy-hack** [comment]
Please merge because 11.11.2 has an [issue restoring from backup](https://gitlab.com/gitlab-org/gitlab-ce/issues/63279).  I've used this branch to [work around restoring from my 11.11.2 backups](https://gitlab.com/gitlab-org/gitlab-ce/issues/63279#note_181966705).

**Comment by solidnerd** [comment]
LGTM ! I had not so much time for the last week. So here we go.

**Pull request merged**
