### PR TITLE
Update gitlab CE to v10.4.4

### PR DESCRIPTION
**Pull request by jdongelmans**
Fixes https://github.com/sameersbn/docker-gitlab/issues/1508

### CODE REVIEW

**Comment by lordvlad** [comment]
:+1:

**Comment by QuickJack** [comment]
Please merge this before switching to 10.5.x

**Comment by cwildfoerster** [comment]
lgtm @solidnerd @sameersbn

**Comment by solidnerd** [comment]
Hey @jdongelmans,

I'm back from busy week. Could you fix your merge conflicts to that we could take this as a next release. It will be the last one for 10.4.X . If you need help with this let me know.

**Comment by solidnerd** [comment]
I created an PR with the update in #1523 . I hope it's okay.

**Pull request closed without merging**
