### PR TITLE
Upgrade to 11.11.1

### PR DESCRIPTION
**Pull request by drubin**
[Changelog](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.11.1/CHANGELOG.md)
[GITALY_SERVER_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.11.1/GITALY_SERVER_VERSION)  1.42.2
[GITLAB_WORKHORSE_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.11.1/GITLAB_WORKHORSE_VERSION)  not changed
[GITLAB_SHELL_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.11.1/GITLAB_SHELL_VERSION) not changed
[GITLAB_PAGES_VERSION](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.11.01/GITLAB_PAGES_VERSION)  not changed.

### CODE REVIEW

**Comment by drubin** [comment]
@solidnerd ping.

**Comment by drujd** [comment]
11.11.2 is out

**Comment by drujd** [comment]
Also, you have not updated gitaly server version

**Comment by drubin** [comment]
@drujd thanks! updated the gitaly version, also submitted a PR for 11.11.2

**Comment by solidnerd** [comment]
LGTM !

**Pull request merged**
