### PR TITLE
Upgrade instructions from Postgresql 12 to 14

### PR DESCRIPTION
**Pull request by froque**
Postgres 15 has a permissions problem.
See https://github.com/sameersbn/docker-postgresql/issues/168

### CODE REVIEW

**Comment by kkimurak** [comment]
Test seems fail because of refused connection but there seems to be no problem with the gitlab container. In the test, `docker ps` is executed after `docker compose up`, but at this point the state of the `sameersbn/postgresql` container is ["Restarting (1) Less than a second ago"](https://app.circleci.com/pipelines/github/sameersbn/docker-gitlab/1314/workflows/3c0fd7b4-c955-451c-bdc7-148a254b562e/jobs/6149?invite=true#step-106-714_177), and it may be stuck in a restart loop.

 Local test on my environment (to follow circle ci step) worked - web interface open, login and creating new blank project succeed.  

Could you please try restarting CI (by rebase and force-push, or something else)?

**Comment by froque** [comment]
@kkimurak postgres 14 was failling in circle ci with
```
[33mpostgresql_1  |[0m popen failure: Cannot allocate memory
[33mpostgresql_1  |[0m initdb: error: The program "postgres" is needed by initdb but was not found in the
[33mpostgresql_1  |[0m same directory as "/usr/lib/postgresql/14/bin/initdb".
```

upgrading to latest ubuntu resolves the problem
https://stackoverflow.com/a/77078191/3929185

**Comment by kkimurak** [comment]
@froque Ok build passed. Thank you for your work.  
Please so be kind to wait for maintainer review,

**Comment by sachilles** [comment]
Hi,

regarding this PR I'd like to clarify some things.

> Postgres 15 has a permissions problem. See [sameersbn/docker-postgresql#168](https://github.com/sameersbn/docker-postgresql/issues/168)

Since I'm running GitLab from this repo with PostgreSQL 15.4, I can't confirm that PostgreSQL has some issues. However, it's a long time ago that I had to restore from backup.

**Review by sachilles — APPROVED** [review]
LGTM

**Pull request merged**
