### PR TITLE
add AWS_BACKUPS to configure automatic backups to S3

### PR DESCRIPTION
**Pull request by colinbrownec**
Enables use of GitLab integration with Fog to automatically push backups to an S3 bucket.

I noticed there is another [open pull request](https://github.com/sameersbn/docker-gitlab/pull/268) doing this same feature, this setup is much simpler.

I just realized now that Fog supports multiple providers, but I'm not sure how to support complete configuration through environment variables without writing a lot more code.

I've tested this on a production git server and it works with both `app:rake` backups as well as automatic backups. It also disables this behavior when `AWS_BACKUPS=false`

### CODE REVIEW

**Comment by sameersbn** [comment]
@colinbrownec do you think it would be a better idea to automatically set `AWS_BACKUPS` to `true` when the required parameters are configured, so as to avoid broken configurations?

**Comment by sameersbn** [comment]
@colinbrownec basically we check if `AWS_BACKUP_REGION`, `AWS_BACKUP_ACCESS_KEY_ID`, `AWS_BACKUP_SECRET_ACCESS_KEY` and `AWS_BACKUP_BUCKET` are not empty before enabling AWS backups.

**Comment by colinbrownec** [comment]
@sameersbn I agree. But if not all parameters are valid, should it exit? I see two options;
1. print error message, disable aws, continue
2. print error message, exit

I guess I'm more for 2. since if you have some aws parameters, you were probably trying to use aws

**Comment by sameersbn** [comment]
@colinbrownec I think you can keep the `AWS_BACKUPS` option. But if it is not specified, then it should be enabled automatically if all the four parameters are defined. If it has been enabled by the user, but if any of the four parameters are not defined, the we display a message that says something like "Cannot enable AWS backups. Invalid configuration.", disable AWS backups and continue without exiting.

**Comment by sameersbn** [comment]
@colinbrownec somewhat (not entirBut unlike the case of AWS, ely) similar to `SMTP_ENABLED` configuration. `SMTP_ENABLED` is automatically set to true if SMTP_USER is specified. However `SMTP_ENABLED` can be manually enabled by the user without specifying the `SMTP_USER` which is not the case for `AWS_BACKUPS`. 

`AWS_BACKUPS` has to have the four parameters. I agree with your "2. since if you have some aws parameters, you were probably trying to use aws", but it you would have to carefully craft the code to make sure if `AWS_BACKUPS` was enabled automatically or by the user.

**Comment by sameersbn** [comment]
@colinbrownec In case of OAUTH support if the user does not specify all oauth parameters. I will just not enable oauth and continue. Here the difference it that the user can tell that oauth has not been enabled by looking at the login screen. In case of aws backups this is not the case. So your right, if `AWS_BACKUPS` cannot be enabled when the user was trying to enable it, its best to error out.

**Comment by sameersbn** [comment]
@colinbrownec Lets just keep it simple. If you current PR, add a check to make sure if the four parameters are defined. If not, print error message and exit

**Comment by sameersbn** [comment]
@colinbrownec ps. post a comment here after you update the PR so that i am notified. thanks

**Comment by colinbrownec** [comment]
new code aborts if `AWS_BACKUPS=true` but options are incomplete. I also like this way since you can disable AWS without deleting configuration information.

**Comment by sameersbn** [comment]
Hi. I will test and merge on Monday. Traveling at the moment. Thanks.

**Pull request merged**
