### PR TITLE
Escaping timezone environment variable due use of slashes causing sed error

### PR DESCRIPTION
**Pull request by urquilla**
Proposal for issue #342

Allows entering timezone environment variable without thinking about internal parsing in assets/init

### CODE REVIEW

**Comment by thomasleveil** [comment]
:+1: nice move. Implementation details (the use of Bash and related escaping issues) should not leak up to the config. Why would anyone have to escape stuff in a environment variable value ?

**Comment by sameersbn** [comment]
@thomasleveil the `GITLAB_TIMEZONE` variable uses ruby TimeZone constants http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html. If you want to specify `Asia/Kolkata` as your timezone then you specify `GITLAB_TIMEZONE=Kolkata` as per the linked page.

I think this PR is not required unless ruby allows it.

**Comment by thomasleveil** [comment]
IMHO, it sucks a _user_ has to follow a web framework documentation addressed to _developpers_ to be able to set a timezone. Anyway see #352 to help future users to figure this out on their own ;)

**Comment by sameersbn** [comment]
@urquilla closing this PR. thanks!

**Pull request closed without merging**
