### PR TITLE
upgrade GitLab CE to 14.3.0

### PR DESCRIPTION
**Pull request by sachilles**
GitLab Release: 14.3.0 (see https://about.gitlab.com/releases/2021/09/22/gitlab-14-3-released/)

### CODE REVIEW

**Comment by kkimurak** [comment]
Also, I remembered that build has fail during compiling `gitlab-shell`. We need to add trick for `install.sh` as I suggested in https://github.com/sameersbn/docker-gitlab/pull/2425#discussion_r728476081

**Comment by sachilles** [comment]
Oh my god, this is getting embarrassing. If I hadn't already tested this separately... Now let's keep fingers crossed.

**Comment by sachilles** [comment]
If the build works, I will create a PR for Gitlab 14.3.1 right afterwards. The corresponding branch is already prepared.

**Comment by sachilles** [comment]
@sameersbn Could you be so kind to publish the Docker images so that the release can be published?

**Pull request merged**
