### PR TITLE
Upgrade GitLab to 10.1.0

### PR DESCRIPTION
**Pull request by solidnerd**

### CODE REVIEW

**Comment by cwildfoerster** [comment]
Whats missing?

**Comment by solidnerd** [comment]
All new configuration changes. I will work on it tomorrow. Hopefully I can ship it than.

**Comment by ovr** [comment]
@solidnerd Please cherry-pick 90dbcf2 from @LordFPL because without it `Gitaly` `v0.43` will not work inside CI, clone will fail inside CI

**Comment by fmauNeko** [comment]
It isn't enough to get Gitaly working, the Makefile is apparently looking for git to get the version now, same as gitlab-pages.
I've tried doing the same thing as e025be7 for Gitaly, and it seems to build correctly, will update after doing some testing.

**Comment by fmauNeko** [comment]
Apparently they thought it was a good idea to unexport `$GOROOT` in the Makefile.
https://gitlab.com/gitlab-org/gitaly/blame/v0.43.0/Makefile#L20

**Comment by solidnerd** [comment]
@ovr I tested this commit on a build. I will gonna merge them before I release 10.1.0. Thanks for pointing this out.

@fmauNeko I cherry-picked your commit in https://github.com/sameersbn/docker-gitlab/pull/1387/commits/3fc8424bbae24b0befdb74f4b70fa9b313f6eab8 . Thanks for work.

For everyone I will start with the release. Thanks for your patient.

**Pull request merged**
