### PR TITLE
Upgrade to Gitlab 9.3.1

### PR DESCRIPTION
**Pull request by abeltay**
https://about.gitlab.com/2017/06/27/gitlab-9-dot-3-dot-1-released/

### CODE REVIEW

**Comment by jostyee** [comment]
since 9.3 has been merged, this pr should be rebased and upgrade to the latest 9.3.3 version, which fixed a gitlab api major bug.

**Comment by abeltay** [comment]
I've rebased for 9.3.1, I think @solidnerd may prefer to release versions in order.

@solidnerd shall I bump this to 9.3.1 or 9.3.3?

**Comment by jostyee** [comment]
Both 9.3.1 and 9.3.2 are buggy, why bother tagging them?

**Comment by abeltay** [comment]
Okay, I've updated it to 9.3.3

**Comment by solidnerd** [comment]
@abeltay I prefer to have it in the release versions order. I would also like to have separate Pull Requests for a better overview of this.

@jostyee This could be important for some users. So that they have other issues that occures in the next patch version. When we bumping it up to the latest version we could not help this users. 

Another point is that I want personally to support the same gitlab version that are released by the upstream.

**Comment by abeltay** [comment]
I've reverted the changes to 9.3.1

**Comment by solidnerd** [comment]
@abeltay If you want you can prepare the other patches with PR's as well. I will gonna review them. When I back at home and probably release them today ;) .

**Comment by abeltay** [comment]
Done! 😄

**Comment by solidnerd** [comment]
I merged my version it was easier to resolve the conflics there but thanks for your work ;)

**Pull request closed without merging**
