### PR TITLE
added direct_upload to artifacts object storage

### PR DESCRIPTION
**Pull request by mlsmaycon**
Added direct_upload to artifacts object storage configuration block, this enables skiping local artifacts storage as described in the link https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/administration/job_artifacts.md#object-storage-settings , this is very useful with docker.

### CODE REVIEW

**Comment by JoeOrtiz** [comment]
Could this be allowed in? This is something we definitely need!

Thanks!

**Comment by GJRTimmer** [comment]
I need it too

**Comment by solidnerd** [comment]
Hey @mlsmaycon, 

could you rebase against master ? This is needed because wenn use circle ci now.

**Comment by GJRTimmer** [comment]
@solidnerd  I've just complete a test with a configuration against self-hosted Minio. Without this parameter the artifacts are not uploaded to S3.

@Solid I've have the same fix in my own fork, If you want I can create a PR which will also auto close this one. And the matching Issue.

**Comment by solidnerd** [comment]
@GJRTimmer Do you have example configuration with minio to test it ? So we can provide it other users that want to use this feature.

**Comment by GJRTimmer** [comment]
I can even do better, I've just finished what I call the ultimate personal Gitlab Instance. Fully tested.

# Gitlab:
- Redis
  - Database: 0 -> Gitlab
  - Database: 1 -> Registry Object Reference Store, I'm using the redis also for the registry because I'm also using minio as a S3 storage for my registry, I'm using the redis as the cache blob descriptor. And separating the dual usage of redis by assigning Gitlab to database: 0 and the registry to database:1.
- Postgresql
- Registry
- Secrets stored in separate file
- PlantUML
- 4x gitlab runners

# Minio Storage
Bucket: Gitlab
 
Subfolders:
* gitlab/artifacts (Artifacts stored by gitlab runners, confirmed working, **requires this PR**)
* gitlab/backups (Gitlab Backups stored here, tested and is working)
* gitlab/cache (From gitlab runners, tested and is working)
* gitlab/lfs (LFS Storage, tested and is working)
* gitlab/registry (Registry storage, including a configured direct link with the runners for faster storage, tested and working including fast uploading from a CI Job)
* gitlab/uploads (Gitlab uploads, tested and is working)
* gitlab/volumes (Currently working on it. Here I plan to storage entire backups of a docker volume, to clone an entire volume just before I run a upgrade of the gitlab server)
  
Nice to note is that I even got every subfolder working within the bucket.

Got the entire thing running on my Synology including a full configuration behind the Synology master Nginx. Configuration of the Synology might be out of scope but I'm of course willing to share.

I've been running Gitlab on my synology for several years now. Just finished a complete fresh redesign and reconfiguration of my setup.

@solidnerd BTW, I have no idea why the Circle-CI did not pass. Any thoughts ?

**Comment by GJRTimmer** [comment]
BTW I'm planning to write an entire article about it, to help people step by step. The Ultimate GitLab Docker setup.

**Comment by mlsmaycon** [comment]
Guys let me know if I should rebase this PR.

**Comment by solidnerd** [comment]
@mlsmaycon  Jep a rebase would be fine

**Comment by GJRTimmer** [comment]
@mlsmaycon Please do, then the other one from me can be closed, I don't seem to get a full pass on circle CI.

**Comment by mlsmaycon** [comment]
I am running some local tests to see whats going on with CI.

**Comment by mlsmaycon** [comment]
@solidnerd Can you help me with the problem I am facing  while testing the built container:

image

**Comment by mlsmaycon** [comment]
Found my mistake, it was missing one more line to remove on SED command. It should build now and run the remaining tests

**Comment by GJRTimmer** [comment]
@solidnerd request to merge.

**Comment by solidnerd** [comment]
@mlsmaycon could you also squash your commits ? Afterwards it looks okay for me.

**Comment by solidnerd** [comment]
LGTM !

**Comment by solidnerd** [comment]
I will put it on master so it will live in the latest tag.

**Pull request merged**
