### PR TITLE
Update gitlab CE to 11.0.2

### PR DESCRIPTION
**Pull request by pieterlange**
Also updates go to 1.10.3

### CODE REVIEW

**Comment by pieterlange** [comment]
Ref https://about.gitlab.com/2018/06/27/gitlab-11-0-2-released/

**Comment by reynold-lariza** [comment]
Is it just me or when I build with 11.0.2 and 11.0.1 even?

It just fails to build no matter how many times I tried :(

what could I be missing?

11.0.2 build error
```
/home/git/gitlab/node_modules/.bin/webpack --config /home/git/gitlab/config/webpack.config.js --bail
rake aborted!
Command failed with status (): [/home/git/gitlab/node_modules/.bin/webpack...]
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/webpack-rails-0.9.10/lib/tasks/webpack.rake:17:in `block (2 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => gitlab:assets:compile => webpack:compile
(See full trace by running task with --trace)
The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 1
ERROR: Job failed: exit status 1
```

11.0.1 build error
```
/home/git/gitlab/node_modules/.bin/webpack --config /home/git/gitlab/config/webpack.config.js --bail
rake aborted!
Command failed with status (): [/home/git/gitlab/node_modules/.bin/webpack...]
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/webpack-rails-0.9.10/lib/tasks/webpack.rake:17:in `block (2 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => gitlab:assets:compile => webpack:compile
(See full trace by running task with --trace)
The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 1
ERROR: Job failed: execution took longer than 1h0m0s seconds
```

**Comment by tomislater** [comment]
I have not noticed errors like these.

**Comment by reynold-lariza** [comment]
I've updated to `10.8.5` for now, as this one build without a hitch :)

**Comment by pieterlange** [comment]
Build works for me, i'm already running it.  How did you try building this @reynold-lariza ?

**Comment by reynold-lariza** [comment]
Fixed it! Two things...

First, the duration for the build default timeout is set to 1h, but then the build is taking longer than it. That's why the timeout. So I set it to `2h` and it proceeded fine.

Second, the build was using official ubuntu xenial image. So I reverted to use the original `sameersbn/ubuntu:16.04.20180124`

Geez! :D

**Comment by lenovouser** [comment]
@solidnerd

**Comment by pieterlange** [comment]
@sameersbn @solidnerd i'm happy to help testing & merging these minor upgrades in the repo. This one has been lingering for 8 days now while the patch is relatively minor and should've just been :shipit:'ed :nerd_face:

**Comment by solidnerd** [comment]
Hey @pieterlange ,
sorry for waiting so long. I was the last 10 days on vacation. I think I will need to ensure that this goes a lot of faster in an easier way.

**Comment by solidnerd** [comment]
But,

LGTM !

**Comment by lenovouser** [comment]
No worries, my guess actually was that you were on vacation 😆 - can you merge `v11.0.3` too? (#1661)

We could maybe ask @sameersbn to add 1-2 more collaborators to ensure a smoother workflow in the future?

**Comment by solidnerd** [comment]
@lenovouser I'm Updating now a lot of stuff. `11.0.3` will also released.

**Pull request merged**
