### PR TITLE
Fix Auth0 config

### PR DESCRIPTION
**Pull request by JGrenier**
Hi, 

The configuration for Auth0 is not functional.

As per this documentation : https://docs.gitlab.com/ee/integration/auth0.html

```
gitlab_rails['omniauth_providers'] = [
  {
    "name" => "auth0",
    "args" => { client_id: 'YOUR_AUTH0_CLIENT_ID',
                client_secret: 'YOUR_AUTH0_CLIENT_SECRET',
                domain: 'YOUR_AUTH0_DOMAIN',
                scope: 'openid profile email'
              }
  }
]
```
where, actually the gitlab.yml template contains : 

```
 - { name: 'auth0',
          args: {
            client_id: '{{OAUTH_AUTH0_CLIENT_ID}}',
            client_secret: '{{OAUTH_AUTH0_CLIENT_SECRET}}',
            namespace: '{{OAUTH_AUTH0_DOMAIN}}' } }
```

scope and domain are missing and namespace can be remove.

with this changes, auht0 is working well for me .

Thanks in advance to review this PR.

### CODE REVIEW

**Comment by JGrenier** [comment]
Hello, 

Any chance to get this merge quickly ?

**Comment by solidnerd** [comment]
Hey @JGrenier, 

I think we could put in the next release and deploy it today.

**Comment by JGrenier** [comment]
This would be nice.

Thank you.

**Comment by JGrenier** [comment]
Any update please ? 

This is really a blocking issue.

**Comment by solidnerd** [comment]
Hey, 

I will create a new patch release to fix a change that doesn't happen. So i think we can bring your fix in `12.2.5-1`. Which should also deployed today.

**Comment by JGrenier** [comment]
thanks 👍

**Pull request merged**
