### PR TITLE
Updates to Gitlab 8.16.5

### PR DESCRIPTION
**Pull request by iamchanghyunpark**
Changelog at [Gitlab blog](https://about.gitlab.com/2017/02/15/gitlab-8-dot-16-dot-5-security-release/)

Build Successful: [Docker hub](https://hub.docker.com/r/heartinpiece/gitlab/tags/)
Successful Launch:
image

Signed-off-by: Chang Hyun Park <heartinpiece@gmail.com>

### CODE REVIEW

**Comment by pieterlange** [comment]
This is a security release: https://about.gitlab.com/2017/02/15/gitlab-8-dot-16-dot-5-security-release/

**Comment by solidnerd** [comment]
LGTM !

**Comment by guilhermesteinmuller** [comment]
is it merely a network issue?

sudo docker pull sameersbn/gitlab:8.16.5
Error response from daemon: manifest for sameersbn/gitlab:8.16.5 not found

**Comment by solidnerd** [comment]
Nope . It's currently not built on Docker Hub. Wait for it. ;) Here can you see the build state:
https://hub.docker.com/r/sameersbn/gitlab/builds/

**Pull request merged**
