### PR TITLE
Upgrade Gitlab CE to 14.9.3

### PR DESCRIPTION
**Pull request by kkimurak**
GitLab Patch Release: 14.9.3 (see https://about.gitlab.com/releases/2022/04/12/gitlab-14-9-3-released/)

Details:

- gitlab: upgrade CE to v14.9.3
- gitaly: upgrade to v14.9.3
- ubuntu: upgrade to focal-20220404

### CODE REVIEW

**Comment by sachilles** [comment]
@kkimurak I did restart the pipeline.

**Comment by sachilles** [comment]
Someone was quick... Could you please add the following additional changes?

- Could you update Ruby from version 2.7.5 to version 2.7.6?
- Could you update Go to version 1.17.9? Please note, that version 1.18.1 didn't work and I need to take a closer look at the corresponding error messages.

Thanks for your contribution.

**Comment by kkimurak** [comment]
@sachilles

- ruby 2.7.6 : I forgot to check for update. I have `cherry-pick`ed your commit [b242ebd](https://github.com/sachilles/docker-gitlab/commit/b242ebda4855d940a85dc5053f142a989d532b8a).
- go 1.17.9 : I have faced similar error with 1.18.1 but forgot to check 1.17.9. `chery-pick`ed your commit [4656e80](https://github.com/sachilles/docker-gitlab/commit/4656e8090b20f784df78699c4afcd20bfa64f153).

Well, I'd better check if anyone is already working on it before doing it..
Thank you for your work anyway.

**Review by sachilles — APPROVED** [review]
LGTM

**Pull request merged**
