### PR TITLE
Possibility to change the redis database number

### PR DESCRIPTION
**Pull request by SolidNerd**
This helps to set a custom redis database number. #674

### CODE REVIEW

**Comment by sameersbn** [comment]
@SolidNerd we need to define `{{REDIS_DB_NUMBER}}` in the `gitlab-shell/config.yml` too. https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/config/gitlab-shell/config.yml#L46

**Comment by SolidNerd** [comment]
@sameersbn done .

**Comment by sameersbn** [comment]
You need to perform the substitution for it as well. I thought you'd figure that one :smile: 

https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/functions#L1130-L1143

**Comment by SolidNerd** [comment]
Ooops 😄 . It's updated.

**Pull request merged**
