### PR TITLE
Upgrade 11.9.8

### PR DESCRIPTION
**Pull request by drubin**
Upgrades to 11.9.8 
https://about.gitlab.com/2019/04/11/gitlab-11-9-8-released/

### CODE REVIEW

**Comment by drubin** [comment]
References #1898 #1894

**Comment by drubin** [comment]
@solidnerd ping please...

**Comment by paolomainardi** [comment]
@solidnerd help us to help you :)

**Comment by solidnerd** [comment]
Sorry for the long waiting. Got a lot of stuff to do and hadn't so much time for OSS. I'll also pick here only the upgrade on the master branch.

**Pull request closed without merging**
