### PR TITLE
Rollback Ruby from v3.x to v2.7.7

### PR DESCRIPTION
**Pull request by kkimurak**
This PR reverts #2675 that upgraded Ruby to v3.x that gitlab does not support yet.  

In #2675, `RUBY_VERSION` written in gitlab-omnibus-builder/docker/VERSIONS is cited as the basis for the upgrade. It was a version of Ruby used to run omnibus-gitlab's build scripts, not the Ruby used to install gems or anything into the package.  
Reference: https://gitlab.com/gitlab-org/gitlab-omnibus-builder/-/merge_requests/237#note_1126063965

See #2698 for detail.

- Roll back to 364df4c81d966cebfd6858b9b85f40afae4a4ff4 (v2.7.6 -> v2.7.7)
  - Partially revert 8386b46009b849e6a220bb0c5596d5c8a29a5f7a (v3.0.4 -> v3.0.5)
  - Revert 988cb396fb484ef4b684469916dd654965fea6d5 (v2.7.7 -> v3.0.4)

Affected releases are: v15.8.0, all v15.7.x and v15.6.x (15.6.3 or later)

### CODE REVIEW

**Comment by kkimurak** [comment]
TODO: add entry to CHANGELOG

@sachilles Could you be so kind to check on this (and plan backporting, if needed)?

**Comment by sachilles** [comment]
I'm sorry I missed that. I didn't notice any abnormalities in my tests, so I had no reason to have doubts.

On the other hand, my tests don't cover all the features of GitLab, so problems could certainly arise.

@kkimurak I will look into testing this PR tonight and backporting it for the current versions.

**Review by sachilles — APPROVED** [review]
LGTM

**Comment by kkimurak** [comment]
Thank you!

**Comment by sachilles** [comment]
You're welcome.

**Comment by Floyddotnet** [comment]
i can confirm, after downgrading back to ruby 2.7.7, it works now as before. thank you very much.

**Pull request merged**
