### PR TITLE
Upgrade GitLab CE to 10.0.0

### PR DESCRIPTION
**Pull request by phenomax**
https://about.gitlab.com/2017/09/22/gitlab-10-0-released/

### CODE REVIEW

**Comment by martell** [comment]
@phenomax you have a lot of `10.0.0.0` instead of `10.0.0` changes in the README

**Comment by phenomax** [comment]
@martell Thanks for pointing that out!
Thanks to @evenh for resolving my conflicts. I'll merge our changes together.

@solidnerd I also checked all config files of GitLab 10.0 and everything seems up to date.

**Comment by evenh** [comment]
@phenomax: In commit cb7edf8 you upgrade to versions that are not specified [here](https://gitlab.com/gitlab-org/gitlab-ce/tree/v10.0.0). Where is the newer versions published?

**Comment by phenomax** [comment]
? I just corrected the version numbers.
See [here](https://gitlab.com/gitlab-org/gitlab-ce/blob/v10.0.0/GITLAB_WORKHORSE_VERSION) and [here)(https://gitlab.com/gitlab-org/gitlab-ce/blob/v10.0.0/GITALY_SERVER_VERSION)

**Comment by evenh** [comment]
Nevermind me, I just looked at the wrong commit :sweat_smile: Anyway, I think @solidnerd likes a neat and clean history, so it should probably be squashed down to 1 commit for upgrading to 10.0.0 and one commit for each version upgrade (a total of 3 commits)

**Comment by cwildfoerster** [comment]
Whats missing? Maybe we should directly upgrade to the just releases 10.0.1

**Comment by solidnerd** [comment]
@evenh You are right. I Like a clean history. @phenomax you should rebase
and Squash your commits.

At all currently I'm not able to release this, because im on vacation and
get no computer with me. I will start with Release when Im Back (monday
2.10) otherwise @sameersbn can handle this.

Am 24.09.2017 16:15 schrieb "Constantin" <notifications@github.com>:

**Comment by phenomax** [comment]
@solidnerd I got no time neither. No PC next to me till Wednesday :/

**Comment by evenh** [comment]
I’ll try and submit a cleaned up PR later this evening :-)

**Comment by evenh** [comment]
See #1358

**Comment by phenomax** [comment]
Closing this in favour of #1358

**Pull request closed without merging**
