### PR TITLE
Upgrade to 13.5.1

### PR DESCRIPTION
**Pull request by f-io**

### CODE REVIEW

**Comment by cwildfoerster** [comment]
Hi @f-io why bump redis/registry on patch release? Also 13.4.4 was released with pages 1.25.0, shell 13.7.0 and workhorse 8.46.0. Also on a personal note, i seem to know your fio dsp from a certain image board i think.

**Comment by f-io** [comment]
Hi @cwildfoerster, I've only read the changelog at https://gitlab.com/gitlab-org/gitlab-foss/-/tree/master.
I'm not that experienced in git, I've only tested it with the above versions and had no issues so far. Maybe that's not the best combination for contribution, but I'm willing to learn.

**Comment by cwildfoerster** [comment]
I always check the corresponding tree/tag https://gitlab.com/gitlab-org/gitlab-foss/-/tree/v13.4.4 , master may/can be on RC state. Maybe i can create a PR tomorrow.

And yes, i remembered your board design, added it to my favorites ;-D

**Comment by f-io** [comment]
closed due to no response

**Pull request closed without merging**
