### PR TITLE
Upgrade to 10.2.4

### PR DESCRIPTION
**Pull request by cwildfoerster**

### CODE REVIEW

**Comment by f3l1x** [comment]
I've tested it and it works. Good job.

**Comment by xNevo** [comment]
When is this going to be merged?

**Comment by cwildfoerster** [comment]
Seems like unfortunately @sameersbn and @solidnerd are pretty busy the last couple of weeks :(

**Comment by solidnerd** [comment]
@cwildfoerster Sorry for the long waiting. I didn't get the notifications for both pr's. I working on it.

**Comment by solidnerd** [comment]
LGTM !

**Pull request merged**
