### PR TITLE
Fix Gitlab Pages Access Control

### LINKED ISSUE #1793: Gitlab Pages is too old / Gitlab Pages Access requires additional arguments
For the Gitlab Pages access control, gitlab pages `v1.3.0` is required, current gitlab pages is too old.

### PR DESCRIPTION
**Pull request by GJRTimmer**
Fixes #1793 

Add full configuration for Gitlab Pages Access Control

### CODE REVIEW

**Comment by GJRTimmer** [comment]
Rebased to 11.5.1

**Comment by GJRTimmer** [comment]
@solidnerd DONE

**Comment by GJRTimmer** [comment]
@solidnerd can you restart CI

**Comment by solidnerd** [comment]
Hey,

this will be released with `11.6.0`. Thanks for your work. I need to cherry-pick it manually but you can find it here https://github.com/sameersbn/docker-gitlab/commit/5c59e16edb53976330dbcacfd5e22b265b780b2c .

**Comment by solidnerd** [comment]
Can be closed now. This was merged through #1827 .

**Pull request closed without merging**
