### PR TITLE
Various fixes to health check scripts

### LINKED ISSUE #2992: healthcheck not works
run
```
curl http://localhost/-/liveness
```

response
```
{"error":"Not Found","status":404}
```

run
```
curl http://127.0.0.1/-/liveness
```

response
```
{"status":"ok"}
```

### PR DESCRIPTION
**Pull request by kkimurak**
close #2992, partially implement #2766

Access to health check resources such as /-/liveness is restricted to IPs specified in gitlab.monitoring.ip_whitelist (`GITLAB_MONITORING_IP_WHITELIST`).
Currently healthcheck may report unhealthy because the name `localhost` is solved to IPv6 loopback address (::1) that is not listed in the whitelist by default.  

This PR fix the issue by using 127.0.0.1 (IPv4 loopback address) instead of `localhost` for monitoring endpoint url.

Possible alternate designs:
- Add IPv6 loopback to whitelist
- Disable IPv6 for gitlab container by specifying `net.ipv6.conf.all.disable_ipv6=1` in docker-compose.yml for example See https://github.com/sameersbn/docker-gitlab/issues/2766#issuecomment-2098030791

/cc @Gaibhne I have create commit based on your suggestion in #2766 so I have set you an author of the commit. Let me know if you don't like it.

### CODE REVIEW

**Comment by kkimurak** [comment]
request for comment: Should this PR contains all suggestion in #2766?

**Comment by sachilles** [comment]
@kkimurak Yes, this would be nice. However, do you have an idea to adress all issues?

**Comment by kkimurak** [comment]
@sachilles Ok, I'll try to implement it by the next release. As far as I checked, the suggestion contains everything to do.

**Comment by sachilles** [comment]
@kkimurak Thank you! But please bear in mind that the reverse proxy can also play an important role in the choice of protocol in the curl command (depending on whether the reverse proxy terminates the SSL connection or not).

**Comment by kkimurak** [comment]
I've implemented all (4) changes based on the current master (v17.3.3), but I haven't been able to test them yet as my local environment has become very slow. It's taking over 10 hours to build the image..

**Comment by kkimurak** [comment]
CI failed due to timeout.

**Comment by kkimurak** [comment]
Now CI looks succeed. It seems like it was automatically restarted after it failed.

**Comment by sachilles** [comment]
@kkimurak I did the restart of the CI. However, in my setup the healthcheck is working. I'll backport the healthcheck into the 17.x branches and the 16.11.x branch as well.

**Comment by sachilles** [comment]
Backport is done by cherry-picking the commits.

**Comment by kkimurak** [comment]
@sachilles Thank you.

**Comment by sachilles** [comment]
You're welcome.

**Pull request merged**
