### PR TITLE
Create version bump script

### PR DESCRIPTION
**Pull request by drubin**
Simple script to replace the version of gitlab in all the files.
Works on osx and linux

### CODE REVIEW

**Comment by pieterlange** [comment]
This also rewrites the `Changelog.md` which is probably unintended.

I just clumsily did something similar while staging a version bump (which should be *easy*) but it is easily manually patched. Excuse my french:
`for file in $(grep -r 10.3.3 . | cut -d: -f1 | sort | uniq); do sed -i 's/10.3.3/10.3.4/g' $file ;done`

**Comment by drubin** [comment]
Thanks. Will fix it to exclude the changelog. But yes it should be easier. The annoying bit is also making it work both on mac and Linux.

**Comment by drubin** [comment]
FIxed to exclude the changelog.

**Comment by drubin** [comment]
@solidnerd ping?

**Pull request closed without merging**
