### PR TITLE
Upgrade to GitLab CE 15.7.2

### PR DESCRIPTION
**Pull request by antt1995**

### CODE REVIEW

**Comment by etlam** [comment]
@sachilles Please approve, as this is a security release.

**Comment by gregorg** [comment]
Anyone else can approve this ? This version contain important security fixes.

**Review by sachilles — APPROVED** [review]
LGTM. Thanks for your contribution.

**Comment by etlam** [comment]
@sachilles I do not see any new docker images, do we still have to wait a few minutes or is it because of the missing github release for v15.7.2?

**Comment by sachilles** [comment]
Hi,

the docker image will be built and published automatically via the circle ci. Thus, the image needs some time to be published via dockerhub and quay.io. Usually it takes about 40 minutes to be published.

**Pull request merged**
