### PR TITLE
Add Gitlab-monitor export for Prometheus

### PR DESCRIPTION
**Pull request by damiendurant**
Add GitLabMonitor process to allow prometheus metrics monitoring

### CODE REVIEW

**Comment by solidnerd** [comment]
Hey, thanks for PR. 👍  This is quite looking interesting. What I missed here is a documentation for that feature and a docker-compose.yml that have all required components like Prometheus and Grafana. Could you do that ?

**Comment by damiendurant** [comment]
Hi,

Some documentation on gitlab-monitor can be found here : 
https://gitlab.com/gitlab-org/gitlab-monitor
I didn't add any specific parameters or env varaibles for the monitor part. I guess we could add the gitlab-mon port number as env parameters.

I don't used to docker-compose because I work on kubernetes. I could have a look for adding prometheus, but as I use a specific profesional image of grafana I will not be allowed to add that part. Please also notice that there is no hard dependencies between gitlab-mon and prometheus. Gitlab-mon expose metrics whereas one ou several prometheus instances are fetching it.

**Comment by damiendurant** [comment]
Hi,

I have updated (but not tested) the docker-compose. 
I have also updated the readme the describe how to setup the dashboard on grafana.

**Comment by jostyee** [comment]
@damiendurant can you do a rebase?

**Comment by damiendurant** [comment]
Done !

**Comment by nixel2007** [comment]
any chance to merge this soon?

**Comment by maffelbaffel** [comment]
I would also really like this to be merged :)

**Comment by DrMurx** [comment]
Is there something we could do to help this PR being accepted (beside fixing the new conflicts)?

**Comment by yuankunzhang** [comment]
@damiendurant 

I have built a merged version of Docker image but unfortunately I cannot make it work. It turns out that there is a curly brace missing in `assets/runtime/functions`. [Here](https://github.com/yuankunzhang/docker-gitlab/commit/a45989ea22f8e8dee103df5d4df96d5d32eaf72d) you can find my fix.

**Comment by lborguetti** [comment]
Hi guys, 

Any updates about this PR?

Thanks,

**Comment by yuankunzhang** [comment]
Hi guys,

Besides this Gitlab Monitor, Gitlab itself exposes a list of metrics. To enable this, you should:

1. In the admin area, check `Enable Prometheus Metrics`;
2. Add a new environment variable named `prometheus_multiproc_dir`, and set it to a valid directory, e.g. `/dev/shm`.

Please refer to [this doc](https://docs.gitlab.com/ee/administration/monitoring/prometheus/gitlab_metrics.html) for more details.

**Comment by derchrisuk** [comment]
@yuankunzhang any idea how to set that variable in the context of the docker-compose file, and make it persistent ?

**Comment by jostyee** [comment]
@derchrisuk
- `Enable Prometheus Metrics` is stored in database
- you can set `prometheus_multiproc_dir` in docker-compose.yml as below:
    ```
    environment:
      - prometheus_multiproc_dir=/dev/shm
    ```

**Comment by derchrisuk** [comment]
@jostyee ah, right.
I have seen so many PR or issues to add a certain variable that I thought this had to be coded into the docker files/install first. Seems to work.
Thanks.

**Comment by Meowbeast** [comment]
@yuankunzhang any idea why this isn't working?  Even after I set the env var in Docker, it still says 
image
and 404's when I check the metrics.

image

Do I need a special image when it shows this should be available in GitLab's official image?

**Comment by derchrisuk** [comment]
@Meowbeast looks like you are trying to set it from within Gitlab.
This needs to go into the either the docker cmd command, or the docker-compose file.
And the image needs to be restarted.

**Comment by Meowbeast** [comment]
@derchrisuk Thanks for the reply.

I'm setting this using Rancher, which is adding to docker-compose file and restarting.

**Comment by derchrisuk** [comment]
I'm not using Rancher, but the compose file from this repo with normal docker CLI.

**Comment by Meowbeast** [comment]
Ok, so that was really my original question...to get this to work I need to use THIS repo?  This isn't something that works using the official GitLab docker image `gitlab\gitlab-ce`?

**Comment by derchrisuk** [comment]
I don't know.
Would say should work with any.
You have to make sure you add the env to the gitlab docker itself.

**Comment by yuankunzhang** [comment]
@Meowbeast Due to the warning message, the `prometheus_multiproc_dir` env var does not take effect. Can you print out all the env vars of the running Gitlab process inside your Docker container?

**Comment by Meowbeast** [comment]
Here is `printenv` from inside the container.

image

**Comment by yuankunzhang** [comment]
@Meowbeast And what about env vars for the exact Gitlab process? Please do the following.

Find the PIDs:

```
root@459e22c67ad0:/# ps -ef | grep 'gitlab/gitlab-rails/etc'
git        765     1  0 04:31 ?        00:00:22 unicorn master -D -E production -c /var/opt/gitlab/gitlab-rails/etc/unicorn.rb /opt/gitlab/embedded/service/gitlab-rails/config.ru
git        880   765  0 04:31 ?        00:00:07 unicorn worker[0] -D -E production -c /var/opt/gitlab/gitlab-rails/etc/unicorn.rb /opt/gitlab/embedded/service/gitlab-rails/config.ru
...
```

Check env vars:

```
root@459e22c67ad0:/# su - git -c 'cat /proc/765/environ' | tr \\0 \\n
prometheus_multiproc_dir=
environment=production
unicorn_rb=/var/opt/gitlab/gitlab-rails/etc/unicorn.rb
user=git
...
```

**Comment by Meowbeast** [comment]
@yuankunzhang you are correct, it is showing unset in the process itself.  I'm a bit confused on why the container would have the env var, but the process is blank.

**Comment by yuankunzhang** [comment]
@Meowbeast I'm not familiar with the mechanism of Rancher setting the env vars. Can you capture Rancher's output docker-compose.yml and see what's happening?

**Comment by Meowbeast** [comment]
Here is the relevant section of docker-compose:

image

**Comment by yuankunzhang** [comment]
@Meowbeast 

As for the official Docker image, seems like setting `prometheus_multiproc_dir` in docker-compose.yml will not take effect. According to [this doc](https://docs.gitlab.com/omnibus/docker/README.html), there're only a limited number of environment variables that can be used in the docker-compose.yml file.

Since you're using Rancher, I'm not sure if you can do the following operations (which shall be working) toward your running Docker image.

**Attention is needed here, I strongly suggest you first test it in a dev environment.**

Edit the `gitlab.rb` file by hand:

```
docker exec -it xxx vim /etc/gitlab/gitlab.rb
```

Find (or add, if not yet exists) the `gitlab_rails['env']` section, and add our dreaming env var here:

```
gitlab_rails['env'] = {
    ...
    'prometheus_multiproc_dir' => '/dev/shm'
}
```

Lastly, save the file and run this command to restart it:

```
docker restart xxx
```

**Comment by Meowbeast** [comment]
Aaaaye.  That worked!

Thanks a lot, @yuankunzhang

**Comment by andypost** [comment]
Passing via `docker-compose.yml` works for me

``` yml
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      gitlab_rails['env'] = { 'prometheus_multiproc_dir' => '/dev/shm' }
```

**Comment by gazben** [comment]
When will the merge happen?

**Comment by damiendurant** [comment]
Above version 10.0.0, gitlabmonitor is included.

Just have to : 
* Add environement variable for setting prometheus_multiproc_dir
* Activate Prometheus metrics in Gitlab setting


I close the merge request.

**Comment by solidnerd** [comment]
@damiendurant  Would you like make a PR for the environment variable ?

**Comment by yuankunzhang** [comment]
@damiendurant 

I think your last reply is about **gitlab internal metrics**. And this PR is about **the gitlab-monitor library**. These two are totally different things. Could you please confirm this?

We're gonna need the gitlab-monitor library as we have been using it for a while and it gives us lots of useful metrics.

**Comment by damiendurant** [comment]
The PR was about including https://gitlab.com/gitlab-org/gitlab-monitor.
This seems really similar to promotheus metric in gitlab configuration.
There is also a influxdb export that provide some metrics.



Le 11 oct. 2017 6:18 PM, "Yuankun Zhang" <notifications@github.com> a
écrit :

@damiendurant <https://github.com/damiendurant>

I think your last reply is about *gitlab internal metrics*. And this PR is
about *the gitlab-monitor library*. These two are totally different things.
Could you please confirm this?

We're gonna need the gitlab-monitor library as we have been using it for a
while and it gives us lots of useful metrics.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sameersbn/docker-gitlab/pull/1102#issuecomment-335864781>,
or mute the thread

**Comment by yuankunzhang** [comment]
@damiendurant 

The two have different probes.

For gitlab-monitor:

image

For gitlab prometheus metrics:

image

**Comment by damiendurant** [comment]
Ok, I reopen it so.

**Comment by damiendurant** [comment]
I've try to update from sameer master.

**Comment by isymbo** [comment]
Line 1870, 1871 from the build logs
"Downloading gitlab-monitor v....
The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 8"

Looks like GITLAB_MONITOR_VERSION definition is not checked in?

@damiendurant

**Comment by GJRTimmer** [comment]
Any update on this ?

**Comment by azachar** [comment]
> Hello,
> 
> For information, i have added a docker env "prometheus_multiproc_dir=/dev/shm", and it's work :)
> 
> Steps to add /-/metrics :
> 
> * Add GITLAB_MONITORING_IP_WHITELIST=
> * Add prometheus_multiproc_dir=/dev/shm (or else location)
> * Check "Enable Prometheus Metrics"
> * Restart

Dear @LordFPL,

Did you apply it to the original installation, without this PR?

Thanks,
Andrej

**Comment by paolomainardi** [comment]
It should be nice to have this MR merged, @damiendurant can you fix the conflicting files ?

**Comment by jasonyihk** [comment]
> Hello,
> 
> For information, i have added a docker env "prometheus_multiproc_dir=/dev/shm", and it's work :)
> 
> Steps to add /-/metrics :
> 
> * Add GITLAB_MONITORING_IP_WHITELIST=
> * Add prometheus_multiproc_dir=/dev/shm (or else location)
> * Check "Enable Prometheus Metrics"
> * Restart

Following this steps and works as a charm. lates gitlab @ 13.8.4

**Pull request closed without merging**
