### PR TITLE
GitLab CE 10.0.0

### PR DESCRIPTION
**Pull request by evenh**
This is a cleaned up version of #1357.

### CODE REVIEW

**Comment by phenomax** [comment]
LGTM!

**Comment by phenomax** [comment]
Can this be merged @solidnerd @sameersbn

**Comment by evenh** [comment]
Any chance to review this @sameersbn?

**Comment by paolomainardi** [comment]
LGTM

**Comment by Ilya-Kuchaev** [comment]
@solidnerd, @sameersbn Any news here?

**Comment by patrickc91** [comment]
@Ilya-Kuchaev They both mentioned they were computer-less until sometime this week. One of them said they might be near a computer on Wednesday though.

**Comment by cwildfoerster** [comment]
Well, we could just upgrade to 10.0.2 all together :)

**Comment by solidnerd** [comment]
I'm back from vacation. I updated nodejs to 8.X for fixing all the warnings with yarn.  For the rest it's LGTM !

**Comment by evenh** [comment]
Awesome! I've rebased the other two pull requests against the updated branch as well.

**Pull request merged**
