### PR TITLE
Upgrade go version to 1.7.4

### PR DESCRIPTION
**Pull request by jostyee**
Go 1.7 has great performance improvements compare to 1.6

### CODE REVIEW

**Comment by jostyee** [comment]
@solidnerd I haven't found any compatibility issue upgrading to 1.7.4

**Comment by sameersbn** [comment]
I've preferred to stick with the upstream instructions to avoid unnecessary support requests. http://docs.gitlab.com/ce/install/installation.html#3-go suggests using Go 1.5.3 but I see we have already switched to using a newer version a while back.

**Comment by lenovouser** [comment]
@sameersbn I think they just don't update the documentation every time a new version of Go comes out. Doesn't seem like a suggestion to me.

Also @jostyee - you replaced `sameersbn` with `jostyee` everywhere in your commit 😃

**Comment by jostyee** [comment]
@lenovouser I'm sorry I was testing dockerhub...
close this pr for now since I looked into gitlab-workhorse source code, it built on Go 1.5 and I couldn't say I enjoyed it.

**Comment by andypost** [comment]
Here's a related issue https://gitlab.com/gitlab-org/gitlab-workhorse/issues/55

**Pull request closed without merging**
