### PR TITLE
Gitlab 10.7.3

### PR DESCRIPTION
**Pull request by evenh**
See [announcement post](https://about.gitlab.com/2018/05/03/gitlab-10-7-3-released/) for detailed changes.

### CODE REVIEW

**Comment by drujd** [comment]
https://golang.org/doc/devel/release.html#go1.9

Just change the version in Dockerfile.

**Comment by evenh** [comment]
Ping @solidnerd @sameersbn

**Comment by cwildfoerster** [comment]
Any sign of life from @solidnerd or @sameersbn ?

**Comment by solidnerd** [comment]
Sorry for waiting for this. I tested it and afterwards I had forget to merge it. 

So

LGTM !

**Comment by Ilya-Kuchaev** [comment]
https://hub.docker.com/r/sameersbn/gitlab/builds/
```
Build failed: The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E1DD270288B4E6030699E45FA1715D88E1DF1F24 && echo "deb http://ppa.launchpad.net/git-core/ppa/ubuntu xenial main" >> /etc/apt/sources.list && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 80F70E11F0F0D5F10CB20E62F5DA5F09C3173AA6 && echo "deb http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu xenial main" >> /etc/apt/sources.list && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8B3981E7A6852F782CC4951600A6F0A3C300EE8C && echo "deb http://ppa.launchpad.net/nginx/stable/ubuntu xenial main" >> /etc/apt/sources.list && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' > /etc/apt/sources.list.d/pgdg.list && wget --quiet -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && echo 'deb https://deb.nodesource.com/node_8.x xenial main' > /etc/apt/sources.list.d/nodesource.list && wget --quiet -O - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && echo 'deb https://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y supervisor logrotate locales curl nginx openssh-server mysql-client postgresql-client redis-tools git-core ruby${RUBY_VERSION} python2.7 python-docutils nodejs yarn gettext-base libmysqlclient20 libpq5 zlib1g libyaml-0-2 libssl1.0.0 libgdbm3 libreadline6 libncurses5 libffi6 libxml2 libxslt1.1 libcurl3 libicu55 libre2-dev tzdata && update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX && locale-gen en_US.UTF-8 && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales && gem install --no-document bundler && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 2
```

**Comment by solidnerd** [comment]
I will look at it later probably we gonna switch to travis direct builds.

Kuchaev Ilya <notifications@github.com> schrieb am Mi., 16. Mai 2018, 08:48:

**Comment by solidnerd** [comment]
I retriggered the build through setting the git tag again. For more information look at:
 https://hub.docker.com/r/sameersbn/gitlab/builds/bzjm4ogivatgqfakcprl9a7/

**Comment by solidnerd** [comment]
#1602

**Pull request merged**
