### PR TITLE
[GitLab Critical Security Release] Upgrade to GitLab CE 15.7.5

### PR DESCRIPTION
**Pull request by rubensilva09**
GitLab Patch Release: 15.7.5 (see https://about.gitlab.com/releases/2023/01/17/critical-security-release-gitlab-15-7-5-released/)

### CODE REVIEW

**Comment by gregorg** [comment]
@sachilles  @sameersbn 🙏

**Comment by Re4zOon** [comment]
BTW does anyone know if its a new feature in gitlab 15.7 to warn people of security fixes?

**Review by sachilles — APPROVED** [review]
LGTM. Thank you for your contribution.

**Comment by sachilles** [comment]
Sorry, but the merge will be delayed because we need to fix the CI pipeline first.

**Comment by rubensilva09** [comment]
Hi,
I am not very familiar with circle CI. Do i need to do anything ?
Thank you

**Comment by xueshanf** [comment]
> BTW does anyone know if its a new feature in gitlab 15.7 to warn people of security fixes?

Yes, but only for "Admin" users.

**Comment by sachilles** [comment]
No, you can't do anything. This needs to be fixed by the owner. I contacted him already. I think he will respond very promptly.

**Comment by sachilles** [comment]
@rubensilva09 I prepared the corresponding PRs for GitLab CE 15.5.9 and 15.6.6 and the CI seems to work. Could you try to force a push just to kick the CI a bit? (Somehow I can't retrigger the CI build via the webinterface.)

**Comment by sachilles** [comment]
I'll close this PR in favor of #2696.

**Pull request closed without merging**
