### PR TITLE
GitLab 8.14.0

### PR DESCRIPTION
**Pull request by solidnerd**
Hello,
I prepared everything for `8.14.0` what I found that needed to be updated. I will start with testing tomorrow. Happy Testing for everyone else 😄

### CODE REVIEW

**Comment by reynold-lariza** [comment]
Seems to be working fine with my setup.

**Comment by reynold-lariza** [comment]
there is just one thing though, I noticed the version for GitLab Workhorse seems to be missing?

image

**Comment by virtuman** [comment]
From the omni gitlab-ce install i see that workhorse should be version 0.8.5:
screen shot 2016-11-24 at 10 08 43 am

**Comment by solidnerd** [comment]
Hey,
on the stable branch is `1.0.0`and at the update guide as well.

Here are the links:
https://gitlab.com/gitlab-org/gitlab-ce/blob/8-14-stable/GITLAB_WORKHORSE_VERSION
https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/8.13-to-8.14.md

**Comment by virtuman** [comment]
I'm guessing that official omnibus gitlab image hasn't been updated to use v1.0.0, i just reinstalled omnibus and it's still on v0.8.5

Any chance 8.14 will be merged in today ?

**Comment by Ilya-Kuchaev** [comment]
Or even today?

**Comment by youuri** [comment]
Or even tomorrow ;D

**Comment by lenovouser** [comment]
Or even the day after tomorrow?

**Comment by virtuman** [comment]
@solidnerd anything i or anyone can try doing to expedite this merge request ?
Thanks

**Comment by solidnerd** [comment]
Or now 😛

**Comment by splattael** [comment]
Thank you for releasing! It works like a charm :purple_heart: :sparkles:

**Pull request merged**
