### PR TITLE
Add support to build arm64 image

### PR DESCRIPTION
**Pull request by kkimurak**
This PR allow us to build arm64 image in addition to currently supported amd64.

Originally I have posted a patch to #2603 . I would love to hear your thoughts (and hopefully reports on how it works) from the community here - including whether or not we should support it. 

Also please note that this PR does not modify CI configuration - This is to ensure that this change does not break existing amd64 image builds and continues to work.

You can test this PR after applying the patch and run `docker buildx build --platform linux/arm64 .`

### CODE REVIEW

**Comment by kkimurak** [comment]
Made sure to pass shellcheck.

**Comment by kkimurak** [comment]
Corrected download message (uninitialized variable in use).

**Comment by kkimurak** [comment]
rebased onto 15.10.3

**Comment by kkimurak** [comment]
rebased onto 15.11.3

**Comment by kkimurak** [comment]
rebased onto 16.0.3.

If this work is not merged in the future, it would be helpful if you could close it and state that there are no plans to prepare an image for the arm platform.

**Comment by sachilles** [comment]
@kkimurak Apologies for my poor availability.

In principle I don't see any problems by supporting ARM64 if there are contributors that support this work an help to publish the corresponding images regularly. So far I didn't provide images for multiple architectures und thus, I'll need help on this.

**Comment by Jack12816** [comment]
I would love to see this merged and made available. <3 Thanks for the contribution @kkimurak! 

Maybe [this](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/) could help here to enable a multi-arch build via CircleCI. 

I guess `--platform=linux/amd64,linux/arm64` must be added to the `docker build` commands:
* https://github.com/sameersbn/docker-gitlab/blob/master/.circleci/config.yml#L79
* https://github.com/sameersbn/docker-gitlab/blob/master/.circleci/config.yml#L105

and the `docker publish` works transparently. 

@sachilles It would be great if you could merge this PR with the CI addition and see if CI is working properly. If not revert it - then we could iterate on this. :)

**Comment by kkimurak** [comment]
rebased onto 16.2.1.

**Comment by gjrtimmer** [comment]
I would really love this, waiting for my RK1 modules from turing pi. With this I can run my GitLab on my Turing PI.

**Comment by kkimurak** [comment]
Sorry for delay but 

- I'm not going to maintain CI settings (as I stated at first)
- I've lost motivation because the only ARM64 device I owned broke.
- There is a concurrent work "Support Arm Architecture" (#2803). This can be confusing, and I think discussions with the same content should be grouped together (i.e. one should be closed).

I hope someone who need this will take over (or #2803 - not exactly same code but works) .

I apologize again for my selfish actions.

**Pull request closed without merging**
