### PR TITLE
Upgrade to GitLab CE 15.6.0

### PR DESCRIPTION
**Pull request by antt1995**
Upgrade to GitLab CE 15.6.0

### CODE REVIEW

**Comment by antt1995** [comment]
https://about.gitlab.com/releases/2022/11/22/gitlab-15-6-released/

**Review by sachilles — APPROVED** [review]
LGTM

**Comment by sachilles** [comment]
Thanks for supporting this project.

**Comment by antt1995** [comment]
@sachilles Found that Golang needs to be updated to run/build GitLab
Also updated ruby as per GitLab omnibus versions
https://gitlab.com/gitlab-org/gitlab-omnibus-builder/-/blob/master/docker/VERSIONS

**Comment by antt1995** [comment]
`Build gitlab-workhorse
make: Entering directory '/home/git/gitlab/workhorse'
fatal: detected dubious ownership in repository at '/home/git/gitlab'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/git/gitlab
### Building gitlab-resize-image
go build -ldflags "-X main.Version=v15.6.0 -X main.BuildTime=20221123.113334" -tags "tracer_static tracer_static_jaeger continuous_profiler_stackdriver" -o /home/git/gitlab/workhorse/gitlab-resize-image gitlab.com/gitlab-org/gitlab/workhorse/cmd/gitlab-resize-image
go: downloading github.com/disintegration/imaging v1.6.2
go: downloading golang.org/x/image v0.0.0-20220722155232-062f8c9fd539
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
make: *** [Makefile:60: gitlab-resize-image] Error 1
make: Leaving directory '/home/git/gitlab/workhorse'
The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 2

Exited with code exit status 2`

Darn

**Comment by antt1995** [comment]
Well thats annoying, Need to upgrade golang to build but cannot build with newer golang

**Comment by antt1995** [comment]
Trying Other versions of Go

**Comment by antt1995** [comment]
Okay, need to add these to the assets/build/install.sh
git config --global --add safe.directory /home/git/gitlab
exec_as_git git config --global --add safe.directory /home/git/gitlab

Also reverted ruby and updated go to v1.18.8

**Comment by antt1995** [comment]
Should build now

**Review by sachilles — APPROVED** [review]
Thanks for fixing and for troubleshooting.

**Pull request merged**
