### PR TITLE
Upgrade GitLab CE to 16.0.0

### PR DESCRIPTION
**Pull request by sachilles**
GitLab 16.0 Release (see <https://about.gitlab.com/releases/2023/05/22/gitlab-16-0-released/>)

This PR is work-in-progress. Feel free to discuss and contribute.

### CODE REVIEW

**Comment by sachilles** [comment]
TODOs

- [ ] check if `assets/build/config/database.yml.postgresql` can be removed 
- [ ] check if `assets/runtime/config/gitlabhq/database.yml` will be filled correcty and if GitLab works
- [ ] fix [building Gitaly](https://app.circleci.com/pipelines/github/sameersbn/docker-gitlab/1120/workflows/e8be53c6-85a7-4a22-af72-2f3d09321f8f/jobs/5403?invite=true#step-102-4073) which currently fails due to [missing directory](https://app.circleci.com/pipelines/github/sameersbn/docker-gitlab/1120/workflows/e8be53c6-85a7-4a22-af72-2f3d09321f8f/jobs/5403?invite=true#step-102-4707)

**Comment by kkimurak** [comment]
For gitaly build issue: The build itself succeed. The process copying `ruby` is in our `install.sh` script.  

This seems to be a planned removal of ruby (gitaly-ruby) on upstream. See [gitlab-org/gitlay!5512](https://gitlab.com/gitlab-org/gitaly/-/merge_requests/5512) , [gitlab-org/gitaly!5671](https://gitlab.com/gitlab-org/gitaly/-/merge_requests/5671) and so on.  

At this time, we can simply remove the line.

````diff
diff --git a/assets/build/install.sh b/assets/build/install.sh
index b84cbe90..b78e6b8c 100755
--- a/assets/build/install.sh
+++ b/assets/build/install.sh
@@ -146,7 +146,6 @@ git clone -q -b v${GITALY_SERVER_VERSION} --depth 1 ${GITLAB_GITALY_URL} ${GITLA     
 # install gitaly
 make -C ${GITLAB_GITALY_BUILD_DIR} install
 mkdir -p ${GITLAB_GITALY_INSTALL_DIR}
-cp -a ${GITLAB_GITALY_BUILD_DIR}/ruby ${GITLAB_GITALY_INSTALL_DIR}/
 cp -a ${GITLAB_GITALY_BUILD_DIR}/config.toml.example ${GITLAB_GITALY_INSTALL_DIR}/config.toml
 rm -rf ${GITLAB_GITALY_INSTALL_DIR}/ruby/vendor/bundle/ruby/**/cache
 chown -R ${GITLAB_USER}: ${GITLAB_GITALY_INSTALL_DIR}
````

**Comment by kkimurak** [comment]
I'm testing local build of your branch.

1. `assets/build/config/database.yml.postgresql` could not be removed - reports following error on build:

    ````
    rake aborted!
    ERROR: This installation of GitLab uses unsupported database names in 'config/database.yml': geo, embedding. The only supported ones are main, ci, main_clusterwide.
    ````
    
    We still need to remove `geo` section. This is really strange ..

1. `config/gitlab.yml` is updated as expected. Nicely done.   
    With `DB_HOST=postgresql`, `DB_NAME=gitlabhq_production`, `DB_PORT=5432` and suitable `DB_USER`, `DB_PASS`, I got following result.  
  
    ````sh
    $ docker-compose exec gitlab cat /home/git/gitlab/config/database.yml
    #
    # PRODUCTION (here: non-decomposed database)
    #
    production:
      main:
        adapter: postgresql
        encoding: unicode
        database: gitlabhq_production
        host: postgresql
        port: 5432
        username: [masked]
        password: [masked]
        pool: 10
        prepared_statements: true
      ci:
        adapter: postgresql
        encoding: unicode
        database: gitlabhq_production
        database_tasks: false
        host: postgresql
        port: 5432
        username: [masked]
        password: [masked]
    ````
    There may be a request to set separate values ​​for the `ci:` section and the `main:` section. We would need the corresponding parameters then - but not now. It is not a requirement to do that work here.

I have successfully launch v16.0.0.

image

**Comment by sachilles** [comment]
@kkimurak Thanks for supporting this PR. The `install.sh` script is updated.

However, I'm really surprised that the replacement of the file `assets/build/config/database.yml.postgresql` just differs in the additional `ci:` sections. The `geo:` sections are just comments (as before). This is really strange.

**Comment by sachilles** [comment]
I confirm that the build was succesful and did launch GitLab 16.0.0 successfully.

grafik

**Comment by sachilles** [comment]
In favor of the next critical security release (GitLab v16.0.1) I'll merge this PR. As suggested by @kkimurak there will be some other PR related to the new `ci:` section in the `database.yml`.

**Comment by tDo** [comment]
@sachilles Short question, given the deprecation of postgre 12 on gitlab 16, what's the suggested way to proceed since the original docker-compose file still uses a 12.x postgres image. Thx for your work :)

**Comment by sachilles** [comment]
@tDo Sorry, I wasn't paying attention for. Unfortunately I'm using a separate (with respect to docker an external) database service and no container.

The best way would be to upgrade your postgresql container. However, I suppose that you are using the image `sameersbn/postgresql` which seems to be unmaintained for a long time. Since the last commit on the corresponding repo was in 2020, I guess we should switch to another default and actively maintained project for postgres containers.

**Pull request merged**
