### PR TITLE
Upgrade Gitlab CE to 9.2.6

### PR DESCRIPTION
**Pull request by abeltay**
https://about.gitlab.com/2017/06/15/gitlab-9-dot-2-dot-6-released/

### CODE REVIEW

**Comment by Ilya-Kuchaev** [comment]
Any news here?

**Comment by abeltay** [comment]
@solidnerd is the PR okay?

**Comment by Ilya-Kuchaev** [comment]
@sameersbn @solidnerd Ping

**Comment by solidnerd** [comment]
LGTM !

**Pull request merged**
