### PR TITLE
Fix problems to replace some placeholder values with sed

### LINKED ISSUE #408: Install fails when postgres password has / in it
The container keeps exiting because some sed statements are failing.  The sed statements fail with:
sed: -e expression #1, char 19: unknown option to `s'

I discovered this was the root cause by adding DEBUG_ENTRYPOINT into my environment.

P.S.  No rush on this issue.  I am changing the password to my postgres user.

### PR DESCRIPTION
**Pull request by JrCs**
Keep the same template files but use envsubst instead of sed to replace placeholder values.

Resolves #408 and #516

Use a generic function (replace_placeholders) to make the job.

### CODE REVIEW

**Comment by sameersbn** [comment]
I see you made the changes for all configurations. I test locally and let you know. thanks for the PR.

**Comment by sameersbn** [comment]
Have merged upstream changes and updated to use replace_placeholders (renamed to update_template) whenever possible. You can take a look at the changes here https://github.com/JrCs/docker-gitlab/compare/master...sameersbn:JrCs-pr-updates. I am currently testing these changes on my local install and will merge the PR after I am confident that it will not lead to breakages :smile:

**Comment by sameersbn** [comment]
was also thinking of updating `update_template` to automatically select the user for executing `envsubst` based on the ownership of the target file. This will allow us to use `update_template` also for the nginx configuration updates

**Comment by JrCs** [comment]
Good idea

**Pull request closed without merging**
