### PR TITLE
fix(#3010) Add symbolic link to the correct location of ca-cert file

### PR DESCRIPTION
**Pull request by ymazzer**
A pull request including the fix for the #3010 issue as fixed in the PR #3016 but isolated to make it easier to merge.

### CODE REVIEW

**Comment by ymazzer** [comment]
@sachilles this issue is quite blocking, is it possible for you to include it in the coming update for 17.5.1?

**Review by sachilles — APPROVED** [review]
Looks good to me

**Comment by sachilles** [comment]
@ymazzer Of course, I'll merge your PR once the CI finished correctly. The problem an ist solution seems to bi quite general. Do you think that we should backport your PR to the last 2 supported versions (i.e. 17.4.x and 17.3.x)?

**Comment by ymazzer** [comment]
> @ymazzer Of course, I'll merge your PR once the CI finished correctly. The problem an ist solution seems to bi quite general. Do you think that we should backport your PR to the last 2 supported versions (i.e. 17.4.x and 17.3.x)?

@sachilles at least 17.4.x, since the problem was present in 17.4.x, I didn't tested it in 17.3.x.

This is a hack to fix the issue, btw this has to be reworked correctly for the coming 17.7 with openssl3

**Pull request merged**
