### PR TITLE
Add: gitlab pages access control (11.5)

### PR DESCRIPTION
**Pull request by GJRTimmer**
Added gitlab pages access control (Introduced in gitlab 11.5).

Fixes: #1769

@sameersbn @solidnerd Request Review

### CODE REVIEW

**Comment by GJRTimmer** [comment]
@solidnerd @sameersbn Any Update

**Comment by solidnerd** [comment]
Will be published with `11.5.0`

**Comment by GJRTimmer** [comment]
@solidnerd Thanks

**Comment by GJRTimmer** [comment]
Rebased onto new master

**Comment by GJRTimmer** [comment]
@solidnerd Rebased on master

**Pull request merged**
