### PR TITLE
Upgrade Gitlab to 13.2.5

### PR DESCRIPTION
**Pull request by vdrahos**

### CODE REVIEW

**Comment by cwildfoerster** [comment]
> lgtm
> 
> A 13.2.6 sees to be out by now.

Yes, there is a new git tag, no blog post yet. But gitaly has also been upgraded to `v13.2.5`/`13.2.6` which is missing in the PR.

**Comment by xasx** [comment]
> Yes, there is a new git tag, no blog post yet. But gitaly has also been upgraded to `v13.2.5`/`13.2.6` which is missing in the PR.

How did you find out? I could not get a updated changelog from gitlab repo.
I guess you know for sure where to look at 😄

**Comment by cwildfoerster** [comment]
> > Yes, there is a new git tag, no blog post yet. But gitaly has also been upgraded to `v13.2.5`/`13.2.6` which is missing in the PR.
> 
> How did you find out? I could not get a updated changelog from gitlab repo.
> I guess you know for sure where to look at 😄

Check the files for the new tag and compare. I once made the mistake by comparing to master. 

https://gitlab.com/gitlab-org/gitlab-foss/-/tree/v13.2.5 :

- https://gitlab.com/gitlab-org/gitlab-foss/-/blob/v13.2.5/VERSION
- https://gitlab.com/gitlab-org/gitlab-foss/-/blob/v13.2.5/GITLAB_WORKHORSE_VERSION
- https://gitlab.com/gitlab-org/gitlab-foss/-/blob/v13.2.5/GITLAB_SHELL_VERSION
- https://gitlab.com/gitlab-org/gitlab-foss/-/blob/v13.2.5/GITLAB_PAGES_VERSION
- https://gitlab.com/gitlab-org/gitlab-foss/-/blob/v13.2.5/GITALY_SERVER_VERSION

**Comment by vdrahos** [comment]
I've created a new PR https://github.com/sameersbn/docker-gitlab/pull/2210 for version 13.2.6

About gitaly: afaik it follows gitlab version regularly, another components have to be checked.

**Pull request closed without merging**
