### PR TITLE
Upgrade to 13.0.0

### LINKED ISSUE #2144: Fail at start due file permissions
12.10.4 fails in error. 12.9.5 works fine
```
Loading /etc/docker-gitlab/runtime/env-defaults
Mapping UID and GID for git:git to 1006:1006
Initializing logdir...
Initializing datadir...
Installing configuration templates...
SSL Key, SSL Certificate and DHParam were not found.
Assuming that the container is running behind a HTTPS enabled load balancer.
SSL key and certificates for Registry were not found
Assuming that the Registry is running behind a HTTPS enabled load balancer.
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::secrets...
Can't open /home/git/gitlab/.gitlab_shell_secret for writing, Permission denied
140680452825536:error:0200100D:system library:fopen:Permission denied:../crypto/bio/bss_file.c:72:fopen('/home/git/gitlab/.gitlab_shell_secret','w')
140680452825536:error:2006D002:BIO routines:BIO_new_file:system lib:../crypto/bio/bss_file.c:81:

```

### PR DESCRIPTION
**Pull request by solidnerd**
Missing Parts:

- [x] Fix #2144 

- [x] Upgrade Postgres to 11.7

### CODE REVIEW

**Comment by achretien** [comment]
https://about.gitlab.com/releases/2020/05/22/gitlab-13-0-released/#postgresql-11-is-now-the-minimum-required-version-to-install-gitlab

Maybe we need to upgrade the postgresql image and the local client libs

**Comment by solidnerd** [comment]
@achretien Yes I can agree. I'll see how we solve this on the best way there are currently two options:

1. Upgrade sameersbn/postgres to support 11.7
2. Use Official Postgres Image and write a migration guide


I think this needs also to be done with redis.

**Comment by cdalvaro** [comment]
It looks like tag `13.0.0` has not been generated. Neither [Docker](https://hub.docker.com/r/sameersbn/gitlab/tags) nor [Quay.io](https://quay.io/repository/sameersbn/gitlab?tab=tags)

```
Pulling gitlab (sameersbn/gitlab:13.0.0)...
ERROR: manifest for sameersbn/gitlab:13.0.0 not found
```

Also I'm having the following issue upgrading from `sameersbn/gitlab:12.10.6-1` using current `latest` tag. (I have updated Redis and Postgres images to the new ones too, `5.0.9` and `11-20200524` respectively)

```
Your current database version is too old to be migrated.
You should upgrade to GitLab 11.11.0 before moving to this version.
Please see https://docs.gitlab.com/ee/policy/maintenance.html#upgrade-recommendations
```

**Comment by cwildfoerster** [comment]
Same error here as cdalvaro...  but upgrading from 12.9.5 due to #2144

**Comment by cdalvaro** [comment]
> Same error here as cdalvaro... but upgrading from 12.9.5 due to #2144. currently running 12.9.5 with postgres 11 and redis 5.
> 
> **EDIT** @solidnerd @cdalvaro the error is due to postgresql upgrading from the wrong dataset. i was running sameersbn/postgresql:10-2 before, but postgresql `11` upgraded from the `9.6` dataset... deleting the `9.6` folder from the postgresql volume fixes that, so the `11` database is the upgraded `10`. If you don't have a backup, i guess stopping the container, deleting both `9.6`and the wrong `11`folder might work.

I was trying this right now, @cwildfoerster!
I can confirm that deleting all version directories except `10` do the trick! 🎉

**Comment by MatthiasHertel** [comment]
@cdalvaro 
what do u mean with deleting all versions ?? 
>I can confirm that deleting all version directories except 10 do the trick! tada

did u mean to delete the mounted volume ? but there is the data from gitlab :thinking: 

my current gitlab version is 12.10.6 here my snippet from my docker-compose.yml , with the relevant parts:
```
...
postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    - gitlab_network
  gitlab:
    restart: always
    image: sameersbn/gitlab:latest
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "22:22"
    volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data:Z
    - /srv/docker/certs:/certs
```

thank u for help!

**Comment by gazben** [comment]
@MatthiasHertel This was the same problem for me.
Do a listing for the directories:
```
root@gitlab:/home/services/gitlab/data/postgresql# du -d 1 -h
443M    ./12
1.2G    ./10
1.7G    .
```

Stop and remove all the containers. There was 9.5,9.6 folders but I deleted them. I made a backup from this folder. After that I deleted the 12 folder and only kept the 10 folder. Start everything and wait.
Don't forget the backup: `cp -a postgresql postgresql.old`

**Comment by cdalvaro** [comment]
Hi @MatthiasHertel!

If you make an `ls -l` under `/srv/docker/gitlab/postgresql` you should see something similar to this:

```
drwx------ 1  101  103   8 Jul 17  2018 9.6/
drwx------ 1  101  103   8 May 25 10:47 9.5/
```

and whatever previous version you haven't removed before.

So try copying all the content inside `/srv/docker/gitlab/postgresql` to a secure place as a backup, and then remove all versions but the latest from `/srv/docker/gitlab/postgresql`.

This should work... 🤞

**Comment by MatthiasHertel** [comment]
@cdalvaro 

hi this is my output from my mounted volume from postgres:
```
ll /srv/docker/gitlab/postgresql
total 12
drwxr-xr-x 3 syslog syslog 4096 Jun 12  2018 ./
drwxr-xr-x 7 root   root   4096 Jun 18  2018 ../
drwx------ 3 syslog syslog 4096 Jun 12  2018 9.6/
```

i have only one dir there , should i leave it and just update my compose-yml to:
```
postgresql:
    restart: always
    image: sameersbn/postgresql:11.2
  gitlab:
    restart: always
    image: sameersbn/gitlab:latest
```

and then run `docker-compose up -d` for recreation ?

**Comment by cdalvaro** [comment]
> @cdalvaro
> 
> hi this is my output from my mounted volume from postgres:
> 
> ```
> ll /srv/docker/gitlab/postgresql
> total 12
> drwxr-xr-x 3 syslog syslog 4096 Jun 12  2018 ./
> drwxr-xr-x 7 root   root   4096 Jun 18  2018 ../
> drwx------ 3 syslog syslog 4096 Jun 12  2018 9.6/
> ```
> 
> i have only one dir there , should i leave it and just update my compose-yml to:
> 
> ```
> postgresql:
>     restart: always
>     image: sameersbn/postgresql:11.2
>   gitlab:
>     restart: always
>     image: sameersbn/gitlab:latest
> ```
> 
> and then run `docker-compose up -d` for recreation ?

Yeah!

Just replace the postgresql image by `sameersbn/postgresql:11-20200524` and then:

```sh
docker-compose down # Stop running containers
docker-compose pull # In order to get the latest image of sameersbn/gitlab:latest
docker-compose up -d
```

**Comment by MatthiasHertel** [comment]
@cdalvaro 

first of all thx for help ok i will try ... fingercross! hehe

one more question is it best practice for version pinning of the images ... i used this repo here always with latest tag for gitlab service ... is it right so ?

**Comment by cwildfoerster** [comment]
Well, for some non essential services i use latest too... but after the mariadb:latest fiasco a couple of years ago, where the major release upgrade was automatically done (yikes) and my database was shot to pieces, im careful with that :-D

**Comment by cdalvaro** [comment]
If you like living on the edge it is OK 😉

As @cwildfoerster has pointed out, it is better to pinned certain images, such as Postgres and Redis, and you can set gitlab to the `latest` image, you'll only have to worry when you perform a `docker-compose pull`

**Comment by MatthiasHertel** [comment]
@cwildfoerster 
ok good to know ....
nice, your watchtower setup looks interesting ... so u got a notification for breaking changes like the upgrade here with postgresql?

@cdalvaro 
ok thanks a lot ... 

```
grep 'image' docker-compose.yml 
    image: sameersbn/redis:latest
    image: sameersbn/postgresql:11-20200524
    image: registry
    image: sameersbn/gitlab:latest
```

i am on sameersbn/redis:latest (redis 4.0) and in this repo here is redis:5.0.9 (see: https://github.com/sameersbn/docker-gitlab/blob/13.0.0/docker-compose.yml#L6)

**is that a problem ? to simply replace it to this:**

```
grep 'image' docker-compose.yml 
    image: redis:5.0.9
    image: sameersbn/postgresql:11-20200524
    image: registry
    image: sameersbn/gitlab:13.0.0
```

`gitlab:latest` is the same like the pinned version `gitlab:13.0.0`
but redis is a major upgrade (v4 to v5) with replacing it from sameersbn/redis:latest to redis:5.0.9

**is that a problem ?**

sorry i never touch my compose.yml during upgrade process i did it  the lazy way with just pull and up

**Comment by cdalvaro** [comment]
It is safe, Redis is a cache service, and it will work great after the update

**Comment by MatthiasHertel** [comment]
ok nice everything worked out!

for others here are my migration steps to upgrade from `12.10.6` to `13.0.0`:
1. stop container

```
$ docker-compose down
```

2. edit docker-compose.yml (replace image tags see diff below)

```
$ diff docker-compose.old.yml docker-compose.yml 
6c6
<     image: sameersbn/redis:latest 
---
>     image: redis:5.0.9
16c16
<     image: sameersbn/postgresql:9.6-2 
---
>     image: sameersbn/postgresql:11-20200524 
```

3. backup mounted postgresql:
```
$ grep -A 4 'postgresql:' docker-compose.yml 
  postgresql:
    restart: always
    image: sameersbn/postgresql:11-20200524 
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
# cp -r /srv/docker/gitlab/postgresql /backup/gitlab/
```
4. remove all but latest version in postgresql volume (for me 9.6 was the latest)
```
$ ls -l /srv/docker/gitlab/postgresql/
total 16
drwx------ 3 systemd-resolve systemd-resolve 4096 Jun 12  2018 9.6
```
5. pull new images
```
$ docker-compose pull
```
6. start container
```
$ docker-compose up -d
```

:crossed_fingers:

**Comment by solidnerd** [comment]
@MatthiasHertel I would really appreciate as a PR those steps ;) and create a pr with the migration guide for 13.0.0

**Comment by achretien** [comment]
Maybe use you should use docket-compose stop instead of down.

If you use named volume, down command could delete them in some case.

Le mer. 27 mai 2020 à 06:39, Niclas Mietz <notifications@github.com> a
écrit :

**Comment by MatthiasHertel** [comment]
@achretien 
> If you use named volume, down command could delete them in some case.

thx good catch but that has to be explicitly stated with the argument -v ?

delete no volumes
```
docker-compose down
```
delete volumens:
```
docker-compose down -v
```

or i am wrong?

@solidnerd 

yes of course i will make a PR ... what do you think where is a good place for the migration guide?
i will put into the docs folder: https://github.com/sameersbn/docker-gitlab/tree/master/docs ?

**Comment by solidnerd** [comment]
@MatthiasHertel Looks good to me ;)

**Comment by edbergavera** [comment]
> ok nice everything worked out!
> 
> for others here are my migration steps to upgrade from `12.10.6` to `13.0.0`:
> 
> 1. stop container
> 
> ```
> $ docker-compose down
> ```
> 
> 1. edit docker-compose.yml (replace image tags see diff below)
> 
> ```
> $ diff docker-compose.old.yml docker-compose.yml 
> 6c6
> <     image: sameersbn/redis:latest 
> ---
> >     image: redis:5.0.9
> 16c16
> <     image: sameersbn/postgresql:9.6-2 
> ---
> >     image: sameersbn/postgresql:11-20200524 
> ```
> 
> 1. backup mounted postgresql:
> 
> ```
> $ grep -A 4 'postgresql:' docker-compose.yml 
>   postgresql:
>     restart: always
>     image: sameersbn/postgresql:11-20200524 
>     volumes:
>     - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
> # cp -r /srv/docker/gitlab/postgresql /backup/gitlab/
> ```
> 
> 1. remove all but latest version in postgresql volume (for me 9.6 was the latest)
> 
> ```
> $ ls -l /srv/docker/gitlab/postgresql/
> total 16
> drwx------ 3 systemd-resolve systemd-resolve 4096 Jun 12  2018 9.6
> ```
> 
> 1. pull new images
> 
> ```
> $ docker-compose pull
> ```
> 
> 1. start container
> 
> ```
> $ docker-compose up -d
> ```
> 
> 🤞

@MatthiasHertel The steps worked for me. I came from gitlab 12.9.2, postgre 10 and redis latest.

**Comment by gekko42** [comment]
Thank you very much for the help. 
I have the folders 9.6/ and 10/ in the postgresql folder, since my latest version was 10-2. When I delete/move the 9.6 folder and update to posgresql 11 and gitlab 13, it "doesn't take" the 10/ folder to migrate the database, but creates a complete new, empty instance of gitlab. Any ideas?

**Comment by vhristev** [comment]
I had issue with DB upgrading from old 12.9.2 gitlab with postgresql 9.6. Here is now achieve upgrading to 13.0.6 . I had an issue with PG duplication. 

Upgrade path from 12.9.2 with postgresql 9.6  bypass 13.0.0 (were hit my issue )  and then upgrade latest 

**Phase 1 DB migration without gitlab**
# Now DB is 9.6 and upgrading to 10
I upgrade DB without touching gitlab which means i download postgres 10 run the composer ( wait DB migration ) gitlab was still 12.9.2
After that I move old DB 9.6 out of the folder mine is located here: /volume1/docker/gitlab-hris/postgresql 
- Verify gitlab is working with 12.9.2 and PG 10

# Now DB is 10 and upgrading to 11
I upgrade DB without touching gitlab which means i download postgres 11 run the composer ( wait DB migration ) gitlab was still 12.9.2
After that I move old DB 10 out of the folder mine is located here: /volume1/docker/gitlab-hris/postgresql 
- Verify gitlab is working with 12.9.2 and PG 11 
- image - sameersbn/postgresql:11-20200524


**Phase 2 Upgrade gitlab**
Upgrade gitlab to 13.0.0
DB upgrade is failing with error:

`2020-10-08 16:22:17,664 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

**PG::DuplicateColumn: ERROR:  column "state_enum" of relation "sprints" already exists**
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `exec'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'
`
**Postgre fix:**

`
# Error : PG::DuplicateColumn: ERROR:  column "state_enum" of relation "sprints" already exists

 # Login to postgresql docker container
sudo docker exec -it docker_postgresql_1 /bin/bash

# Login to postgresql DB
root@6b8649719c7f:/var/lib/postgresql# psql -U postgres

# Find DB database name
postgres=#  \l
 
# Connect to DB . In my case is **gitlabhq_production**  
postgres=#  \c gitlabhq_production

# When you are connected to your DB drop bad columns
gitlabhq_production=# ALTER TABLE sprints DROP COLUMN state_enum;

# After cleanup 'sprints' are empty

gitlabhq_production=# select * from sprints;
 id | created_at | updated_at | start_date | due_date | project_id | group_id | iid | cached_markdown_version | state | title
 | title_html | description | description_html
----+------------+------------+------------+----------+------------+----------+-----+-------------------------+-------+------
-+------------+-------------+------------------
`
Continue normal with the upgrade to  13.4.3

**Pull request merged**
