### PR TITLE
Upgrade to GitLab 8.15.5

### PR DESCRIPTION
**Pull request by beevelop**
> Today we are releasing versions 8.16.1, 8.15.5, 8.14.7, and 8.13.12 for GitLab Community Edition (CE) and Enterprise Edition (EE).

> These versions contain important security fixes, and we recommend that all affected GitLab installations be upgraded to one of these versions.

https://about.gitlab.com/2017/01/23/gitlab-8-dot-16-dot-1-security-release/

### CODE REVIEW

**Comment by beevelop** [comment]
@sameersbn @solidnerd I guess this one is obsolete with the latest changes (the upgrade to 8.16.0)?

**Comment by sameersbn** [comment]
8.16.0 has been released. gonna skip this revision

**Comment by iamchanghyunpark** [comment]
@sameersbn Do you mind if I keep a LTS (or stable) version repo that should basically fork from your repo?
If you don't like it I'll keep the docker builds private. [Docker](https://hub.docker.com/r/heartinpiece/gitlab/) [Github fork](https://github.com/iamchanghyunpark/docker-gitlab)

@beevelop I used this commit as a patch for the 8.15.5 patch

**Comment by sameersbn** [comment]
> Do you mind if I keep a LTS (or stable) version repo that should basically fork from your repo?

Instead of an LTS version for reasons outlined by @medokin in https://github.com/sameersbn/docker-gitlab/issues/1058#issuecomment-274474879, my proposal is to maintain the previous months release and apply security fixes to it until the next release it out. This is something that will mostly be manageable for the maintainers.

> If you don't like it I'll keep the docker builds private.

No I do not mind it one bit. The project is licensed under MIT, so you are free to do it

**Comment by iamchanghyunpark** [comment]
@sameersbn I just read through your conversation with @solidnerd and I think if we do get another stable like branch, then that would be great 👍

**Pull request closed without merging**
