### PR TITLE
Fix gitlab pages deamon error when enabling access control

### PR DESCRIPTION
**Pull request by ttphi88**
Fixes https://github.com/sameersbn/docker-gitlab/issues/2155

### CODE REVIEW

**Comment by ttphi88** [comment]
Hi @solidnerd Can you please take a look?

**Comment by ay-b** [comment]
Eager to have this merged. Got fail with gitlab-pages used with auth.

**Comment by mmerickel** [comment]
I applied this patch and it has fixed our 502 Bad Gateway issue with pages. Things broke for me when upgrading from 12.10.6 to 13.0.6.

**Comment by GJRTimmer** [comment]
When will this be merged ?

**Pull request merged**
