### PR TITLE
Upgrade to GitLab CE to 11.8.0

### PR DESCRIPTION
**Pull request by greyferret**

### CODE REVIEW

**Comment by Andrewpk** [comment]
Nice!

**Comment by tiredofit** [comment]
Gitaly Server should be 1.2.0 as per https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.8.0/GITALY_SERVER_VERSION

**Comment by greyferret** [comment]
Thanks! Rebased.

**Comment by solidnerd** [comment]
Hey,

it's not perfect but almost done. You missed the gitlab shell to upgrade to [latest version](https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.8.0/GITLAB_SHELL_VERSION) . I'll cherry-pick mine for this. 

Thanks for your work ;)

**Comment by solidnerd** [comment]
ping @greyferret

**Comment by greyferret** [comment]
@solidnerd gitlab-shell was already version 8.4.4 :)
https://github.com/greyferret/docker-gitlab/blob/upgrade-to-11.8.0/Dockerfile#L10
https://github.com/sameersbn/docker-gitlab/blob/master/Dockerfile#L10

**Comment by solidnerd** [comment]
Ah okay fine let's :shipit:

**Pull request merged**
